== Chapter 2

[.chapter-synopsis]
* Travels and Gospel Labors in New England
* Letter to his Wife

In the spring of 1777, David Sands commenced a journey in New England and parts adjacent,
which occupied him two years and seven months;
he traveled much in the wilderness country,
where at times there was scarcely a track for a horse,
so that they carried an axe to clear the way,
and frequently were obliged to travel on foot, enduring great hardships:
and being during the period of the revolutionary war, he had many trials to pass through,
both in his journeys, and on account of his family.
The following account of this arduous journey is from his Journal:

Having a concern to pay a religious visit to Friends in New England, Rhode Island,
Nantucket, Newport, and as far eastward as way might open,
and this concern being united with by the Monthly and
Quarterly Meetings of Friends to which I belonged,
held at Nine Partners, in the 4th month, 1777,
I left my home and proceeded to Nine Partners,
where my beloved friend Aaron Lancaster lived, who united in my concern.
After attending a solemn meeting, where much labor was bestowed,
and many lively and cheering testimonies borne
by our many beloved and truly dedicated friends,
to the cause we were engaged in, we enjoyed the reward,
promised by our holy Redeemer to his devoted and redeemed children,
who are made willing to give up all;
to whom be ascribed glory and honor forever and evermore.

We commenced our journey, taking many meetings in our way,
which were attended many times with much comfort and encouragement to seeking minds;
likewise appointed meetings, some of which were attended with close and proving feelings,
being a time of great confusion and wars in many parts of the country,
and yet we were enabled to pass quietly through, until we reached Nantucket,
where we were kindly received by our friends.
We proceeded to visit all the families of Friends on the Island,
in which service we were often bowed in thankfulness of
heart to our great and good Master,
who made our way more easy than we could have expected,
and our service appeared truly acceptable to many exercised minds.
We had also much service among other societies,
through all which we were kindly received,
and great sympathy and unity with our labors was
expressed by many of our brethren and sisters.
We spent a considerable time with my much beloved friend and brother in the truth,
William Rotch, whose kindness, and that of his affectionate family, was truly acceptable.
After this visit, we left Nantucket, and went to Newport,
where we attended the week-day meeting, and after it visited several families of Friends,
and continued in that service until the first day of the week,
when we attended Portsmouth and Newport meetings,
and have continued visiting families of Friends,
and attended their meetings for worship and discipline for several days past.
The Lord of the Universe has been pleased to own the labor of his poor servants;
it has been as bread to my soul in this trying season,
whereby I have been enabled to go forward.
I have had in the course of this visit to observe the
wonderful dealings of our Heavenly Father,
and found by experience the necessity of depending on him from day to day,
to point out the way and open the hearts of the people to receive the word of life.
I have found peace to follow resignation and patience, which when attained,
fully compensates for the trying exercises we pass through.

We attended a funeral, and appointed a meeting that afternoon,
amongst the inhabitants and soldiers, which was a favored opportunity,
and cause of refreshment to some;
after which I felt much strengthened both in body and mind.
We were also at the burial of Anna Mitchel, a worthy Friend and elder,
which was a solemn opportunity, and several living testimonies were borne.
We now took leave of our friends in Newport, in great nearness and tender love;
many of us were made to be of one heart and one mind,
and the tendering power of Divine love was over us.
We parted under a sense of divine goodness,
his protecting arm having been visibly made bare amongst us.
Having the company of a number of friends, we came to Portsmouth,
and lodged with Isaac Lawton.
The next day took leave of Friends on that island;
several friends from Newport and Portsmouth
accompanied us as far as the guard would permit.

The various exercises I have had to pass through since being on this island,
have been trying to me,
and I have had sometimes to believe my will was almost
subjected to the will of my Heavenly Father,
who has led me through the water and tried me in the deeps, also through the fire,
that he might purge me from the dross, and "`take away the tin.`"
Nevertheless, he has never forsaken me, nor taken his spirit from me;
he has made a way when there was no way, and has been on the right hand and on the left,
as a wall; and has caused a language to be sounded, saying,
"`Do my servants no harm,`" and may my soul praise His great and glorious name,
while I have a being,
who is worthy of praise from the whole creation forever and forevermore.
He has been a sanctuary to my soul, and preserved me from the hands of the ungodly.
Oh, that men would praise his name!

Having parted with our friends, we were conducted down to the ferry by several officers,
with a flag and drum.
Here my mind seemed at times to be shut up.
The officers of the provincial received us very kindly, and with much respect.
One, who was a major, conducted us to the house of our friend,
the widow Barker of Tiverton, where we were kindly received.
We attended their first-day meeting,
and had renewed cause to acknowledge the Lord`'s kindness in this trying visit,
and in opening the hearts of many to receive us,
even amongst the soldiers and officers on both sides, and I may say,
"`It is the Lord`'s doing,
and it is marvelous in my eyes,`" to behold the goodness of our Heavenly Father.

On first-day, we were at Tiverton meeting, where came many officers and soldiers,
and through the goodness of our kind Master, we had a good meeting,
truth appeared to be over all,
and the Lord`'s name was magnified in the hearts of a remnant that day.
The officers and soldiers behaved very solidly, and we parted friendly.
My mind seemed to be led into a near sympathy with them, under their tried situation.

After this, we traveled as way opened, experiencing many close and trying seasons,
and at times had to acknowledge way was made for us, beyond what we could,
in our own strength, have had any right to expect.
But blessed and praised be His holy name, in that he never left his obedient servants,
but strengthened them to do his holy will.
We had many meetings, although passing through a wilderness country.
I trust they were to the encouragement of many seeking minds.
We were invited to the house of a justice of the peace, whose name was Remington Hobby;
he received us kindly, and we had two meetings at his house, one on first-day,
where were many of the town`'s people (this place is called Vassalborough,
on Kennebec river), and another in the evening at a Friend`'s house.
These meetings were much to my comfort,
feeling the overshadowing of our divine Master to be round about us.
We next proceeded up the river for two days, through great fatigue and suffering,
having to travel part of the way on foot to a Friend`'s house, who received us kindly,
there being no other Friends within forty-five miles.
Here we had a meeting amongst a poor people, newly settled,
but to our mutual satisfaction and comfort,
witnessing the divine presence to be underneath for our support.
Next day we left them and came down the river in a batteau;
Joseph Craggan accompanied us, and was very kind.
We crossed a river called Seversticook, and lodged with William Richardson,
and had two meetings, they manifesting their love by their kindness.
After meeting with many trials and difficulties in getting along,
we left the country westward, taking leave of many friendly people,
and reached Royals Town, and had a meeting amongst them,
wherein truth seemed to be over all.
From there to Falmouth, and then to Windham, where is a small meeting of Friends,
the families of which we visited.
From there back to the monthly meeting of Falmouth, and westward to Berwick, where,
with my dear companion Aaron Lancaster, we attended one meeting,
and feeling under an exercise to return back, I laid it before several weighty Friends.
They having unity therewith, I parted with my dear friends,
and joined in company with Elijah Jenkins, and a young man from Falmouth, John Winslow,
and visited several places, namely: Royals Town, Margyiony, New Meadows,
a place called the Reach;
the inhabitants of the last two places seem to be much dissatisfied with their priest,
and some convincement appeared amongst them.
From there we crossed Kennebec river, and went to Easton river, where we lodged,
and next morning crossed Kennebec river on the ice, and had a meeting at Swan Island.
Having been much shut up at times since being on this island,
(God opens and shuts as he pleases),
I experienced this day`'s service greatly to enlarge my heart,
by removing the cloud that has at times covered my mind,
and have cause to rejoice and bless Him who is my strength, my fortress, and my God;
praised be his name forever and ever.
I continued visiting many families of Friends and others,
attended the funeral of a Friend on first-day,
and trust I may say the Lord owned my service,
and enlarged my mind on different subjects, much to the satisfaction of many;
and I believe some have been reached so far as to
desire to turn to Christ Jesus their free teacher;
and I may say I have renewed cause to praise his worthy name; the meeting was very large,
solid, and quiet, to the honor of Him who is God over all,
blessed and praised be his worthy name.
We then had a select meeting with Friends, wherein my mind was much opened,
and the state of society closely spoken to, which was a great relief,
and a time of refreshment to the upright-hearted;
the power of truth appeared to cover the assembly in a remarkable manner.
Wonderful are the dealings of the Almighty,
who alone opens the hearts of mankind to receive the word of life;
many and various are his ways and dealings with his creature man,
to bring him to a sense of his duty.

10th month, 4th, attended a meeting, and visited several families until the 15th;
then parted with our friends, in great nearness of affection,
and took passage for Falmouth, where we arrived in about six hours;
had great peace of mind on this passage, feeling entirely clear of Nantucket,
after many meetings both among Friends and others.
I landed at Falmouth, and stayed one night, and proceeding to Martha`'s Vineyard,
had a meeting, and stayed with a kind friend, David Coffin; from there to Falmouth,
and attended their first-day meeting; and there to Boston, to their quarterly meeting,
and to Lynn and Salem.
I was much favored through the several sittings of these meetings, which were large,
and truth seemed to be over all; God be blessed forevermore.
We lodged at Jeremiah Hacker`'s while in Salem, who was very kind, and, with his children,
was made near to us in the best sense.
From this place we returned back, and had meetings at Boston, Lynn, and Pembroke,
the last a quarterly meeting; after which we took several meetings on our return,
as Centre Cushinet, Long Plane, Rochester, Sandwich, and Yarmouth.
To the last came many of the town`'s people, who were very civil, and we were favored,
through the Lord`'s goodness, to open the way to rest and peace through Jesus Christ.

10th month 20th, 1777, we left Boston and came to Salem,
and lodged with our friend Jeremiah Hacker, who, with his family, received us kindly.
We have traveled in this journey more than three
hundred miles since we last left this place.
Praised be the Lord, who has been near to us, both on the right hand and on the left,
and carried us through the many besetments we have had
to experience both inwardly and outwardly.
22nd. We traveled eastward: reached Hampton, and lodged with Tristram Collins;
here we met with kind friends.
23rd. To Berwick, about eight miles; from there to Falmouth,
and attended their monthly meeting; there to a new settlement of Friends,
called Royal Borough, and had a meeting to good satisfaction.
30th. Set forward to a place called Boarding, on the Kennebec river,
and had a meeting at the house of a friendly man, where came many of the inhabitants.
We were favored with a solid meeting.
The people appeared kind,
and I trust it was a comfortable opportunity to many exercised minds,
and cause of thankfulness in us,
thus to experience the continued care of our dear Lord and Master,
in whose cause we are made thankful to be worthy to serve.
Here we tarried two days, and some friendly people came and sat with us.

11th month 2nd, left Swan Island, and went up the river to the house of Gideon Gardner,
and had a meetings, where came most of the inhabitants around.
I had cause to acknowledge the merciful dealings of our Heavenly Father,
who was pleased to look in mercy upon us,
favoring with his life-giving presence and renewings of strength.
The next day we proceeded up the river, (the country and roads being hardly passable),
we reached the house of Christian Pinkham, a friendly man, who,
with his wife and children, received us kindly.
We had a meeting at his house to our comfort: from there to a settlement,
called Jones`' Plantation, where were some friendly people.
Our meeting was to good satisfaction;
they appeared to be in a humble disposition of mind,
being much alone in a wild new country.

I had many trials as I traveled through the wilderness,
in many parts there being little or no road; but I believe Friends here,
if they keep their places, will increase.
Stayed two days, being unwell, at a house where the wife is a Friend,
but not the husband, though both were very kind and tender of us,
and provided sundry necessaries to take with us for our future use.
We left Swan Island on the ice, and were the first that had passed with horses,
and had a meeting in the evening at Gardner Town, and lodged with Reuben Goben,
whose kind reception was grateful to us.
Here we had a meeting, many attended, and the opportunity was much to satisfaction.
Feeling my mind engaged to proceed, I went up the river,
and found people much rejoiced at my return.
Having reached the place I felt concerned to visit, we appointed a meeting,
but from the great depth of snow, and cold, few attended.
We stayed two days with our kind friend, Jethro Gardner, until first-day,
and had a satisfactory meeting, I trust to our friends also,
as much kindness was expressed.
The next day, went down the river,
feeling our minds drawn to visit sundry families on our way,
in which we had good satisfaction, and great tenderness appeared in many countenances.
The people are poor, and far from any place of worship,
there not being a meeting-house for near sixty miles.
We had many meetings as we came back, much to our comfort and refreshment,
and many appeared to be convinced of the truth, whom we parted with in great tenderness.
Being much fatigued by hard traveling,
we rested several days in a town called Vassalborough.
The inhabitants are generally friendly, though much strangers to our society.
We stayed with a friendly man before mentioned, Remington Hobby,
who gave up his house for meetings,
and desired to entertain us as long as we chose to stay.
We lodged at many of their houses, who did the best they were capable of for our comfort,
having had many tender seasons with them.
We parted, under a sense of God`'s goodness in sending us among them,
but finding myself impressed to go back, I gave up to it,
and having delayed the time so long, was obliged to ride against a hard snow-storm,
but was enabled to reach in time enough to hold a meeting; and,
through the goodness of God, we were much favored,
and the name of the Lord was exalted that day.

My concern, in being thus led so singularly where no Friends dwelt,
yet finding no release without returning back, was a great exercise to me,
being almost at times ready to conclude that I was wrong,
but felt satisfied that my kind Master would never fail,
though at times great trials of faith are the lot of his children,
although they may be truly devoted to His service.
Oh, I may say, many were the heart-achings I had to pass through in that wilderness land,
but the Lord supported me under my many exercises, and preserved me,
though many times I was almost in despair,
having had to pass through good report and evil report;
there being those who rose up to oppose and withstand the truth,
but through the power of the Most High they were made willing to acknowledge their error,
and I believe were truly sorrowful.

Elijah Jenkins and Samuel Jones, my companions, here left me,
and I am now accompanied by a young man, whose name is John Winslow.
In one of these meetings, he appeared in a public testimony, much to my comfort,
and to him my heart feels nearly united.
Having had several meetings to satisfaction,
and finding my mind drawn up the same river again, we set off,
but giving way to doubts and fears, I got discouraged, and turned back,
and made my way westward, but in great trouble; sometimes thinking to go back,
at other times ready to think I had stayed too long already.
From the various reports I expected to be imprisoned, as many had threatened it.
I made several stops at different places, to converse with the most leading men,
and had several meetings in my journey, to good satisfaction;
and we got to Falmouth and attended a funeral,
where came some that intended ill against me,
but afterwards they went away well reconciled.
Next day being first-day,
there came more persons in order to examine and form some judgment,
whether it was best to stop me or not, but I understood they went away satisfied.
Thus, having favorable opportunity, through the Lord`'s goodness,
truth was exalted over all.
From there we went to Goram Town, where I was again examined,
but nothing appearing against me, I appointed a meeting at the house of a friendly man,
who was very kind, and entertained us.
There appeared to be a tender people here, and they were much reached,
the Lord`'s power being manifested in the said meeting, to our mutual comfort.
From there we set off for Berwick, where I met many near friends; from there to Kethera,
and lodged with James Neal, a valuable minister.
So to Dover, where I met with my dear companion Aaron Lancaster,
after a separation of ten weeks.
We had to rejoice in the Lord`'s goodness in preserving us through many close trials,
in which our souls had to praise his mercies.
At this monthly meeting were Friends from different parts,
in which we were favored with the renewals of the Father`'s love, much to the refreshment,
I believe, of the living seed.
The business of the meeting was conducted in a
good degree of brotherly love and condescension.
From there we went back to Berwick, and to a place called Philip`'s Town,
where there had not been a Friends`' meeting before; then to Dover again,
where I had an attack of illness, so that my life was almost despaired of,
but through mercy I soon recovered.
After parting with many near Friends we went to Rochester,
and there to a meeting at Meadsborough; there back to Rochester: we stayed two days,
and had meetings to our mutual satisfaction and the refreshing of many minds,
through the extending of the Father`'s love.
Here appeared to be many inquiring people, and some in a tender state of mind;
there we proceeded to Hail`'s Town, a newly settled place,
where were many who had been convinced since Friends
settled there and who appeared very solid and steadfast.
From there to Hopkin Town, where we had a meeting,
and many attended not of our profession, who appeared well satisfied, except one person,
who seemed to cavil at something that had been said;
I having been led to speak from the words of the prophet wherein he
signified a dissolution of the old heaven and old earth,
and a new heaven and a new earth being created, wherein dwells righteousness;
and being led to express the necessity of this being experienced here in time,
through the melting power of truth on the soul,
which is compared to the refiner`'s fire that separates the dross from the tin,
and takes away the reprobate silver.
This was a matter that had caused great disputes amongst them,
though it was altogether unknown to me from any outward information.

We next went to a place called Pembroke,
where lived a person lately convinced and received amongst Friends.
At this town there had never been a Friends`' meeting; many came in,
and gave solid attention, and the Lord was pleased to favor us with his helping hand,
by which we were enabled to declare the way to the kingdom of God through Christ Jesus,
who is the alone way, the truth, and the life;
by whom many that were heathens came to be renowned Christians,
through attention to Christ the light, that enlightens the children of men;
and leads them that attend to his voice, out of darkness into his marvelous light.
The people appeared tender and well satisfied,
and we parted under a sense of God`'s goodness and love;
many of them signifying their satisfaction and their desires for our preservation.
We now set off for our friend Joshua Falsom`'s, which was forty-four miles distant,
which much exhausted my strength, arriving late at night.
The next day we reached our worthy friend Tristram Collins,
whose wife had traveled much in the work of the ministry.
Next day attended the monthly meeting of Hampton, held at Ambury,
and returned back to T. Collins`'s again.

Here my companion and I had a fresh trial, he finding his mind drawn towards Salem,
and I felt drawings back to Dover monthly meeting.
We parted with hearts filled with love and desires for each
other`'s preservation in the work the Lord might engage us in.
I, in company with several young Friends, rode that day to Dover,
and put up at Hope Scammon`'s, whose kindness towards me was very comfortable.
Many more seemed glad to see us.
After this monthly meeting, which we attended,
I felt a concern on my mind to join a committee to visit delinquent members,
and examine who were proper to be retained, as many had married out,
and there had been a neglect on this account,
their cases not having been attended to agreeably to the order of society,
which service was very exercising to me;
but through the merciful goodness of the Great Master, we were much favored,
as far as I proceeded with them, and the Lord owned both us and the service we were in,
blessed be his most worthy name.
From there I proceeded to Hampton, in company with a number of Friends,
and attended their monthly meeting, with most of their particular meetings,
to a good degree of satisfaction; there appeared to be a living remnant amongst them.
Here I parted with many dear and tender Friends,
in whom I had often experienced much comfort,
having been nearly united in the best sense.
From there we proceeded in company with Jonathan Dame,
and were kindly received by my dear friends of Salem,
(having been long absent from them in the Eastern
States) and attended their first-day meeting,
and met with my dear friend Aaron Lancaster,
who had been engaged visiting the families of
Friends belonging to the said monthly meeting.
Feeling my mind drawn towards this service, I joined my friend,
and had much satisfaction therein; this being accomplished, we took our leave,
after again visiting Boston, it being the third time.
I thought the people appeared in the most humble disposition of mind I had seen them,
and they were very kind towards us; many came to our lodging to sit with us,
and appeared very solid.

From there we went back to Lynn and to Bolton,
in which meetings I was favored to open some things to the comfort of the honest-hearted,
and to my own confirmation.
I had to remember that the secrets of the Lord are with them who fear him; he opens,
and none can shut from his all-seeing eye: as he sees fit,
he discovers his secrets to them that wait on him.
After our service was accomplished here, we passed to a place called Leicester,
where came several people not of our Society,
and we were favored with the renewings of ancient strength,
and the Lord`'s power was over all, and the witness in many hearts seemed to be reached,
through the gathering hand of the Lord.
Here we rested a day, and visited some families, wherein I had good service,
and then proceeded on our way to Northbridge,
where we were favored to clear our minds to our mutual comfort,
the Lord`'s power being in dominion.
From there to Uxbridge, Mendom, Winsocket, and Smithfield old meetinghouse,
in all which we found close labor, but had peace therein to our own souls;
and a concern having attended our minds for some days,
to return back to Salem quarterly meeting, which we were made willing to undertake.
We met many of our near and dear friends from the eastward,
whose company and conversation was strengthening to me,
having had to pass through close and trying seasons,
wherein I felt the humbling power of truth to lay the man`'s part as in the dust;
but blessed be Jacob`'s God and Israel`'s preserver and deliverer,
who raised me as from the earth, and put a new song into my mouth,
even praise forevermore; and he owned us with his ancient love,
through the several sittings of this quarterly meeting,
and also two meetings held at Lynn,
where the Lord appeared to the comfort of a living remnant,
many of whom appeared concerned for the prosperity of Zion.
Having at times had a drawing on my mind to return eastward, since I left those parts,
which now returned with a pressing concern,
but which was very proving to me to have to give up to,
having had so many trying seasons in the eastern country, and spent much time there;
also, the consideration of having been long from home, added to my exercise,
though I have been enabled to submit all to His
protecting hand who required this service of me.
I parted with many of my kind friends at Salem,
and proceeded in company with my dear friends Mehetabel Jenkins and Hope Scammon,
(widow). We had two meetings at Amsberry, where came many people not of our profession,
and we had a comfortable time, much to my satisfaction,
and to the comfort of the faithful.
The following letter to his wife, dated from Salem,
affords living evidence of his faith and patience,
and of the many trials he was called to endure about this period:

[.salutation]
My dear Wife and bosom Friend--

It is long since I have had an opportunity of writing to you,
though I have been favored to receive comfortable accounts from you,
which have been truly consoling in my retired walks and lonely moments,
when you and my dear children are brought feelingly to my remembrance,
and a renewed confidence in the Divine promise--I will be a father to the fatherless,
and a husband to the widow.
I am sensible at times that you are one that almost lays claim to that appellation.
I am not prepared at present to give you a particular account of my travels;
but may inform you,
that I have spent part of the fall and most of
the winter among a people not of our profession,
many of whom received me very kindly, and my testimony also,
which made them feel near to me, and their hearts and houses are open to receive Friends.
I have an untrodden path to tread,
where no Friends have before traveled in the work of the ministry.
I have passed through many towns where there are no religious meetings of any sort,
and as the Lord has led me through this wilderness land,
he has preserved me through the cold, and in sickness and health,
and through every trial, of which I have had many;
at times doubting whether I should ever return to my
native country and other dearest enjoyments;
but I have been enabled to submit all to the Lord`'s disposal, who gave me a being,
and has blessed me with so many marks of his kindness and tender regard, in whom,
your confidence, I hope, will not fail.
If there is but a steady eye kept to the hope of reward which
is promised to the faithful who hold out to the end,
which I feel a confident hope may be the happy experience of you, my beloved companion,
with myself,
and that we may in the Lord`'s right time be permitted to meet where we can
mutually unite in rendering thanksgiving and praise to His holy name,
who is blessed forevermore.
In that love which time or distance cannot change, I most affectionately salute you,
with my beloved parents and friends,
to whom I feel most sincerely united in the bonds of pure love.

[.signed-section-closing]
Your affectionate husband,

[.signed-section-signature]
David Sands

The journal thus proceeds:--At Amsberry, there seems to be a tender, seeking people.
From there we proceeded to Dover, Berwick, Falmouth, and Royalstown,
in which we had many satisfactory meetings; from there to a place called Small Point,
where had formerly been a settlement of Friends,
who had frequently been visited by travelers, but not keeping faithful, all wasted away,
except one family, who received us kindly,
not having been visited for twenty years by a Friend.
From there back to George Town, where we had a meeting, also to Long Reach,
where we had another; these were favored meetings, and truth reigned.
From there to Vassalborough, and had two meetings in our way,
and through the extendings of best wisdom we have been preserved through all,
to the praise of His worthy name.
From there to Jethro Gardner`'s, which we reached with much difficulty,
having been lost in the woods, and had little hope of getting through;
but considering the mountains, hills,
and woods are all the workmanship of Him in whom I trust, my mind was easy.
We were favored to reach our friends, who gladly received us,
and we had one meeting to good satisfaction, here being some convincement.
We had two meetings on our return to Vassalborough,
one amongst a thinly scattered people, also to satisfaction;
and one in a town called Winslow.

After having spent some time in and about Vassalborough, and had many meetings,
wherein the Lord owned his own work, to our mutual comfort and edification,
we parted with many near and dear friends,
under a sense of the goodness of Him that had brought us together.
From there we went to a new settlement, called Winthrop, where we had several meetings.
Here were several convincements, and many that appeared to be seeking the right way;
there back to Holland, where we had a meeting much to our comfort,
the Lord`'s power being over all, and many hearts tendered thereby.
We parted with these tender people in great brokenness of heart,
under a sense of God`'s goodness to us all; from there to Gardner Town,
where we had a meeting; and from there to our kind friend, Gideon Gardners,
who received us with much kindness.

After this meeting, a concern came on me to return back again to Vassalborough,
but by reasoning and consulting with flesh and blood, I became weak and did not give up,
which, as I traveled along, was very painful to me at times; but He who knows my heart,
and that my desires were to serve Him according to my understanding,
after reproving me for my disobedience,
was pleased to lift up the light of his countenance upon me and heal my soul,
and may I ever adore His goodness, and remember the rod, and Him who has appointed it.
We then proceeded to the yearly meeting,
attending meetings in our way between Falmouth and Berwick, mostly to satisfaction.
Next day had a parting meeting with our friends at Berwick,
wherein we were favored to witness the Lord`'s presence to be felt amongst us,
this being the last meeting we had in that country,
except the yearly meeting at Smithfield, for New England, which,
through the sittings thereof, was experienced to be a time of favor,
wherein the Lord`'s wonderful power covered the assemblies of His people.
After this meeting I proceeded homeward, and was favored to meet, in health,
my dear wife, children, parents, and friends in 12th month, 1779,
after a separation of two years and seven months,
and we were filled with grateful acknowledgments to the
Great Preserver of His truly dependent children,
who had been experienced as a present help in every needful time.
