== Chapter 3

[.chapter-synopsis]
* Letters to his Wife
* Letter from Miriam Fry to David Sands
* Convincement of Remington Hobby
* Letter to Daniel Starbuck
* Epistle to Friends of East Hampton
* Trials of his Wife from the Army
* Letter to his Wife--His return Home

The following letters, addressed to his wife in the course of this long journey,
will be read with interest:

[.embedded-content-document.letter]
--

[.salutation]
Most affectionate and truly beloved wife--

The time seems to have come in which we must
necessarily consider ourselves as not our own,
nor as having a right to do as would be most agreeable to our natural will,
as in the time of more ignorance, at which the Lord has been pleased to wink.
But now we must remember we have been "`bought with a price,
that henceforth we should not live unto ourselves, but unto Him who died for us,
and gave himself a ransom for all,`" which we cannot experience but
through the death of self and selfish motions of the mind,
which, if given way to, will produce sorrow and cause dimness.
I am sensible that we have our trials,
and our faith is frequently assaulted by the adversaries of truth,
and enemies of pure righteousness, and these are frequently of our own house.
I believe it is safe to watch the motions of our own minds,
lest when under trials we should fall into poor Israel`'s condition,
and murmur against the Lord,
by which we should render ourselves unworthy of an inheritance in the good land.
We may remember some who "`came out with a strong hand,
and an outstretched arm,`" and had been baptized unto Moses in the cloud and in the sea,
(which I take to be a baptism of tears, under some very painful conflicts of mind),
who were wonderfully carried through,
so as to sing his praise on the banks of deliverance; and yet,
by letting in discouragements,
and a disposition of mind contrary to the pure will of the Lord,
they fell in the wilderness.
The Apostle explains it to be through unbelief.
However great our trials may be, as they are, and have been many since our acquaintance;
yet my cries and prayers are, that we may not fall after the same example,
nor fall short of that rest which will be the sure
reward of the righteous who hold out unto the end;
and although our trials may be many,
yet blessed be the Lord) who has hitherto been as a
"`great rock in a weary land,`" that we may boldly say,
"`the Lord has been our helper,`" and by Him we
have been enabled to "`run through a troop,
and leap over a wall;`" and seeing, my dear companion,
that through all our trials "`his hand is not shortened,
nor his ear grown heavy,`" let us still confide in Him, follow our great Captain,
and be of good cheer, for as he was so should we be, grave in conversation,
sound in judgment, and constant in persevering, meeting afflictions cheerfully,
especially when they come from Him who is everywhere present.
We may remember what our Lord signified, "`The cup which my Father has given me to drink,
shall I not drink it?`" And if this was a situation fit for a son,
how much more so for the servants,
and especially for those who have been and are but unprofitable ones!
We are apt at times to grow impatient, and tired of the school of affliction,
which frequently is a greater blessing than the increase of temporal things.
All the righteous nation, who keep the law, enter in with the Bridegroom,
to hold the repast which tongue cannot set forth,
being in the full fruition of never-ending joy, when tears will disappear; and oh,
my dear! though I am absent in body, I am often led to sympathize with you,
under your present exercises, which doubtless are numerous and painful, but I am,
and have been, through mercy,
renewedly supported with a firm and unshaken belief that the Lord,
whom I desire to serve with all my heart, will support and keep us,
and our tender offspring, by his almighty power,
if we do not forsake or turn aside from following after him.
As touching my return home, it seems at present to be hid from me.
Friends have received me very kindly, and I have had many tendering seasons among them.
I think they are gaining ground in this island.
The Lord has a tender people here, to whom my heart is often united.
As to particulars, I cannot say much, hoping in some short time to speak face to face.
And in the mean time I recommend you, my beloved wife, and my tender children,
to the guidance of his good Spirit, who will lead us safely,
and no doubt will land us all joyfully in the celestial regions when
a few troublesome and afflicting days and nights have passed away:
so in true love and tender affection I bid you farewell.

[.signed-section-signature]
David Sands

[.signed-section-context-close]
Nantucket, 3rd of 9th month 1779.

--

[.embedded-content-document.letter]
--

[.salutation]
My dear and beloved Wife,

Notwithstanding my long and unforeseen stay, which is at times very proving to me,
I am from time to time in expectation that my service will be accomplished soon,
and that I shall return home with true peace and satisfaction,
which I hope earnestly to seek,
and which I have found to be the certain consequence of true obedience.
I have no doubt our present separation is in wisdom, unerring wisdom,
and I am supported in the belief, that however painful it may be, yet,
if rightly improved, it may afford us some instruction that cannot be had any other way,
which I hope will tend to our purification,
and fit us for those services that the Lord may intend for us,
and in the promotion of whose cause I hope we may daily be engaged,
as I am fully persuaded if He is but sought unto he will never leave nor forsake us;
and though with many other brethren and sisters that are gone before,
we may have had to sow in tears, yet let us be encouraged,
for we shall assuredly reap in unspeakable joy.
I feel, while I am writing, my heart filled with a husband`'s affection,
and a father`'s love, to you and my dearly beloved children,
whom I have committed to the care and protection of Him
that commands all things both in heaven and in earth,
and I cannot doubt but that his watchful providence will protect both you and me,
and all those who put their trust in him, bring us finally to a happy conclusion,
and grant us an entrance into the mansions of everlasting rest.
I have visited all the families of Friends in this island, and some friendly people,
much to my satisfaction; in which the Lord`'s power and presence was experienced,
to the comfort of the honest inquirer, and the convincement, I trust, of the unconcerned.
I mention this for your encouragement,
and to let you know that the Lord is still willing to own his own work.
With love unfeigned I remain your affectionate husband,

[.signed-section-signature]
David Sands

[.signed-section-context-close]
Nantucket, 8th month, 16th, 1779.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Miriam Fry to David Sands

[.salutation]
Dear Friend,

In the everlasting love of God,
wherein New Jerusalem`'s children have their true consolation,
do I very dearly salute you with your dear companion Aaron Lancaster,
with earnest desires that I may ever remember the sweet counsel that flowed from you,
being strengthened, I believe, and borne up by the arm of unerring Wisdom;
which was as a heavenly visitation to my soul, a poor unworthy creature,
who am ready to think myself unworthy of the least of the Lord`'s mercies.
By letting in discouragement,
and giving way to the temptations of the enemy of all righteousness,
I have been as one straying from the Father`'s fold.
And it is the earnest desire of my soul that I may double my diligence,
in the pursuit after the heavenly and durable treasure, which will stand us in stead,
when time to us here in this world shall be at an end.
I think that I have great cause, in the depth of humiliation,
to magnify and to adore the great and glorious name of him that lives forever and ever.
Who is everlastingly worthy, worthy, worthy, of all glory, of all honor, of all might,
majesty, and dominion, both now, henceforth, and forevermore.

My desire is that you may be conducted home in the Lord`'s own time,
to your wives and children, with sheaves of peace in your bosoms, having been enabled,
I believe, to administer comfort to the afflicted by the divine power of God,
encouragement to the feebleminded, and instruction to the ignorant,
and those that are out of the way, being filled as clouds with heavenly rain,
distilling it upon the flock and family of the faithful,
and as dew upon the tender grass, yet being as a fire to the rebellious,
but refreshing as the dew of Hermon to the honest traveler.

Oh, may the great Lord of the harvest grant that I may be enabled to follow you,
as you follow Christ, in the way of regeneration, and of self-denial,
and that I with you and you with me,
may be preserved in the meek spirit of the Lamb of God, the Prince of Peace,
of whose peace and government there shall never be an end,
is the sincere desire of my soul.
So in near and dear love, I conclude, and bid you farewell,
and remain your friend and sister in the unchangeable covenant of light and life.
My husband joins in near and affectionate love to you and your companion.

[.signed-section-signature]
Miriam Fry

[.signed-section-context-close]
Nantucket, 4th month, 24th, 1778.

--

[.blurb]
=== Some Account of the Convincement of Remington Hobby

In the year 1777 or 1778, when David Sands was on a religious visit to New England,
the eastern part of which was almost a wilderness, with but few inhabitants,
and they generally of the poorer class,
(at least their appearance and accommodations indicated it),
after having had several appointed meetings in the neighborhood,
a man who was a magistrate in the place,
and more comfortably situated than many of his neighbors) said to his wife,
"`I hear these Quakers are decent, respectable-looking men:
I believe I shall invite them to my house,
as they must be but poorly accommodated where they are.`"
She readily agreed to the proposal, and a messenger was dispatched for them,
and they were pleased to accept his kind invitation;
when they came they were shown into the common room or kitchen, after being seated,
they remained in perfect silence.
The man being entirely unacquainted with the manners or principles of Friends,
was at a loss to account for their remarkable conduct, and attributed it to displeasure,
on account of their being invited into their kitchen.
He immediately ordered a fire to be made in another room, for, said he to his wife,
"`I believe these Quakers are not pleased with their reception;
we will see how they like the other room.`"
He invited them in, and after having seated themselves, the same solemn silence ensued,
at which he became almost vexed, and thought to himself, they certainly are fools,
or take me to be one, and regretted having taken so much trouble on their account.
As these thoughts were passing in his mind, David Sands turned,
and fixed his eye full in his face, and in the most solemn manner said,
"`Are you willing to be a fool,`" when he paused, and again repeated,
"`Are you willing to become a fool for Christ`'s sake?`" he continued with such power,
(as the man afterwards expressed), that he could not withstand it,
and in a short time became fully convinced of Friends principles,
and most warmly attached to David Sands from
feelings of sincere gratitude and brotherly love.
His house was open at all times to them to hold their meetings in,
and he kindly offered to attend them,
while they were visiting families and meetings throughout the neighborhood,
fully acknowledging the power of truth, as he had heard it set forth,
and soon after became a member of the Society of Friends,
very zealous in the cause of righteousness, and a faithful laborer in the ministry,
traveling much in the work, so that, as he once observed,
his house had become to him as an Inn, where he could tarry but a short time at once.
When David Sands paid his last visit to New England,
previous to his departure for Europe,
R+++.+++ H. became his faithful and well-beloved friend and companion,
in his various exercises, and parted with him with feelings of the truest regard,
commending him to the care of Him who ever watches over his faithful children,
whether by sea or land.

The following letter by David Sands,
evincing his tender concern for the growth and
establishment of those among whom he had labored,
is thought to have been written while engaged in this last journey.
It is without date:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend, Daniel Starbuck,

Notwithstanding our correspondence has not been regularly kept up,
yet I may assure you my love is in no way lessened either by time or distance.
I have at times brought into view the many trying seasons we passed through together,
in traveling the untrodden paths of the wilderness to
declare the glad tidings of the Gospel,
through Jesus Christ our holy Redeemer, to many of the unconverted,
who are forgetful of their duty to their merciful and gracious Creator,
"`who wills not the death of him that dies, but that all should return, repent,
and live.`"
I have, with you, to adore that arm that bore us up,
and so marvelously supported us under every exercise, both as to body and mind;
and hope this may be an encouragement to us in our future stepping along,
to yield our minds to every service that may be appointed to us,
nothing doubting but that He who has already
begun the work will carry it on in us and by us,
if we humbly confide in him, resigning our own will to his blessed will,
not looking so much at the appearance of things, and at our own abilities,
as to the all-sufficiency of His power who can fit the
least in the family for every good word and work,
and enable them to show forth the praises of Him
who has called them both to glory and virtue.

And, dear friend, as you were made a comfort, and a near companion to me,
I have often been desirous that you might be so
preserved as to become useful in the family,
and shine among the fixed stars in the firmament of the Lord`'s power, which,
I doubt not, will be the case if you hold fast the beginning of your confidence,
and keep in the humility of the heavenly family,
where nothing impure can find acceptance,
but where joy unspeakable and full of glory is the enjoyment of the blessed;
the redeemed of all generations, who unite in praising his holy name forever and ever.
With a heart filled with the love of an affectionate brother in Christ,
I remain your friend,

[.signed-section-signature]
David Sands

--

Among the papers of David Sands was found the following weighty address,
which appears to have been written about this period,
and is deemed well worthy of preservation:

[.embedded-content-document.epistle]
--

[.blurb]
=== To all who love the Lord Jesus Christ, addressed more especially to Friends of East Hampton,

[.salutation]
My dear Friends--

I have had my mind often drawn to remember you,
since my lot has been cast in this island,
feeling something to say to encourage you who have known in measure
the purifying power of divine love shed abroad in your hearts,
which is able to keep and preserve you in the hour of temptation,
and make you as hewn stones that will lay solid in the spiritual building.
As you abide in it,
you will be led from all likenesses of things that are in heaven above,
or in the earth beneath; seeing the end of all types and shadows,
and looking to the eternal substance,
to Jesus the living bread which comes down from heaven;
whereby you will be enabled to keep the spiritual passover,
where you will drink the wine of the kingdom, well refined,
and eat of the spiritual bread which our Lord breaks
and blesses to his poor dependent children,
whom he chooses as in the furnace of affliction,
where he baptizes them with the baptism of sufferings,
and thoroughly purges the floor of their hearts, and burns up all the loose matter.
Therefore, my dear friends, dwell in this principle of divine love,
which casts out all slavish fear;
for as you are found dwelling therein it will be your strength,
whereby you will be enabled to wage war in
righteousness against the man of sin in yourselves,
and to destroy the works of Satan through the power of God,
who is himself an immense ocean of divine love,
which I apprehend some among you have been made sensible of.
Therefore, my friends, dwell in that power and wisdom which is from above,
and in the life and virtue of Jesus Christ,
and this will keep you alive in Him who is the root of life;
it is this that will make you fruitful; not formal, dry, and barren;
having the form but lacking the power.
Get, friends, to the inward sanctuary, and wait, like David formerly,
who often waited upon God; so will you witness him to be strength in weakness,
riches in poverty, and a never-failing helper in the most trying seasons.
May it be your engagement to come out of all mixtures,
into God`'s peaceable truths out of all the imaginary conceptions of man`'s wisdom,
into God`'s wisdom, into his Spirit,
that so you may drink of the river that makes truly glad.
It is a small thing to be called a Christian, but to be a true follower of Jesus,
to love him above all, to deny ourselves, and to take up our daily cross and follow him,
is a labor which is not agreeable to the creature:
or that self should have no reputation, nor any share,
especially in religious performances.
The nature of man is activity, which, in these, ought to be laid in the dust;
for that which comes from God, gathers to Him;
and that which comes only from the will of the creature, and wisdom of man,
though clothed with the richest garments of man`'s contriving and preparing,
can bring no life, nor the savor of it to the soul.
I may say you have been made near to me,
and should I be engaged to pay you another visit in Gospel love,
may I be comforted in beholding your growth and firm establishment in the eternal truth.
I believe that God will reveal himself more clearly to some of you,
through the light of his dear Son.
Oh! that you may take heed to the tender touches of His love,
and keep to that in yourselves which convinces you of evil,
and though it be small in its appearance, it will enable those who take heed thereto,
to overcome evil, and lead from it into truth and peace.
And as I have, when among you, exhorted to these things, so I now again write to you,
to keep out of all noises, tumults, and confusions, that are in the world,
and are of the world, which lies in wickedness, and be still.
Seek for the true quietude of mind;
the place of true menial prayer is a quiet habitation,
and O that many of you may be gathered to it, both parents and children;
then you will be enabled to offer acceptable prayers to our Father which is in heaven,
who hears the prayers that proceed from the contrite spirit.
With a salutation of love to you all, I remain your sincere friend,
in Jesus our dying and risen Lord,

[.signed-section-signature]
David Sands

[.signed-section-context-close]
It is desired that this epistle be read at the close of an evening meeting,
by the Friends of East Hampton.

--

The foregoing journey, through some of the Eastern States,
being at a period when the revolutionary war was at its height,
he had many trials to pass through, in moving about among the armed forces.
Of these trials his wife and family at home had largely to partake.
His house stood in a neighborhood where many of the troops were collected,
and at one time there was a guard of fifty men stationed at his house.
At first they appeared rather hostile, but soon changed their conduct,
as they became acquainted with his wife and family,
and were satisfied that he was absent on a religious visit,
though it appeared strange to them that he could
leave a comfortable home in such perilous times;
from this circumstance they were at first almost
induced to believe that he had gone to the enemy.
One day, when several soldiers were present, his wife received the following letter,
which, after having read, she handed to one of them,
desiring him to take it to the camp and show it to their officers,
that they might be satisfied of its contents:--

[.embedded-content-document.letter]
--

[.salutation]
My beloved Companion--

The tender ties, both of grace and nature,
call on me to embrace every opportunity of writing to you.
After a salutation of tender love,
these may inform you that I have today finished my service in
this island in visiting nearly two hundred families,
which service I have been favored to perform beyond my expectation,
through the helping hand of Divine Goodness.
My mind has been much with my tender and beloved family,
and at times the flood of affliction has;
run so high that I have been almost overwhelmed; though at this time I feel,
in some measure, relieved from it,
and hope to be resigned to the Divine Disposer of all things, who, I me say,
has hitherto helped me.

I expect, in a day or two, to leave this island, and proceed,
unless I find my mind released from further service, which seems to be my daily desire.
I am comforted at times,
under a confirming belief that He who requires the
service of me is a merciful covenant-keeping God,
in whose arm of power I trust,
and that he will preserve me and mine under the shadow of his wing,
if we are but faithful to him; and that we may be so is the fervent breathing of my mind.
I expect that you, perhaps, have met with close trials,
and had great exercises to pass through; and though I am separated from you,
my earnest desire and prayer is, that your faith fail not,
and I am persuaded that Jacob`'s God and Israel`'s King will not forsake us;
though more trials may be near, yet as our eye is single to him, we shall be preserved.
I hope you will not be dismayed or cast down, but trust in the Shepherd of Israel;
cast your care upon him, for he cares for those who trust in him.
I have been favored to believe that he will be a father to my beloved infant children,
and as a husband to you, seeing he has ordered our separation in this trying season.
My love is to my beloved parents, brothers, and sisters, and dear inquiring friends.
In the most affectionate and heartfelt regard, I am your loving husband,

[.signed-section-signature]
David Sands

[.signed-section-context-close]
Nantucket

--

It is stated that some of the soldiers often
came in and sat with them during their meetings,
and appeared very civil and respectful.
Clementina Sands lent them several Friends`' books, particularly Barclay`'s Apology.
When they left, they took a friendly leave,
and appeared to wish for the welfare of the family.
During their stay, her friends felt very anxious for her removal to a place of safety,
but she felt most easy to remain, though much exercised,
desiring to be shown what was best for her; and, on one occasion,
she retired to wait in silence to be guided by
Him who is alone able to direct in best wisdom.
She felt drawn to open the Bible, and her eye rested on the 27th Psalm:
"`The Lord is my light and my salvation, whom shall I fear:
The Lord is the strength of my life,
of whom shall I be afraid?`" which was so fully
applicable to her present trying situation,
and also the promise of care so beautifully expressed, that her mind became quieted,
and all fear and anxiety were at an end.
She felt full confidence in Him who had sent her
protector away from her on an errand of gospel love,
for the benefit of his fellow creatures,
believing that He would extend a fatherly care to her and her little ones.

After his return in the winter, 1779 and 1780,
he remained at home until the following summer,
when he felt a concern to visit Friends in Philadelphia, particularly in their families,
which service engaged him until the 2nd month, 1781.
He was much comforted with the openness manifested to receive the truth;
and though it was an arduous labor,
yet he was favored to return with peace and
thankfulness to Him who had required it of him.
The following is from his Journal:
