== Chapter 4

[.chapter-synopsis]
* Visit to Philadelphia
* Letter to his Wife
* Robbery of his Store
* Second Visit to New England
* Letter from John Pemberton

In the year 1780,
I felt my mind drawn to visit Friends in Philadelphia and parts adjacent.
I spread my concern before the monthly meeting to which I belonged,
and obtained a certificate expressive of the unity of my friends,
and encouragement to proceed to perform the service required of me as way might open.
I left home about the 8th month 1st. On arriving at Philadelphia,
my friends received me kindly, uniting in my anticipated service and labor.
I visited all the families of Friends,
and was kindly accompanied by some of them through this extensive service,
in which much exercise and close labor was found to be in the way of my duty.
I felt a comfort in believing that it was owned by my great and good Master.
I attended many meetings, both for worship and discipline,
to the relief and comfort of my own mind, and, I trust,
to the general satisfaction of concerned Friends,
whose sympathy and exercise for my welfare I was fully sensible of.
I had many meetings, and much labor amongst those of other societies,
much to my satisfaction.
I also attended many meetings, both for worship and discipline,
amongst Friends of the adjacent parts.
In a letter to his wife he thus expresses his lively
concern for her preservation under her many trials,
and for the welfare of his own family:

[.signed-section-context-open]
Philadelphia, 8th month 20th, 1780.

[.salutation]
My dearly beloved Wife--

Duty, as well as inclination, invite me to embrace this opportunity to write to you.
Though absent in body, few hours pass without remembering you and my beloved children.
But I still feel a reviving hope that you are mercifully cared
for by Him whose care is for His dependent children.
A sense of His all-sufficient help still remains as an anchor
to our minds under every dispensation of His providence.
I have with much clearness seen, in the visions of light,
that it is according to the saying of the prophet,
"`It is the Lord that teaches to profit,
and leads in the way that we should go;`" and though in the cross to our own wills,
yet I believe there is no other way to the crown; therefore, as far as we may be enabled,
let us resign the government of our wills to Him
who is the great counsellor of His people,
who leads in a way the fowls of the air do not know, and the vulture's eye has not seen,
and who sustains the character of an everlasting Father to
provide for and support his children that cry unto Him,
and a mighty God to deliver, as well as a Prince of Peace,
of the increase of whose government there never shall be an end.
Let not your heart faint nor your hands fail.
Your acquaintance with trial and disappointment is not new, and if we abide faithful,
it will help us to do our day's work in the daytime.
I have now nearly gone through the families of Friends in this city,
and feel desirous of being discharged from further labor,
but cannot determine yet whether I shall or not,
but desire to be resigned to the Lord's will; and I hope you will not murmur,
as I trust the Lord will not only engage me in his service,
but make you sensible of the same.
May His powerful arm support and keep you and my beloved children,
is the constant prayer of my heart;
that if we are permitted to meet again we may rejoice
in that joy that is superior to the joys of harvest,
or the increase of corn, wine, or oil.
A joy that arises from an evidence that we have done the will of God,
which is felt to be "`joy unspeakable and full of glory.`"
Thus, my beloved companion, let us be encouraged to hold on our way.
Many have landed safely after a rough passage,
and have eventually been comforted within the confines of a calm and quiet harbor.
I have no doubt but that He who was with the disciples
when the winds blew and the sea ran high,
when their faith began to fail,
is still "`in the side of the ship,`" and has the same power, as he is called upon,
that ever he had, to say, "`Peace, be still,`" and so to bring a calm.
Thus may we be encouraged to dwell under the calming
influence of His holy Spirit from time to time,
and at all times, knowing that "`the foundation of God stands sure, having this seal,
the Lord knows them that are His,`" and whose hearts are devoted to serve Him.
I trust that it may be the will of our heavenly Father to permit us to meet again,
when our close trials and long separations will
be forgotten in the sweet reward of faithfulness.
My affectionate love to my dear parents and friends.
I remain your tender and affectionate husband in truth's Service.

[.signed-section-signature]
David Sands

=== Robbery of his Store

In the spring of 1783, he again commenced a mercantile business,
his residence being near where the soldiers were stationed,
though many were now disbanded.
They were in the habit of purchasing articles,
and became acquainted with the situation of the store, and in the following winter,
when the river was frozen, six young men, scarcely of age, headed by an elder one,
came to his house at midnight and broke open the door.
Finding they were in the premises, and no way to resist them, David Sands partly dressed,
and while they were forcing open the store door he raised a back window,
which was near the ground, and attempted to jump out to go for assistance.
As he was nearly out he saw a man point a gun towards him,
upon which he was favored to be able to return into the house again,
not having let the window fall from his hand.
The gun was so near that the flash lighted over his head.
During this time his wife was surrounded by the soldiers; one,
with a bayonet pointed at her breast, made inquiries for the money.
She immediately told them it was in the store, and they left her to go in search of it,
when she attempted to light a candle, but they forbade it.
They all rushed into the store, when David Sands again went through the window,
and ran to the nearest neighbors (nearly a quarter of a mile) through deep snow,
being but thinly clad, and without his hat.
The thieves seized the money-drawer, containing about fifty-dollars,
all being in change or coppers, and very heavy.
It being dark, they supposed they were in possession of a prize;
they soon emptied its contents, and then each took a load of fine broadcloth,
in all amounting to about five hundred dollars.
No other articles were disturbed, and they immediately started for West Point.
David Sands soon returned, and with him several neighbors,
and pursued them so closely as to pass them before they reached the river,
they having left the road; the men followed, and disposed of their goods,
etc. under the snow, and before daylight each was at his post.

When the officers were informed of the affair,
they said they would gladly find the offenders,
but could not determine in which way to proceed.
David Sands proposed to have the men placed in their ranks,
and said he believed that he could select the offenders.
The officers agreed to his proposal, but appeared doubtful as to its success.
David Sands walked up to the first, and, with the keen eye of justice fixed on him,
thus addressed him,--"`Where were you last night?`" "`On guard, sir,
and a cold night it was.`"
David Sands replied,
"`Did you find it cold when robbing my store?`" He denied the charge,
and proved so far innocent, that he was not one of the party; but David Sands insisted,
from his countenance, that he knew more of the matter than he was willing to acknowledge.
He then proceeded, and immediately selected three others; on which the older one,
who appeared to have been their leader, informed against them,
and by that means escaped punishment; but he was immediately banished.
In less than twenty-four hours the goods were all returned; also, part of the money,
having been buried in the snow.
Six of them were imprisoned, and martial law, according to the nature of the offense,
executed on four.
He desired they might be spared as much as possible, their time having nearly expired,
and their youth and the families with whom they
were connected being such as to claim sympathy.
The one who fired the gun, with another equally concerned, were put in irons,
and delivered up to the civil authority for punishment; which, as the laws then were,
would have condemned them to death.
They were sent to David Sands to proceed against them,
and he directed the person who had charge of them to take them to the county jail,
about twenty miles distant, they expecting he would appear against them in the morning;
but he had no idea of doing so,
though he permitted them to believe that they should be punished,
thinking it would prove salutary to them.
No one appearing against them, they were again returned to him.
He told them he had no wish to do anything with them,
and that they might return to their officers;
but first he had a comfortable breakfast prepared for them, of which they partook,
while tears of gratitude ran down their pale faces;
and although their hands were fastened with irons,
yet it appeared to be a very comfortable meal to them.
In the course of their stay the person who had charge of them,
being the same who was first accused by David Sands, said, "`Mr. Sands,
you felt in some measure inclined to include me in the number.`"
David Sands replied, looking earnestly at him,
"`I do not feel clear that you did not possess some knowledge of it,
if I can judge from your countenance both now and at the time;`" to which he answered,
"`What man would not feel a change, when closely examined by an eye like yours,
were he ever so innocent?`" But David Sands never withdrew his first judgment.

He gave the prisoners much important advice,
strengthening it with a hope of their forgiveness by their merciful Creator,
whose kindness they were now experiencing through his
unbounded mercy and not from their own merits,
which they must be sensible was the case,
and they were bound in duty to acknowledge his favor
and merciful forbearance by their future conduct.
They seemed much tendered and dropped many tears,
promising obedience and attention to what he had so kindly
expressed and the interest that he had manifested towards them.
Thus they took leave of him and his family.

A number of years after this,
When David Sands was on a religious visit in a far distant country,
attending an appointed meeting, in which he had much service and great openness,
and where much tenderness was evinced: after the meeting broke up, a man,
plainly dressed, came up to him and said, "`I wish to speak to you alone.`"
He took David by the hand, and, while weeping, thus addressed him:
"`I wish to ask your forgiveness, and rejoice in having this opportunity.
My conduct has been to me a source of grief, and at times almost bowed me to the earth.`"
David Sands replied: I think you are mistaken in the person; you are a stranger to me,
and I know not how any act of yours could have been connected with either me or mine.`"
The man replied--"`I am not mistaken.
I am the man who shot at you when your store was robbed.`"
David Sands replied--"`I remember the circumstance well, but have no power to forgive sin.
If your heavenly Father will forgive you, it is all I ask,
and am thankful to meet you in this situation.`"
He requested David Sands to accompany him to his house,
where he found an interesting woman his wife, she being a Friend's daughter,
but had married him contrary to the rules of society.
But she, with her husband, had now made application to be received as members.
This opportunity was truly gratifying,
particularly to one so entirely given up and devoted to
his Master's work as was the case with David Sands.
He labored to prepare his fellow-creatures for everlasting happiness.

From the time of the robbery until the year 1785,
he spent much of his time in visiting his friends of the meetings to which he belonged,
having also many meetings appointed amongst persons of other denominations.
His labors were well received.

His ministry was at once awakening and persuasive,
conveying deep conviction to the conscience of the careless, the rebellious,
and the unfaithful,
and greatly tending to the instruction and enlightening of the
understanding of the sincere inquirer after the way to Zion.
Many were gathered through his labors to unite in religious fellowship with Friends,
and some of these became useful and acceptable ministers,
laboring extensively in the service of the gospel.

In 1785, he spread a concern before his meetings, both monthly and quarterly,
to revisit his many near and dear friends, in the love of the gospel,
within the compass of New England, Rhode Island, Nantucket, Kennebec,
and other places as way might open.
His friends cordially united with his concern,
and he was enabled to accomplish this engagement in about a year.
The following letter, received by David Sands from another beloved fellow-laborer,
appears to have been written to him from London, about the 6th month, 1787.

[.letter-heading]
From John Pemberton to David Sands

The renewed testimony of your affectionate remembrance, and near sympathy,
was very cordial, and truly acceptable.
The Lord has seen fit to afford such supplies of instrumental help when I stood in need.
Many and deep are my conflicts in the arduous path I tread.
I believe few have had more general sympathy manifested towards them than I have had,
yet there are individuals who cannot see nor comprehend my steps,
which has brought your early movements, which were in a singular line,
often to my remembrance.
I was, with some others, ready to admire and to fear,
then little apprehending my own steps would be directed in a line similar.
After I last wrote you I entered Scotland again,
and spent upwards of six weeks on the west coast, and had (in company with David Ducat,
a worthy aged Friend of Cumberland) sixty-three meetings, in forty-four days,
amongst people much strangers to Friends and our religious principles,
and much bigoted and prejudiced; yet the Lord made way,
and a second opportunity was generally more open and comfortable.
It was as satisfactory a tour as any I ever had.
We did not imprudently hasten from places, but in some had two or three meetings.
The aged Friend was willing to journey my pace, which all companions have not been.
He had waded under a concern to visit the west coast many years,
but no way opened for him until I came.
He had been brought up a Presbyterian, and knew their principles well,
was strong and clear in doctrine, and much favored.
I hastened to this city to present myself to the brethren,
and to be open to any counsel they might have to communicate;
as I wish ever to stand open to advice.
My case was considered in the yearly meeting of ministers and elders,
which was a solid time, and I was left to the Lord and the guidance of his good Spirit;
but I have met since with some things which have afflicted.
I would be very grateful, and I should esteem it a favor,
could I have had liberty to return with our friends Patience Brayton, Ann Jessup,
Rebecca Wright, William Matthews, and Zechariah Dicks,
who expect to embark for Philadelphia in a few days.
My heart throbs; but I can not look to go home as yet with a peaceful mind.
Our dear friends Rebecca Jones and George Dylwyn are here, and are favored with help.
We all have our trials and besetments,
but all except myself have been directed to labor among the Brethren.
I am but little among them.
With dear love, and sincere desires for our preservation on the sure foundation,
in faith and patience, I am your very affectionate friend,

[.signed-section-signature]
John Pemberton

P+++.+++ S. The last yearly meeting was very large, and a favored season;
the largest number of hopeful youths I ever saw together.
The state of our religious Society, though low, is, I think, improving,
and the discipline better-maintained than in former years.
