== Chapter 7

[.chapter-synopsis]
* Visit to the Northern Counties
* Letters from J. B. of Darington
* G. Dillwyn
* Attends the Northern Yearly Meeting at Carlisle
* Yearly Meeting in London
* Letter from a Friend of Philadelphia
* Travels in England

8th month 9th, 1795, accompanied by Isaac and Susannah Hadwin,
William Farrer also bearing us company,
I set off to attend the quarterly meeting at Chester.
I passed the first meeting in silence, but another being appointed,
I was largely opened in doctrine, I believe to good satisfaction.
I found the business of the church done here
very differently from what I had been used to,
therefore thought it wisdom to meddle but little, yet made some remarks,
which seemed to be very kindly taken;
and at the close of this meeting I felt easy to return to Liverpool,
where I entered on a visit to the families,
in company with my much-loved friend Sarah Benson; and here I spent about ten days,
in which time I prepared myself for my journey;
and this service being crowned with the evidence of Divine favor,
as far as I had pursued it, I seemed easy to leave it for the present;
my health being poor, and the climate very different from ours.
Feeling easy to visit some particular and quarterly meetings,
I proceeded in company with my before-mentioned friend, Sarah Benson;
a woman remarkable for her humility and good understanding every way,
being most excellently gifted as a minister and elder.
We were at a meeting about eighteen miles from Liverpool,
which was held to good satisfaction.
Many tender people were at it, and I believe some were convinced that day.
After taking some meetings, and visiting several families,
we proceeded to the quarterly meeting at Kendal,
where I seemed pretty much opened in some of their meetings;
and after visiting some families, I felt easy to return to Lancaster quarterly meeting.
I may here remark, that at Kendal formerly lived our beloved friend, Rachel Wilson,
several of whose children remain yet, and are very hopeful.
Returning to Lancaster, I met many Friends from different parts of the nation,
and was favored with a comfortable meeting.
Many things were brought under notice that seemed to increase the weight,
and Friends appeared desirous of the prosperity of truth.

After this meeting, I returned again to Liverpool with my said friend, where,
after staying a few days to recruit, as I was often very unwell,
I set out for Manchester, and stopped at Warrington,
where formerly lived Samuel Fothergill, where I had before made some stop,
and visited several meetings near this place,
especially that which Samuel Fothergill used to attend.
After having visited a few families in Warrington, in company with our beloved friends,
John and Elizabeth Bludwick, at whose house I put up, and was most cordially entertained,
I proceeded to Manchester, and lodged with a kind friend, Isaac Cooke,
whose wife and children were also very kind.
There I tarried until I visited near forty families,
and had many public meetings to good satisfaction; and while here,
I assisted in establishing a school upon a plan new to Friends,
which met their general approbation.
Taking leave of Friends here, I returned to Warrington; was at the monthly meeting,
and so back to Liverpool, to finish visiting the remaining families,
and helping them to organize a school on the same plan as before mentioned,
which I accomplished to my own satisfaction, and I believe that of Friends generally;
William Farrer, before-mentioned, being my companion in this visit, and is still with me.

Going to a small meeting, we visited families, and had several public meetings,
to the relief of my own mind, and I believe that of many others;
and had a meeting at Langtree, and after closing the service here,
returned to a large town called Wigan, where I had two meetings in the Town Hall,
attended by abundance of people of various descriptions, to much satisfaction.
Soon afterwards, went to Warrington again,
where I met with my near friends and countrymen, Nicholas Wain and David Bacon,
on their return from Ireland, where, after spending some time together, we parted,
and I went towards York.
On the way, I was at two meetings, in one of which I was silent,
and in the other had something to say, without feeling much relief,
though some thought it a good meeting.

Leaving this place, I proceeded pretty directly for Leeds,
where I met with dear Thomas Colley, with whom I spent the evening,
and went with him the next day to York quarterly meeting,
and put up at the house of dear Lindley Murray, my countryman and very near friend, who,
with his wife, were much rejoiced to see me,
and we were greatly refreshed together in the Lord`'s presence,
which frequently was felt to cover us.
The quarterly meeting was very large,
and in the course of it several meetings for worship were held.
I found myself easy to sit in silence, and thought it a favor.
I was also at two other meetings here, to pretty good satisfaction.
Having now stayed with our valued friends for near two weeks,
I became a little recruited, having visited several families,
and particularly Thomas Priestman, at whose house, in the year 1772, died John Woolman.
His wife was yet living.
She attended our worthy friend in his last illness,
and expressed her great nearness to him.
Thomas Ross also died here, in 1786, at the house of our worthy friend Lindley Murray,
and was laid close to the remains of John Woolman, at his own request.
I now proceeded on my visit to a large seaport town on the northeast side of England,
taking meetings in my way.
On my journey I passed by the house near North Cave, where lived John Richardson,
when with his father-in law, where also he served his apprenticeship.
The meeting is at present quite small,
and few in it that appear as the offspring of that once great man, John Richardson.
I had two meetings here, and many people came to them, I believe to profit.
From this place I proceeded to a large town called Beverley, where I had three meetings,
two in the Town Hall, which were large and solemn,
and I think there was some convincement.
Here the number of Friends is small, but valuable; being people of good understanding,
and in a good measure purified by Divine grace.

We next went to Hull, and after spending a few days, and having had several meetings,
proceeded on to the north, visiting meetings,
which were generally too large for all to get into the houses;
but they all appeared to be much favored.
I returned to Beverley, with my much-loved friend T. Priestman and his affectionate wife,
and was at their meeting-house in the morning;
and in the afternoon went to the Town Hall, where we had a highly-favored meeting,
though so crowded that many could not get in.
From this place I went, with several valuable Friends,
to visit sundry places where no Friends`' meetings had ever been held,
in which places many attended, and were contrited and much broken.
I left them in great nearness of spirit,
and proceeded to a large town called Bridlington, where also, for a time,
once lived John Richardson,
at a period when this meeting was called "`A School of Prophets.`"
At present there is only one family of Friends in the place, and a few single people,
and these quite of the weaker sort,
as to holding up anything of a standard to the people.
Thus we see what a few years will do to us as well as to others;
especially where faithfulness is lacking.
There came many people into the meeting, but my way was quite closed up as to testimony.
I sat among them in much inward poverty, and so left them, and proceeded to Scarbro,
where are many signs of its having formerly been a place of great note,
but the walls and public buildings are now much decayed.
At this place George Fox suffered a very long and hard imprisonment in the Castle,
now much decayed.
I went to view the place,
and was interested in seeing what vast strong works and buildings there once had been;
the walls being six or seven feet thick.
Here are a few respectable Friends.
I sat with them, but had nothing to say.
I found my mind drawn to visit their families,
which I did to my own and their satisfaction.

I now proceeded to Pickering, and put up at William Rowntree`'s,
where I was kindly entertained.
The next being first-day, had two meetings; the last being publicly known,
there came in many very sober people, and we were favored with a refreshing season.
Here again I found my mind drawn to visit the families, which having accomplished,
had a large meeting about three miles off at Thornton; and the next day proceeded,
with several Friends in company, to Whitby, where I had several meetings,
and visited the families of Friends and some families
that did not belong to the Society nor profess with us;
in which labor I felt much inward peace.
I put up here at the house of a widow, whose name is Mary Linskill,
who is one of the true mothers in our Israel; under whose roof I took much comfort.
Leaving my near and dear Friends, and many tender people, I proceeded to Castleton,
where formerly lived Luke Cock.
This meeting seemed small and low, yet there remains a wrestling seed;
the house seems not quite left without a light in it.
I then proceeded to Guisborough, once a place where were many Friends,
but now only one family left, and a single member.
Here I was silent,
and can say I often find more openness where
there never was a meeting than at such places,
where they have dwindled away, or nearly so.
I proceeded to Ayton, and put up at the house of a kind friend, Nicholas Richardson,
and had two meetings here.

2nd month 13th, 1796, took leave, and attended a meeting at Rounton;
and on the 15th went to Yarm, and put up at the house of Joseph Proctor,
an ancient Friend in the ministry, who received us very kindly.
Here I attended the monthly meeting.
I was enabled to proceed in my little service to the satisfaction of myself and friends.
I had two meetings among the town`'s people, who behaved well,
although many had to stand for lack of room, and many could not get in;
and I think the power of truth was felt to reign.
I then came to Stockton, a very beautiful town, and put up at Henry Richardson`'s, who,
with his wife, were very attentive and kind.
I attended their middle week meeting, in which I felt much refreshed,
and found my mind drawn towards the inhabitants at large, which, after duly weighing,
I felt clear and easy to propose a meeting among them;
and may acknowledge that the Lord owned his own work,
and many appeared much broken and tendered in spirit.
A concern still resting on me, I proposed a second meeting,
which also was overshadowed with the love of Him who is
the Father of all the families of the earth,
to the tendering of many minds.
On the evening following, had a meeting at a large village.
These meetings were much crowded, and many unable to get in;
and many that did get in had to stand.
Having now visited about fifteen families between meetings, to much satisfaction,
I left them 2nd month 20th, near the setting of the sun, and rode about twelve miles,
to Darlington, where I put up at a very kind Friend`'s house, whose name was Joseph Pease.
His wife was in the ministry, and appeared to be a sweet-spirited woman,
and their children such as becomes the offspring of an elder and minister.
I attended their first-day meeting, where were a considerable number of Friends,
many of whom look hopeful, especially the youth.
The evening meeting being crowded with those not of our Society, we had a solid time,
much to the refreshment of Friends and others.

On second day, being 2nd month 22nd,
we had a very large meeting for those not of our society,
in which the power of truth prevailed, to the tendering of many hearts;
and not feeling clear, had a meeting on the day following, and one in the evening,
both crowded, so that many had to stand outside around the house;
and I may say we were favored to the melting of many hearts before the Lord.
After these meetings, I felt much relief,
and parted in love from these tender and valuable people for the present.

On the 24th, being much fatigued,
having had more service than two meetings a day for near three weeks,
I felt easy to rest for the present,
for the purpose of writing some letters to my friends in America,
having here received one from my dear daughter, Catharine Ring, much to my comfort.
On looking over my travels in this land, I find my mind refreshed with sweet peace,
and a hope accompanies that the Lord has blessed, and will bless, my hard labor,
as he has been pleased to put me forth and go before me hitherto.
Praise, therefore, be ascribed to His name forever.

Feeling clear of service in a public line, which after my writing was still the case,
while in this quiet situation, I was taken very unwell,
so that a physician was thought necessary, who, being called in,
attended me regularly twice a day.
My disorder, proceeding from a cold, appeared slow in its progress;
and consequently confined me about two weeks at the house of our friend, Joseph Pease.
When recovered a little, I found my mind engaged to visit a few families of Friends,
which I did, as I found strength in performing it,
which was at times graciously afforded to the comforting of many minds.
Having visited most of the families in this meeting, I felt easy to leave the place,
after a stay of four weeks, when I took leave of my kind friends,
both in the Society and others.
There appeared to be many seeking people in this town,
and many frequently visited me on a religious account,
unto whom I was enabled to impart some suitable advice;
and I believe several will join the society, if Friends keep their places.
My trials here have been great,
yet they have been made easier than could have been expected.

At this period,
David Sands received the following letter from one of the class just mentioned:

[.embedded-content-document.letter]
--

[.salutation]
Honored Friend--

Having, in the Friends`' Public Meeting-house heard you discourse on
the all-sufficient atonement for the redemption of souls,
by our blessed Lord and Savior Jesus Christ, in so clear a manner to my understanding,
that it gave me great satisfaction;
indeed I have enjoyed something similar to this at different times for many years past,
when I sat under the administration of the Calvinist doctrine,
and I acknowledge I was never so happy under any preaching as theirs,
judging it most agreeable to the Scriptures of any
doctrine I had ever had the opportunity of hearing.
Yet I think I did not experience some things in the manner you mentioned;
neither did I understand some of your doctrines; and I acknowledge I have not felt easy,
at different times, since I heard you, lest I should have to say, when it is too late,
as the Deist said, whom you made mention of:
therefore I will receive it as the greatest favor to have a little of your instruction;
for I am fully persuaded in my mind you are able, through Divine assistance,
to cast light upon many things that I see but darkly,
which are very necessary for me to know;
and I sincerely hope you will have an opportunity to do it; if not,
I trust you will pardon my request,
as I feel it important to the future state of your unworthy friend,

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Northsgate, February 26, 1796.

--

The Journal continues:--I next proceeded to Newcastle-upon-Tyne,
and put up at the house of Hadwen Bragg.
His wife is a daughter of our beloved friend, Rachel Wilson.
There I met with much kindness, and was at two meetings on first-day,
and at their monthly meeting on second-day;
in which meeting truth reigned in some good degree,
to the comfort of many deeply-proved ones, who, though honestly inclined,
yet have not been able to remove some things out of the way
that have been a stone of stumbling to many seeking minds.
Many things were gone into, concerning the state of the church.
A committee was appointed to visit some disorderly persons.
I felt easy to join in the said visit,
which was performed to a good degree of satisfaction.

I then proceeded to Shields, where I visited families,
to my own comfort and that of Friends.
My kind hostess, Margaret Bragg, who had long been a deeply proved woman,
went with me to Shields, where she appeared in a public testimony for the first time.
I put up at this place with Joseph Proctor, Jr., who, with a sister of his,
lives in this town, and carries on the business of shopkeeping.
He is a very tender young man,
and I think will yet become very serviceable in the church, if spared.
His sister was very kind, but seemed loath to give up to what was required of her.
Here I again entered on a visit to the families of Friends.
Margaret Bragg; continued with me, and appeared in the ministry, to the satisfaction,
I believe, of all.
We had several public meetings, and visited all the families.
We took leave of Friends and others here in much nearness of affection,
and proceeded to Sunderland; and took up our lodging with Thomas Richardson, who,
with his wife and only son, were very kind and attentive.
Margaret Bragg being yet with me,
I again felt my mind drawn to enter upon a visit to the families of Friends,
and finding much openness in their minds,
it made my way more easy than otherwise could have been expected.
Having finished this visit, I attended several meetings,
and felt easy to take leave of Friends, and left them in a sweet frame of mind.
Here Margaret Bragg left me, having grown much in her gift,
and returned with her husband,
and I proceeded to Staindrop monthly meeting by way of Durham.
Solomon Chapman accompanied me, and Thomas Richardson, Jr.,
son of the Friend where I lodged.
Solomon appeared under a concern to engage in the ministry,
and broke forth in several opportunities in families.
We reached Bishop Auckland that evening, and attended their meeting next day,
which was favored with the heart-tendering power of truth,
to the refreshing of several present.
Friends are but few at this place; the Bishop`'s palace being here,
the people are mostly of that sort.
We next went to Staindrop.

About this time David Sands received the following kind and
sympathizing letter from his friend and fellow-laborer George Dillwyn:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend, David Sands,

Your acceptable remembrance of 2nd month 16th, from Yarm, I duly received.
I had several times been asked whether we might expect
to see you at the approaching yearly meeting,
which I was unable to answer till within a few days past,
when I understood your back and not your face was turned this way,
so that it is not likely we shall soon have the pleasure of shaking hands.
It is, however, a satisfaction to believe we are both doing as well as we know how,
and as the religious Indian Tahpuhuany said to Anthony Benezet and Isaac Zane, when,
on parting at Philadelphia,
they asked him if he had anything on his mind towards his friends there,
"`Tell them that if they and I keep to that love
which has warmed our hearts when together,
it will bring us sometimes into remembrance of each other when separated.`"
So I may say to you.
The Friend who brought the account of your going north was, I believe,
of opinion that you were going into Scotland.
Dear John Pemberton met with open doors there in many parts, having, no doubt,
the right key with him.
I have been twice in that country,
but my prospect not extending much beyond our own lines,
I found myself more at a loss among strangers there,
than in any other part of Great Britain.
This shows the necessity of each one minding his own calling, and if he, dear man,
had more strictly observed the Master`'s injunction "`to salute no man
by the way,`" it is highly probable he would have escaped those
perplexities which so much embittered the latter years of his life.^
footnote:[John Pemberton was a man of a very tender and susceptible mind,
often fearful of omitting any duty.
This led to an indecision of character in reference to some of his religious services;
and he sometimes sought counsel of others beyond what they were qualified to give.
This was particularly the case in reference to views of
further service in Scotland and the Orkney Islands,
which he afterwards greatly regretted not having fully performed.
See J. Pemberton`'s Journal, pages 198, 200, 223, 288.]
But as I told him,
I thought his dearly bought experience would prove a lesson of instruction to many.
So I trust it has and will be to myself.
For as on one hand it shows how improper it is for us,
when the guiding ray of wisdom is withdrawn,
to turn aside for counsel or direction to others; so on the other hand,
it may convince us of the danger of an unwarranted
interference with those who are circumstanced as he was.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
George Dillwyn

[.signed-section-context-close]
London, 4th month, 21st, 1796

--

He next proceeded by way of Staindrop and Bishop Auckland to Durham,
where the quarterly meeting for the county was to be held, and lodged at an inn.
Here I met with many of my kind friends that I had visited before.
We were much refreshed together.
The business was conducted in a good degree of brotherly love,
and many things taken into consideration as
respects society that had been overlooked before.
In the meeting^
footnote:[Note, by the Editor--I well remember the meeting here so briefly described,
and the testimony borne that day,
which was of a very encouraging character to the sincere-hearted traveler Zionward.
He expressed his persuasion that some present were under the
Lord`'s preparing hand for service in the church.
He endeavored to strengthen the faith and hope of these, by calling to mind,
the manner of the Lord`'s dealings with some of his
little humble-minded devoted children in ancient times,
as in the case of Gideon.
How small was he in his own esteem,
yet how eminently were his endeavors blessed for the deliverance of his people from
the thraldom and oppression in which they were held by their enemies,
as he proceeded under Divine direction!
Such little devoted ones may not foresee the nature or
extent of the service to which they may,
if faithful, be called by their great Lord and Master.
The Lord`'s spiritual house, His church, is built of living stones;
each may seem insignificant of itself, but when fitly joined together,
they make a strong and beautiful building.
The acorn, the seed of the stately oak, is also small,
but when sown and nourished in a right soil and in a right climate,
in time it becomes a noble tree.
These trees, fitly prepared and framed together, become a gallant ship,
breasting the waves of the mighty ocean,
bearing along to distant lands many a precious cargo.
How beautiful upon the mountains are the feet of the Messengers of Peace,
who publish the glad tidings of the Gospel of life and
salvation through Jesus Christ our Lord! (This was the import
of that remarkable testimony on that memorable occasion.)]
for worship, I was much favored, and I believe several were convinced.
The Lord`'s power was known to reign, and Friends`' hearts were much tendered.
The business of the meeting being over,
we took leave of each other in a very tender and truly feeling manner.

I now proceeded towards the northern yearly meeting, by way of Benfieldside,
where many appear to have been convinced by our worthy friend George Fox.
And here was once a very large meeting,
but at present little is to be found of that so spoken of.
I passed on from this place to a meeting at Winness Hill,
but found my way so shut up that I felt most easy to leave it, and went on to Allandale,
where lived Rachel Wigham, mother to John Wigham, now in America;
and as we had been together there,
it appeared the more comfortable to this ancient Friend;
and I lodged with her son-in-law, Joseph Watson, with whom she lived.
I may also add, she is a living minister.
Here I was again taken poorly with my old complaint, and underwent much suffering,
though I was enabled to attend one meeting; but feeling a little better,
I attended another meeting on first-day, where many of other societies came in,
and truth reigned over all.
Several came after meeting to see me, and to inquire after the things of the kingdom,
who behaved with great modesty.
We had a comfortable season, and parted in much love and sweetness towards each other.

On second-day morning, we proceeded to Cornwood, where John Wigham, before mentioned,
was born, and lived many years.
We were at his brother`'s, Thomas Wigham, who was also in the ministry.
This meeting is small, and things but low; yet I thought the seed of life was to be felt,
and I may say that, through Divine goodness, we had a very favored season.
Here I was much reduced and under great discouragement, as my disorder seemed to increase.
I saw no way of getting forward except with great difficulty;
but the next day I felt a little better, and set off for Carlisle,
a distance of about twenty-three miles,
where I arrived with less trouble than I expected.
I stayed at the house of David Carrick until the yearly meeting came on,
which is called the Northern Yearly Meeting;
at which meeting I had much liberty or freedom in speaking to the states of the people,
and good service in the discipline of the church,
which was conducted with much harmony and brotherly love, to the edification of many,
and several seemed measurably convinced.
Here I was so feeble that I often thought I could not get to meetings,
but was carried through beyond my own expectation;
praised be the name of the Lord forever.
At this meeting were a number of hopeful young people,
and I thought the meeting of conference was very much owned,
and tended to general advantage.
After this, having taken leave of many very valuable Friends,
I set forward to reach the yearly meeting in London, taking many meetings in my way,
and appointing several in places where no meetings had been held for many years.
On my way, I met with Thomas Clarkson,
who had entered deeply into the state of the poor Africans,
and has gathered many articles of their making,
in order to prove to the British Parliament and Ministry their capacity for
industry and knowledge in many useful branches of business;
which clearly discovered their natural abilities.
He appeared to be a man of a tender spirit,
and much convinced of the truth of our principles.
I parted with him in near love, and proceeded to Appleby, where died Francis Howgill,
after many years`' imprisonment for the cause of truth.
The old prison is now nearly demolished, though some marks of it are left.

We proceeded to Darlington, and had a meeting about six miles off,
in a meeting-house belonging to the Methodists, to much satisfaction:
the people appeared kind and open.
From Darlington on my way to York had one meeting, and having arrived safe,
put up at the house of my old friend and countryman, Lindley Murray.
Here we were once more refreshed together, and after spending one day,
set forward to Ackworth, a large estate owned by Friends,
purchased for promoting the education of Friends`' children.
Here were now near 300 scholars, 170 boys, and 130 girls, educated by several teachers.
I thought I felt something more than usual of
weight in sitting with them in their meeting.
Having spent some time here, I left them in much love, and proceeded to Doncaster,
where I had a highly favored opportunity; and so passed on to Sheffield,
to Thomas Colley`'s, with whom I lodged; he having been in our country,
made the opportunity more refreshing.
Staying here a few days, and visiting several families,
I set forward with my friend Thomas Colley towards London,
and on our way had one appointed meeting where there had never been one before.

In London I put up at the house of Joseph Smith whose wife is a daughter of Rachel Wilson.
The yearly meeting now beginning by the holding
of the general meeting of ministers and elders,
was very large, and much weighty advice was given.
The business was managed in much brotherly love and harmony,
to the refreshment of many minds.
Having attended all the public meetings for worship during this yearly meeting,
in which I have been silent,
and often thought it was a favor to me that I was led in this manner,
as it gave me an opportunity to view the labors and gifts of others,
and to see the state of Society in this land.
The affairs of the church here are conducted with propriety;
many things were revived and gone into respecting the state of Society,
and the standard of truth was raised up in a good degree,
respecting the order and Christian discipline of the Church.

The following letter, received by David Sands about this time, is without signature,
but must not be omitted:--

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend--

Your letter of the 10th month 18th last, dated at Stockport, came acceptably to me;
having had you frequently and affectionately on my mind;
recollecting at times your bodily infirmities,
it was particularly gratifying to learn from yourself
that you had been favored to move in the line of duty,
under the sustaining power of the Shepherd of Israel;
and that through His continued mercy and favor,
strength of mind and health of body was vouchsafed,
so as to qualify you for the service of the day.
Holy, just, and true is He. May you and I, dear friend, now in our advanced years,
lean singly and solely on His Divine arm for succor and support,
through every one of his providential dispensations; in heights and in depths,
and in all those dippings, exercises, and baptisms which He may, in unfathomable wisdom,
direct or permit for our refinement and preparation for His work and service.
That light is sowed for the righteous, and gladness for the upright in heart, is,
I believe, an immutable truth.
Your fear is just, that the inhabitants of this highly favored city,
at least too many of them, would so pass over the solemn visitation of the year 1793,
that the sanctifying, purifying effect thereby intended,
would not have the desired influence.
Many, very many were, I believe, in that awful season, humbled and deeply reached;
desires were excited in them, and covenants made, that if spared for a time to remain,
they would bow to the power of an offended Creator,
and serve Him with a more perfect heart.
But alas! how have the people, at least the great bulk of them, increased in pride,
wantonness, and dissipation!
Have we not just cause to expect the rod will
again be shaken over this ungrateful generation?

I have noticed what you have said respecting the prospect of
the length of your stay on the other side of the water.
By daily attention,
and keeping a single eye to the hand that led you forth
into the present important and dignified service;
suppressing and watchfully guarding against the reasonings and
imaginations of the creature--but in the depths of solemn retirement,
when all fleshly wisdom is set at naught, and the sure guide, the Divine Counsellor,
is with undoubted certainty and clearness heard and understood; then, dear David,
will you move on in the appointment of pure wisdom,
and His strength and anointing influence will not be withheld.
I believe it may be needful for the servants to be watchful and guarded,
who are called forth to publish the glad tidings of peace and salvation,
and who have known days of abounding, and their labors crowned with heavenly consolation,
that a desire to live on the dainties of the Lord`'s table,
may not excite to any movements or extension of service,
which the great Master of the family has not clearly painted out.

By this ship a valuable cargo goes from us to you: two dear women.
Friends from England, Deborah Darby and Rebecca Young, having,
with singular diligence and very great acceptance, visited this continent,
even in the remotest part, where Friends are settled,
and held many meetings with persons not professing with us;
and also in many places they have been engaged in visiting the families in our society.
Their extensive and well-authorized labors have been so accompanied with restoring,
reclaiming love, that a sweet savor will they leave in this land,
and the seals and edifying fruits of their ministry are not a few.
Added to these two dear handmaids of the Lord,
are our endeared friends Samuel Emlen and William Savery.
To give them up to the Lord`'s requirings herein,
has been trying to many of their brethren and sisters, who are nearly united to them.
I may own, as one of the little ones in the family,
that it has been an occasion of close exercise to me.
Nevertheless, having felt in a measure the weight of their concern,
I could do no less than "`loose them and let them go,`" though stripping indeed,
and to our meeting in particular, will it be.
There are also cleared out from our general spring meeting, on a like embassy,
our esteemed friends, Sarah Talbot and Phebe Speakman, from Chester county,
and who proceed in the same ship called the "`Sussex,`" Captain Atkins,
bound for Liverpool.

It is but lately that I returned from an arduous journey,
through a mountainous and very rough country,
to attend the opening of a newly-established monthly meeting,
at a place called Calwessey,
situate on the borders of the northeast branch of the river Susquehanna.
From this service, myself and several others from this city,
under appointment from our quarterly meeting, returned but a few days past;
and I am now preparing to proceed to Newcastle,
to see the Friends above-mentioned take ship.
So I am a good deal straitened for time,
but did not feel easy to let the present opportunity slip,
without sending you some testimony of my affectionate remembrance of,
and tender sympathy with you, under the pressure of your present allotment.

__Signature lacking; but is supposed to have been from John Elliott,
of Philadelphia__

[.signed-section-context-close]
Philadelphia, 5th month 15th, 1797.

--
