== Chapter 8

[.chapter-synopsis]
* Studies the Dutch and German Languages
* Arrives at Bremen
* Visits Hamburg, Hanover, Pyrmont, Brunswick, Magdeburgh, Brandeuburgh, Potsdam, and Berlin
* Visit to Freyenwalde, where they met Charles Albinus
* Return to Berlin, and Service there
* To Potsdam
* Magdeburgh
* Halberstadt
* Wolfenbuttel
* Pyrmont
* Letter from Major Marconnay on the King of Prussia`'s willingness to receive a Visit
* Visit to parts of Holland, Germany, and France

Before proceeding to insert David Sands`' Journal
of his travels on the Continent of Europe,
it may be proper to describe in what a remarkable manner he
was rendered additionally qualified for the performance of
this important service by his having acquired,
in a very unexpected manner, a considerable knowledge of the Dutch and German languages.
It is thus mentioned in his papers:

While visiting the family of a dear Friend in Philadelphia, who was then lately deceased,
the children, when speaking of their father,
mentioned the interest he had expressed to them which he had felt in
the perusal of some of the books of his Low Dutch library,
remarking that the religious histories and various other matters contained
in them were far superior to many books in use at the present day,
and had been amongst his most valuable entertainments.
David Sands inquired if none of them were disposed to learn the language,
whereby these books might yet be useful.
One of them replied that they were not so inclined,
at which David Sands expressed some surprise.
One of them queried, "`Friend Sands,
would you accept them?`" "`Most willingly,`" said he,
"`and prize them highly for your dear father`'s sake.`"
They seemed gratified by his acceptance of them, as they would be cared for.
Accordingly they were packed up and forwarded to his home.
The prospect of a visit to Europe being then before him,
was an inducement for his endeavoring to obtain some knowledge of the German language.
The reader may remember that, in his youthful years,
he had pursued with avidity opportunities to learn the Latin,
which would now be of use to him.
On his return home, he commenced with the Primer, which he learned grammatically;
and in the course of three months,
he could read most of the New Testament in the Dutch language;
and in a short time he could read the other books.
Amongst them was a history of the early Christians, which was interesting,
and at the same time promoted his improvement in the language.

When he reached Germany,
his knowledge of the Low Dutch so far assisted him in acquiring the German language,
that, in three weeks, he could read the German New Testament, and,
with a little assistance from an interpreter,
he was enabled to offer his public testimony in that language satisfactorily;
yet he preferred a good interpreter.
Thus, by his industry and perseverance,
he soon acquired a sufficient knowledge of these
languages to be understood in his public communications,
this being at times the medium through which he could
best perform his great Master`'s work acceptably.

When in France also,
he experienced much advantage from having acquired some knowledge of their language,
as his friends often acknowledged.
The spirits of some of those amongst whom he
labored were so much united to him in the truth,
that it tended to make their language, though imperfectly expressed,
more easily and feelingly understood by each other.
But a fear of making any awkward mistake, especially on doctrinal points,
led these Friends to prefer a good feeling interpreter.
He thus continues his Journal:

After the yearly meeting in London (1796) was over,
I found my mind exercised to open my prospect to the
select yearly meeting of ministers and elders,
as respected going to Holland.
The spreading of this concern appeared to bring a weighty exercise over the meeting,
and Friends uniting with it, expressed their unity in much brotherly love and sympathy.
The yearly meeting closed in a very solemn manner, to the refreshment of many Friends.
We now took leave of each other in much tenderness and brotherly love;
since which time I have been in and about London, visiting meetings, and appointing many,
in which I felt my mind relieved from a weight which lay upon it.
The people of this city appear very open and free in attending meetings,
and behave well when there.
My trials appear to be many on account of my bad health,
which seemed to increase those of my mind, which have not been few.

In the city I meet with many of my acquaintances from America,
and several very intimate friends.
Four Friends lately arrived from Philadelphia,
being liberated by the yearly meeting of that city, namely: Samuel Emlen, William Savery,
Phebe Speakman, and Sarah Talbot.

Having solidly weighed the circumstances attending my going direct for Holland,
I felt measurably easy to unite with my much-loved friends and companions:
William Farrer having concluded to be my companion through Germany,
as he had been through England; and George Dillwyn and William Savery,
who were proceeding to Germany by way of Bremen; for which purpose,
with the unity of Friends, we took passage,
and went on board of a brig of about three hundred tons, called the "`Victoria.`"

Many have been the inward exercises of my mind in preparing for this voyage,
in which I have been favored with the near sympathy of many friends,
who took leave of me at my lodgings.
Our parting was accompanied with many tears and
supplications to Him who has all power in his hands,
to whose care and gracious protection we recommended each other,
as believing it most probable that we should
never all meet again in a state of mutability.

My kind friend and host, Joseph Smith, with his very sympathizing and affectionate wife,
his brother-in-law, George Stacey and wife, with our ancient friend, David Bacon,
from North America, William Dillwyn, Joseph Savery and wife, with several other Friends,
accompanied us about four miles, to Black Wall, where the vessel lay.
My feelings at parting seemed to be again quickened,
and I thought I never felt more reduced than at this time.
Yet a little sense of that all-sustaining Arm that has ever
been the support of those who trust in him was granted.
Our parting was in much brokenness and great nearness of spirit.
We again resigned each other to our Heavenly Father`'s care.

We now set sail with a pleasant wind, and sailed down the river Thames,
and saw many vessels going out and coming in;
with the sight of a very delightful country, highly improved by cultivation.
But my mind could not enjoy it much, as my health was but poor.
The wind continued in our favor for several days, which brought us in sight of land,
where we had to lie for one night, in the mouth of the river or arm of the sea,
at the entrance of the river Weiser, which was very difficult, and we had no pilot.

The day following, we sailed pleasantly up the river, and met many vessels outward bound;
by one of which, bound to Philadelphia, I wrote to my dear wife.
In our passage, my companions were all very sick; but now coming into still water,
they recovered.
Coming to anchor to wait for the tide, George Dillwyn, William Farrer, William Savery,
and myself went on shore;
where walking round to see the country and refresh ourselves with the air,
we were invited to the house of a man who was secretary to the prince of this country,
who treated us very kindly.
His mother was an ancient woman, and appeared to be very affectionate towards us.
She walked with us in their garden for near half an hour.
We found our minds much united to her in near sympathy.
George Dillwyn had a little to communicate to her, as also myself,
William Savery being better acquainted with the Dutch language,
interpreted our communications to her, so that she understood, and replied,
"`God be with you and cover you, and carry you safe back to your families.`"
Now parting with her, we returned to our vessel, and proceeded up the river to a village,
and here I went on shore and found the people very civil.
I distributed a few books.
This country, on the west side of the Weiser,
is dyked off from the river by a very high bank being cast up; on which they travel,
and which appears to be the main road.
They build their houses behind the bank,
so that we can only see part of the houses as we sail up the river.
At this place we left the vessel;
but the evening previous we had an opportunity with the
men and passengers to a good degree of satisfaction.
About two o`'clock next day, we went on board of a little boat,
where we were very much crowded and uncomfortable.
The wind failing, and the tide coming against us,
we went on shore at a village in the Hanoverian government.
We here had the opportunity of seeing how the people lived,
which seemed to me to exceed all I had ever heard of or seen before;
the family and the cattle living together, with little separation.
After taking a view of this village, we returned to the vessel, and soon after,
the wind springing up, we set sail for a town called Negesah,
where we lodged at a pretty good inn.

On the 11th of 8th month, 1796, we arrived at Bremen,
and put up at a house outside the town wall or city gate.
Our landlady seemed to be very kind and attentive to us.
Here we enjoyed the satisfaction of having things decent and in good order,
as to our victuals and lodging.
I went out but little, being affected with lameness in my ankles and feet,
and otherwise much indisposed.

On our first landing I went into a house where a woman treated me kindly,
though I could not say much to her, as she could neither speak nor understand English,
and I not understanding much High Dutch, made it difficult to communicate to each other,
yet I believe there was something felt by which our spirits were
united in that fellowship which words cannot fully express.
In this place I have renewedly found the necessity of seeking
Him for counsel who is the great Counsellor of his people.
Many have been the trials I have gone through in this land,
yet have hitherto been supported.

Several days having now elapsed, and nothing very favorable appearing,
we thought of leaving this place, after spreading a few books,
and my companions making a few visits to some seeking people,
who seemed to be in some measure convinced of our principles,
but yet shy of entering into a very near acquaintance with us.
One man, however, visited us twice, and though not much inclined for conversation,
seemed to be very clear in his mind respecting our principles, and owned them freely.
This city stands on the east side of the Weiser; it is walled round,
and a large canal cut to let the waters flow round the city.
The people seemed very civil to us,
and we gave some notice that we intended to hold a meeting on the first day of the week;
but none of the inhabitants came to us,
and we held our meeting to a good degree of comfort amongst ourselves.
The people seemed to be engaged to attend their own meetings, which, we were informed,
began about eight o`'clock in the morning, and they had two meetings,
which were generally over about one o`'clock,
and the after part of the day and night appears
to be spent by many in various kinds of mirth.
The inns are full, some drinking, some gaming,
and all kinds of vanity and folly seem to possess the minds of the people;
and what made it appear more strange, was, that these people were mostly Calvinists,
and profess much as to the sanctity of what they call the Sabbath-day.
Yet neither the priest nor the magistrate takes any notice of these things,
as I understood.

On feeling after the mind of truth,
we seemed united that it would be best to proceed to Hamburgh.
After taking a solid leave of our kind landlady and her children,
on the 16th of 8th month, about seven o`'clock in the morning,
we proceeded in a wagon and four horses, which carried us about three Dutch miles,
which is about eighteen English, to Ottenburgh, where we took dinner.
The people seem mostly to live in pretty large buildings of one story, with sharp roofs,
the end standing to the road, with a large door,
sufficient for a loaded wagon to drive into the yard.
At the entrance we find an earthen floor,
which is frequently all the floor found in the house,
except some rooms may be paved or laid with flat stones.
The front, or entrance part of the building, the cattle, horses, sheep,
and fowls generally occupy; and in the back part the people live.
It is not uncommon to see the racks of pewter and other household goods
quite open and exposed to the view of their cows and other stock.
The fire is kept in the back part, on the floor, in a kind of box, or stones laid round,
without any chimney, the smoke going out at different doors.
On the same floor, they stow their grain and hay,
so that themselves and the cattle seem to make but one family;
and which is most proper to say, that the cattle live in the house,
or the people live in the barn, I have not been able to determine.

We left this place, and proceeded to Rottenburgh, two Dutch miles,
where my companions drank some coffee and milk,
and again proceeded on about three Dutch miles further, to a village called Tastoss.
Here we lodged, and met with pretty good treatment,
as we have done since entering on this journey.

We left this place on the 17th of 8th month, and proceeded.
The country seems quite open as to fences,
so that for many miles we see no mark of any division in the land by fences,
or unploughed land between the pieces of grain,
and it looks as though one man owned the whole, for many miles together;
as all the land that would bear any kind of grain seemed to be occupied and full,
so that riding five or six miles it was all one harvest-field, of one sort or other,
but principally of rye or oats.
I never saw so much of that kind of grain, or any such harvest-fields before.
Though the soil looks very poor, being a kind of whitish sand,
yet it produces rye and oats beyond what I could have imagined.
The land looks as though they sowed it every year, and we saw none but what was in grain,
or reaped.
For thirty miles together, (except little pieces round their houses,
and some small pieces of meadow), I did not see grass, standing or growing,
or any place where it had grown sufficient to get ten tons of hay.
They keep their cows up in the stable for most part of the time, till after harvest,
when they are turned out and tended by either women or men in certain places,
as they agree.
Hogs and all are kept in this way.
I saw many flocks of sheep on their barren land,
where nothing seemed to grow but heath on which they feed,
but they are very ordinary indeed, and mostly of the black sort;
seldom seeing white sheep amongst them.
The women tend the sheep, and indeed serve for the most servile purposes;
they are very different from either English or American women,
both as respects their figure and strength:
they carry remarkable burdens on their backs and heads.
Their dress is very coarse and simple, frequently without anything upon their head,
more than a little kind of cap that sits close;
so that they have nothing to screen them from the hot sun,
and yet they appear to be of fair complexion, and seem pretty cheerful:
they live in a dirty way.
The country generally is very sandy, so that a wagon travels very slow,
not more than three and a half miles English, in an hour.
I saw some fruit, but it was very scarce and dear.
The people seem to be contented with the necessaries without the luxuries,
or even many of the real comforts of life.

1796, 18th of 8th month.
This day we crossed the River Elbe.
After proceeding down a branch of it for about six miles English,
we arrived at the city of Hamburg.
Two of our companions having gone before,
had provided lodgings for us at the house of a widow of the name of Seebohm,
where we found ourselves in provisions,
and paid two shillings a-day for our rooms and beds.
Here we tarried until the 25th. During our stay we found many seeking people,
who appeared very glad of our visit to them; we had several religious opportunities,
and on first-day we had a meeting amongst a few tender-spirited people,
and in the evening we had an opportunity with several others,
at the house of a young Englishman, who, with his wife,
had lately come here to settle in the mercantile line.
He had been educated among Friends, but had gone out in marriage.
At this opportunity were several young men of good understanding and family,
who seemed well satisfied;
so that I hope our coming here has not been altogether in vain.
This is a very large city, and is called a free port.
It contains, by information, about one hundred and fifty thousand inhabitants:
the buildings appeared to have much carved work about them,
and many of them are very high;
but their notions of greatness are so different from those of the English people,
that their fine things look very tawdry and foolish.
This city has many canals cut through it in various directions,
for the purpose of boats coming through it, so that they want but little done by horses,
and it is not uncommon to see men working in a kind of collar or harness,
several together,
so that they frequently draw hogsheads of sugar on carts or little low wagons.
The people were civil to us, and obliging when we lacked anything.
They generally attend their places of worship on first-day in the forenoon,
beginning about eight o`'clock,
and have two meetings which are generally finished about twelve o`'clock,
when they go to dinner, after which many go out of town,
and the greater part spend the remainder of the day in
various kinds of diversions and amusements.

I went about two English miles to the city of Altona, which is large,
as to the ground it stands upon, but not so full of inhabitants as Hamburg,
as it is not situated so convenient for trade.
On my return over a common that lies between the two cities,
the people seemed to cover the ground, and in many houses there were crowds of people.
Here they were entertained with various sorts of music and dancing,
which was carried on in almost every house:
some appeared to be dancing at the beat of drums and other sorts of music.
I inquired if the priest or magistrate did not interfere on such occasions,
and was told they did nothing but provide a few soldiers to ride about to prevent mobs,
and see that there was no murder committed.
I observed two soldiers riding very slowly amongst the people,
to whom they paid very little attention.
This practice having been a custom so long that it is thought very little of,
by Lutherans and Calvinists, or any other religious sect; and,
from what I could understand,
they looked upon the afternoon of the first day of the
week as a time for feasting and frolicking.
In these cities there are many Jews: they appear to be generally poor,
and in Hamburg there is a portion of the city set apart for them, where they may live,
and in no other part.
And here they are obliged to bear arms, do the drudgery of the city,
and pay very heavy taxes for the privilege of being citizens.
The people appear to be given to many vices,
and the streets are very noisy through the night, with music and dancing.

Feeling our minds clear of this place, we proceeded to a city called Zell,
where our entertainment was not very good.
The people appeared strange, and our prospects were trying to us; but next morning,
walking about the town, we seemed refreshed;
and after some inquiries we heard of some
religious persons whom we found to be Moravians,
and some others who received our visit very kindly; to whom we gave books.
This city seems to be ancient, and is kept very clean.
Here was born George, the first King of England of that name,
and here remains the palace where he resided before he went to England,
which is very large, though time has much defaced it.
The stones and all the ornaments about it are much decayed.
After we had spent several days,
we took our leave of a few friendly families and our landlady and her servants,
in much nearness of spirit, and proceeded to Hanover,
where we arrived on the 30th of 8th month, 1796, and put up at the Amsterdam Inn,
until the 4th of 9th month.

Our accommodations were pretty good;
we found a number of friendly people who received us with much joy.
They were quite separated from the public worship held in that city,
and sometimes met for religious conferences with each other.
Some of them seemed inclined to the Moravian Society,
but others had got some Friends`' books, and seemed perfectly convinced of our principles,
but no religion being tolerated here but the Lutheran, Calvinistic, and the Romish,
makes it very difficult for such as are not joined to them to avow themselves,
so as to be publicly known; as the priests of all orders, and the magistrates,
are very severe with all who do not unite with one or the other.
So that suffering must be the portion of those who would openly meet,
though it should be in silence.
Yet I believe that the time is near,
when some will be called out to bear a public testimony
against their false worship and bad conduct.
The people here generally, as in many parts of Germany,
seem to have but little sense of religion.

We visited these tender people in their families, and had one public meeting with them,
to their and our satisfaction; and left a number of books with them,
and parted in great nearness of heart.
We proceeded to a city called Hammlen.
This is in a beautiful situation.
We stayed here one night and part of two days.
I passed through this city,
and felt my mind drawn to speak to a man standing at his door, who took me by the hand,
and would have welcomed me in, but my object was to inquire after serious persons,
and such as were called Quakers.
And he informed me I had passed the house of one so called, about three doors;
and directed me back, where I went in, and was met by a very good-looking man,
advanced in years, who looked on his wife, and said,
"`These are my brothers;`" but we found he was not quite of our way of thinking,
although very near to us in the best sense.
We stayed at his house, and he provided food and seemed greatly rejoiced to see us,
and told us there were none of our profession in that city,
nor any other than of the common religions of Germany.
He seemed like one alone.
The people here seem to be very dark; quite given up to the pursuits of the world.
The common people appeared poor and oppressed.

On the 6th of 9th month they reached Pyrmont,
where they had a variety of useful services,
of which no account appears in David Sands`' memoranda.
They were serviceable in bringing about a reconciliation between
those who had separated through the influence of Emanuel Brown.
They had conferences with Herman Shutamire, Henry Munthang, and Anthony Shonning,
who were the chief of them; and had them together, with the principal Friends;
and through the prevalence of the humbling melting power of Divine love,
with which these conferences were mercifully owned,
they became again united in Christian fellowship.
Several Friends met them here from Minden and Boetter;
they also paid a visit to the governor of the town, Klapp, with useful effect.
They formed an acquaintance with a valuable Friend from Minden, Chris, Reckefus,
who had suffered for his testimony against ecclesiastical impositions.
One of his children dying, he had him buried in his garden.
Six months after,
the priest had the corpse taken up and laid in the public burial-ground,
and then distrained on Christopher for his fees.
This Friend undertook to drive their carriage for some weeks.
They were the means of getting the monthly meeting, which had been dropped, revived,
and attended the first held by appointment, which continued four hours, to edification.

They left Pyrmont 9th month 29th, and reached Mela, and there to Brunswick,
where they paid an agreeable visit to the Duchess, sister to the King of England,
(George the Third.) At Helmstead, they called on Professor Beireis,
who is a man of learning, with whom they had a friendly conference,
and presented him with a copy of Barclay`'s Apology, in Latin.
They then proceeded to Magdeburgh, where they had a meeting with about seventy persons,
to good satisfaction.
They visited several families, and were instrumental in detecting an impostor,
in whom some of the simple-hearted, serious people were placing a foolish confidence.
They distributed some books, and parted in much affection.
David Sands thus proceeds:

10th month 5th, 1796.--We left Magdeburgh early in the morning,
and reached Brandenburg next day, which we spent in visiting several sober people,
to good satisfaction; and about six o`'clock had a public meeting with them,
in which truth arose into a good degree of dominion,
so that we had to acknowledge the goodness of the Lord in thus
favoring us in that strange land to feel His power near,
and to open the hearts of a remnant to receive us in much brotherly love and sympathy.
After our meeting was ended, we took our solemn leave.
Some of them said they should never forget the opportunity as long as they lived.

10th month 7th.--We reached Potsdam, a large city, with extraordinary fine buildings.
Here dwells the King of Prussia.
There are two palaces.
The building and furniture of the palaces exceed anything I ever read of or saw,
as they appear to be generally ornamented with gold and silver.
One of the palaces, I was informed, had one hundred and forty-eight rooms,
all furnished in the most extraordinary manner
that money and art could contrive or invent.
We spent some hours in walking about the city, and then proceeded to Berlin,
where we arrived near night; and after being examined as to where we came from,
and whether we had any business in the mercantile way, we were set at liberty,
and went to the Inn.

8th, being first-day, we spent pretty much in our chamber,
though several of our company went out and found some tender people,
and one to whom we were recommended from Magdeburgh by a man there,
who appeared to be very friendly towards us, with whom we left several books.
This man, after we left him, changed his mind on reading them, and put up the books,
and sent them with a letter to Berlin, to counteract what he had written before,
directed to the man to whom he had recommended us.
Thus we found our way unexpectedly shut up, much to our disappointment.
How changeable a creature is man!
And how little is he to be depended on!
We have met with very civil treatment as yet amongst the Prussians,
except what I before mentioned, the effects of this man`'s so writing,
which seems inconsistent with the character of a sincere-hearted man.

11th.--We still abode at our Inn, without much encouragement,
as the people seemed alarmed at what had been written to those
to whom we expected a visit would have been acceptable.
But in the evening, seven good-looking men came to us,
who at first seemed more like spies than brethren,
with whom William Savery and Lewis Seebohm had a pretty open time in conversation;
and the opportunity closed in a solemn time in supplication, and a few words after it,
which seemed to remove the cloud from off their minds;
and in tenderness of spirit we parted,
with some expectations of a more general opportunity, which we requested,
and they promised to use their endeavors, by consulting their brethren.
We continued at our Inn most of the day waiting to see
what way would open for our moving forward,
either to another visit, or for us to return, which at present seemed to be hid from us.
Here we found that much patience was necessary, that we might not move in our own time,
or under the influence of our own spirits,
but might know the putting forth of the Great Shepherd of Israel,
who puts forth and goes before his humble servants.
About six o`'clock in the evening came two young men to see us,
who appeared very sober well-behaved men.
They informed us that there was no prospect of
our holding a meeting with them at present,
but thought way would be made in the course of a day or two;
they informed us that there was to be a meeting that began at seven o`'clock that evening,
amongst a religious people that frequently met together,
where was an elderly man that expounded the Scriptures, and sometimes preached to them;
and they invited us to go, which I felt a freedom to accept,
though William Savery and the other Friends seemed most easy to stay,
except Lewis Seebohm, who went with me.
We found the old man rather opposed to us,
and he seemed not willing that we should sit with them, which was a new trial to us;
but after weighing the matter, and a little more conversation,
he invited us to go with them into an upper room, which we did,
and found about twenty persons sitting, and after a little while came several more.
The old man gave us a seat quite behind, which we cheerfully accepted.
He then began his service by repeating some passages of Scripture,
and then read a part of a chapter, and began to expound it to the people,
which lasted near an hour, during which the people sat very quiet,
though they seemed but little affected with what he said.
After his time for expounding was over, he appeared in prayer,
in which he mentioned the chapter and verse of several texts of Scripture;
after which the meeting broke up,
when I desired Lewis Seebohm to request their patience a little while,
as I had something to say.
They sat down again, and truth seemed to rise into some dominion,
and much brokenness appeared amongst them.
After standing about half an hour, I felt easy to sit down,
and then all shyness that before was to be seen and felt appeared to be gone;
so that we parted with them with many expressions of
their love and desires for our preservation.
We expressed a desire for a further opportunity, which seemed to meet their approbation.
In returning to our lodgings, I was ready to say,
"`Strong is the Lord,`" and how does he make way for
his servants whom he sends out on his errands.
Surely the hearts of all men are in his hands,
and praise and thanksgiving are due to him for evermore.

On the 12th of 10th month, we rested at our Inn; had several friendly people to see us,
and one informed us of a meeting that was proposed to be held at our Inn at six o`'clock,
with our consent, to which we agreed.
At the time proposed there came two priests, one a Lutheran, the other a Reformant,
with about twenty or more of those who appeared to be principal men among them.
I felt much tried,
believing there were many of this company more like spies than well-wishers to us;
but the Lord was pleased to look down upon us and favor us with strength;
so that both William Savery and myself were preserved
from falling under any censure from them,
and what we had to deliver appeared to be very acceptable.
Most of the meeting appeared to be in a tender contrite state, and some very much so.
Thus, the Lord`'s power being over us, we parted in much good-will.
The priests acknowledged that they had been greatly refreshed,
and expressed many wishes for our welfare.
We now seemed to feel refreshed also, and our spirits revived,
and a hope springing up of our success, we felt our courage renewed.

10th month 13th.--I having had a prospect of going about forty miles eastward,
we now thought it a proper time to proceed, which we did.
We left Berlin about seven o`'clock in the morning, and arrived at Freyenwalde,
the place we had in view, about seven o`'clock in the evening.
We found it a large town, situated between the mountains.
Soon after we got to an Inn,
Lewis Seebohm went in pursuit of a religious man that we heard of, and soon found him,
and requested him to call on his religious friends, which he did,
and then came to let us know it.
I thought I saw something more than common in his countenance when he first came.
We went with him to the meeting, and found about twenty persons,
which were the religious company that usually met by themselves.
We had a comfortable room and a very open opportunity, so that they seemed much tendered,
and parted in great nearness of spirit.
The friendly man before mentioned went back with us to our lodgings,
and appeared much refreshed by the opportunity,
and informed us that the man at whose house the meeting was held was sick,
and desired to see us.
We paid him a visit the next morning, and found him very ill.
He appeared to be a man of note in the world,
and his wife also a person of good understanding, as well as a very comely woman,
who the evening before seemed much reached:
and we now had a very solid opportunity in the family, and parted in great love.
I thought I felt more relief from this opportunity than
from any I have had since being in Germany,
on such an occasion.
We retired to our Inn, and prepared to set off for Berlin,
with the before-mentioned friendly man with us; his name was Charles Albinus.
He had, not long before we met with him,
resigned his post or office of Secretary to the King,
which had brought him in a considerable sum yearly,
but which he gave up on a religious account,
and had retired from the bustle of worldly affairs to spend
his days in a more retired way than he had done before,
though not yet forty years of age.
This man appeared to receive both us and our doctrine with great satisfaction.

10th month 14th.--We left Freyenwalde and reached Berlin that night.
This day was very trying to me, having taken a heavy cold, I apprehended,
from sleeping in a damp bed;
so that before I reached Berlin I was so ill that it
rendered my riding in a wagon very uncomfortable;
but I was supported to hold out so as to reach our Inn,
where our landlord received us very cheerfully, and our new friend, Charles Albinus,
with us.

15th. We spent mostly at our Inn, myself in particular, being very unwell.
Lewis Seebohm went out to see if we might be at a private meeting,
to be held at a priest`'s house, who had been at a meeting with us,
and who seemed to accept us in the greatest love, and promised his assistance;
but he sent us word that the magistrates were about to send us out of the city;
and further, that he wished to serve us, but could not: therefore,
wished us not to attend his meeting; but said, if we would hold one at our Inn,
he would give notice at his meeting; which, after weighing, we found liberty so to do;
and again sent him word by a few lines, which he read to the people then assembled;
but after reading, said to them that we held bad principles,
and that the magistrates were about to send us away,
and advised them not to go to our meeting.
Thus he discovered himself to be unsound, as to his former pretensions.
We now again seemed to be surrounded on every side with
various difficulties that seemed to threaten us,
and no way opened for any escape; therefore,
to the Lord only could we look and cry for help, who had hitherto helped us,
and so settled down to bear whatever might be permitted as a trial of our faith.

In the course of the day, several came to see us, who seemed to strengthen us;
and in the evening there came a number to hold a dispute with us,
who appeared not envious, but supposed we were well-inclined men, but in error;
and they wished to set us right.
The subjects they wanted to converse with us upon were Water Baptism,
and the Bread and Wine, by way of ordinance.
They brought their Testament with them, and all prepared as to places in Scripture;
but here they seemed to have the advantage,
as none of us could hold a dispute in Dutch but our interpreter,
who did not attend so much to what I said as not
to enter into his own explanation of matters;
which for some time gave them an advantage over him,
and led from the points in dispute into that of the effects of water baptism;
which wandering way of disputing I have never seen do any good,
but that if anything is done to advantage,
it generally is by attending simply to the baptism of John, and that of Christ,
distinctly.
But after some time, he who managed the dispute being very full of words,
seemed to spend himself a little.
I then desired him to be quiet; and when he spoke to the matter, to be short and clear,
as I had been and intended to be.
I urged a proof from Scripture for water baptism, as being the express command of Christ,
and also for their mode of administering it,
(as their mode must be supposed to be what they
thought right.) This put him to a nonplus,
and he declined it; but would hold to water baptism in more general terms.
I distinguished between water baptism in the general, and their mode;
which he declined to undertake the defense of, but soon grew weary of the subject,
and said he must go.
I endeavored to soften the matter a little,
and others entered into the subject on more general terms, so the discussion ended.
I thought they seemed much disappointed,
as I believe they thought their ground so good that on it they could not be withstood;
but they soon saw that so much could be said on the question,
and that they could not withstand the force of it,
that they seemed to doubt whether there was so much in it as they had thought.
William Savery having offered something in the controversy, now speaking Dutch,
they seemed to unite in some points;
and after a pretty full opportunity I requested them to stop, which they did,
as to conversation; and a reverential feeling came over us,
and we had a very solemn opportunity in supplication,
in which the Lord`'s power seemed to shine over all, and our hearts were humbled together,
so that we parted in much brotherly love.

This being the seventh-day evening, we concluded to hold a meeting next day,
being the 16th of 10th month, in our own room, at ten o`'clock,
to which came most of our friendly acquaintances;
and the Lord favored us to experience of his
mercy and goodness in a very humbling manner,
to the contriting of our hearts and qualifying to offer unto Him the praise of all,
to whom it is due now and forever.
We now had our evening meeting in prospect, to be held at six o`'clock,
which was very weighty upon our spirits;
and being before invited to dine with a friendly man, who sent a coach for us, we went,
where both William Savery and myself had some acceptable service.
To this house came a daughter of one who had been friendly to us,
who appeared to be a very solid young woman, and had before sent us a book,
in order to receive our names; with a desire, if we found anything resting on our minds,
we would write it under our names; which we did,
as it appeared to me as though it was right at that time,
though it may not always be the case.
This, I understood, was a practice among the religious people in Germany.
We had a very suitable opportunity with her and the family,
and left them in a sweet frame of mind, and returned to our Inn about five o`'clock.
The people collected very fast, and soon filled our rooms,
which brought a great weight upon us on several accounts,
as the lack of a suitable place, for we could not furnish this with seats;
and many of the great of this world seemed to be coming,
and all unacquainted with our manner of sitting or moving in our meetings.
But soon after the meeting was gathered, my dear fellow laborer, William Savery,
appeared in prayer.
In the exercise of his gift therein, he was led to touch on the states of many present,
and a solemn silence prevailed, and ended in brokenness of heart in many.
After which, I felt my way clear to stand up, and found great openness.
Truth continued to rise into dominion to the humbling of many minds;
after which I was easy to sit down, and William Savery rose and stood near an hour.
I then found the spirit of prayer to come upon me very strong,
and I yielded to its motion,
and was very much favored to the solemnizing of the hearts of the people.
Our meeting ended in great sweetness, and we parted in tenderness of spirit.
Our rooms were full, and according to the best account we could get,
there were near two hundred people present,
the greater part of whom had stood three hours or more,
and I think I never saw people of any description continue with such stillness.
They appeared as though they were neither weary nor faint;
never moving from their places, so as to make the least noise,
but with weighty solemn countenances seemed
engaged to know the truth in order to follow it;
many of them came with expressions of gratitude and embraced us,
of the youth as well as of the aged.

10th month, 17th.--We found our minds not fully relieved;
at least I was still bound in spirit, though my companions seemed pretty cheerful.
A sick woman had the evening before sent for us to make her a visit,
which William Savery, with L. Seebohm and myself, did this morning,
and found nearly twenty persons present, of the religious sort.
We were favored with a very open opportunity with them; their hearts seemed tender,
and we parted in great love.
Still finding our minds not clear, as to leaving this place, after weighing the matter,
our way opened to have another meeting; which we appointed in our chamber,
to be held at six o`'clock; to which came nearly a hundred people, who appeared solid.
Many of them had heard of our meetings, but had not been to any of them.
I found my mind set at liberty,
and the Lord`'s power rose higher than I had known it before, since being in Germany,
through my ministry.
The people seemed to be melted into great tenderness, so that several wept aloud.
After I sat down, dear William Savery appeared in prayer,
and I thought it exceeded any that I had ever heard before from him.
The meeting now ending, the people took leave in great brokenness,
and we retired to take our rest.

Next morning, the 18th of 10th month, many came to visit us that had been at meeting,
especially an elderly man who had been a Major in the Prussian army,
and the day before had been to see us;
and towards whom I felt a particular draught of love,
and was dipped into near sympathy with him,
and had something to offer that was very suitable,
as he afterwards confessed when he came to open his condition to us.
He was much contrited, and said his questions had been answered and his state opened,
and he was thankful that the Lord had sent us into that land, and hoped that he should,
through Divine grace, be more faithful in time to come.
We now thought of another meeting, which we appointed in the evening,
where came more than one hundred.
We had in this meeting to labor to establish the principles we had been preaching; which,
when we are led to do,
never seems to raise and animate the minds of the people to
that height that advocating more general views does;
but having cleared our minds of what lay with some weight upon us,
tenderness of spirit appeared in many, and our meeting concluded in solemn prayer,
and we took leave of the tender people, thinking to leave them in the morning,
in order to return towards Holland.

This morning, being the 19th of 10th month, we left the city about ten o`'clock.
It was a very solemn time to many who came to see us before leaving; and our landlord,
with his wife and children, seemed much affected, and many others,
who seemed as though they could hardly endure the moment of our parting.
Indeed, it was a time to be remembered by us all.
We had many portions of advice to leave with several of the family,
who received it in much brokenness of heart.
I had an opportunity with our landlord and his family by themselves,
in which I hope I was in my place.
I recommended them to God, their best teacher and guide,
after which we parted in much nearness and love.

We proceeded back to Potsdam, the residence of the King of Prussia, as aforesaid,
which we reached about two o`'clock.
We dined, without making much stay.
Our company having agreed to reach Brandenburgh that evening,
but yet I did not feel quite easy so to do, but submitted,
and had often to reflect on my own conduct in so doing,
believing I was not right in leaving this place then.
I found weakness to increase upon me and on all our company.
The road being bad we traveled very slowly, and reached a poor Inn about nine o`'clock,
where we were obliged to stop, though fifteen miles short of our intended Inn.
Here we could get little to eat, and the most of our company lay upon straw, though I,
being unwell, had a bed; but being covered with another it was very unpleasant;
and from frequently flinging it off throughout the night I took a violent cold,
which distressed me much, and made me feel very low, both in body and mind.

On the morning of 19th month 20th, we went about twelve miles, to Brandenburgh,
where we breakfasted; after which Lewis Seebohm went to see our friendly acquaintances,
made when in this town before; who received him with expressions of kindness.
We remembered our love to him, and to all our friends in the town,
which they promised to do, we being in haste to proceed towards Holland.
Hitherto the Lord has helped us beyond what we deserved,
or had reasonable grounds to expect.
Just as we were leaving this place came the elderly man whom we visited in the morning,
as we left this town before; he met us with much kindness,
and told us his daughter desired her love to us.
We parted in much nearness of spirit, after embracing each other very affectionately.
We then proceeded to a large village called Zelan, about eighteen miles.
This day has been very dull, having felt but little of the presence of Christ.
We traveled about forty-two miles to Magdeburgh, and put up at our former Inn,
where we were gladly welcomed,
and where we had been before very cordially received
amongst a religious people called Pietists;
but, as before observed,
we were disappointed in some of the leading members of the Society,
particularly the schoolmaster, who gave us a few lines to Berlin, as before mentioned.

I may now acknowledge the favor I enjoy in feeling better, both in body and mind,
for these two days past.
Lewis Seebohm having been out to see some of our former friends,
returned and expressed the satisfaction that some had mentioned in hearing of our return.
We hope, before we leave this city,
to see matters more settled as to what has been circulated
respecting the bad principles we are said to hold.
10th month 23rd.--Being first-day, we had a meeting at our Inn,
where came two friendly men and sat with us;
when we had an opportunity to open to them the principles of truth,
we hope to their advantage and our refreshment.
After meeting, we proposed a meeting among them at half-past four,
when we met a number of solid people,
but they seemed as though they were rather
looking for our halting than to help us forward;
though, as we apprehended,
they had received some unfavorable impressions by the reports
spread by the before-mentioned man respecting our books.
William Savery appeared in prayer in the early part of the meeting,
and the people kept their seats; after which I had something to offer,
which they seemed to oppose for some time,
but the power of truth rising and spreading over them, they were brought down,
and tenderness of spirit appeared amongst them; and finding truth had gained ground,
I sat down, to leave the way open to my fellow-laborer,
who had a seasonable opportunity with them; and when he sat down,
I felt something weighty upon my mind, and stood up, when the Lord`'s power reigned,
to the breaking down of the stout-hearted, as one who often appeared to scoff at us,
in the fore part of the meeting, broke out into many tears.
On sitting down, I soon felt my heart exercised to engage in the solemn act of prayer,
in which I was much refreshed.
The meeting then broke up in great sweetness, under a sense of Divine goodness.
After taking leave of each other, we returned to our Inn,
where came several that were at the meeting;
and we had some friendly conversation with them on several subjects,
which they did not seem clear in;
yet I believe that the light has broken forth amongst them, and will gradually arise,
and finally remove those things that have been an obstacle and
hinderance to the springing up of vital religion.

10th month 24th. We arrived at Halberstadt.
Next morning, soon after we had taken our breakfast, came a very solid man,
who saluted us very kindly and spent a short time with us,
and made way for a meeting to be held at six o`'clock this evening.
In passing along the street, I observed the door of a Roman Catholic Chapel open;
I went in, and found it greatly ornamented with images and pictures,
with a great deal of carved work.
The candlesticks appeared like solid gold,
and many things that strike the outward senses, such as the representation of Christ,
as large as life, extended upon the cross,
with the Virgin Mary and one other standing near, in a very pensive attitude,
and many other representations; but all seemed to be covered with dark superstition,
and the people very ignorant as to the spiritual life.
We found our landlord and family very friendly to us.
He had a son whom he had educated for a minister,
and said he was very sorry that he had not been brought up to some other business,
as he had no inclination for preaching,
nor for several other things that are usually done by the clergy,
such as taking money from the poor, for what they called the Sacrament.
This he thought he could not do;
as he said they often took it from such as needed it for their common necessities.
He was very friendly to us, and went to the meeting and behaved very soberly.
The number attending was small, but I was glad I was there,
though I went under great discouragement.
I believe the Lord owned our endeavors, and we parted in much nearness of spirit.
After we returned to our lodging, the young man before spoken of, and one other,
came to see us, and had much friendly conversation with William Savery,
in which he seemed to be near to us in principle.

Next morning we set out for the city of Brunswick,
after taking a tender leave of the family, especially the young man before mentioned.
We passed through the suburbs of the city called Wolfenbuttel,
where it is said Luther wrote much of his works.
The people relate that, when writing, he was beset by Satan,
who attempted to get his inkstand; which Luther perceiving,
took it up and flung it at him so hard that he broke it against the wall,
where the ink remains to be seen to this day.
I did not find time to examine the matter myself,
but I believe it is generally credited here.

This day we have passed through a very fertile country,
where we saw many fine towns and villages.
We arrived in Brunswick about six o`'clock.
Soon after came the doctor, who before had visited us, with another person,
who received us with much love and seeming affection, and spent the evening with us.
We laid our prospect before them of having a meeting,
that they might consider of it and let us know in the morning.

10th month 27th.--The old man who was with us last evening came this morning,
and proposed the meeting to be held at half-past five, to which we agreed;
but before the time appointed,
there came a friendly man and informed us the house could not
be obtained that was intended for the meeting to be held in.
This was a new trial of faith and patience; but through Divine mercy and goodness,
I felt my mind stayed in a comfortable hope that way would be made for the meeting,
which soon after was done,
having information by another messenger that a house was obtained.
Near the time appointed, we went to the meeting, and found a few gathered,
and soon after came a number more, so that the rooms were pretty well filled,
and the great Master seemed to own our assembly with the overshadowing of his love.
My dear friend and fellow-laborer William Savery was much favored in supplication,
in the fore part of the meeting:
the savor of life continued to increase rather than diminish through the meeting.
At this meeting I saw the first man sit with his hat on, since I have been in Germany,
except those that profess the principles that we do; he was the doctor before mentioned.
He appears to be a man of a tender spirit, and much convinced of our principles.
In the meetings I thought I felt the call of Christ to him in a particular manner:
he appeared tender and well satisfied with the meeting;
and after it was over he came to our lodgings, and supped with us;
after which he took leave of us in an affectionate manner.
Thus we parted in near love, with desires for each other`'s preservation.
I felt much peace of mind after this meeting, though my health was very poor;
and after I went to bed, I felt as though my senses would leave me,
and on the whole had a very exercising night;
and in the morning was much straitened to know what to do as to going or staying.
However, I felt a little strength to go on, though it proved a very trying day,
traveling 42 miles, and taking very little nourishment; yet I was brought through.
I may here observe that many are the afflictions of us poor mortals,
but the Lord delivers out of them all, as we call upon him.

We passed through the city of Hildesheim, where I before had felt uneasy,
without trying to have an opportunity with the people;
but my friends being now desirous to go forward, and myself but weak,
I submitted to go on, which brought on me a very great burden.
Having been directed to a place to stay that night,
we went and found ourselves in a very poor situation, as the people seemed unfriendly,
and we had to accept of very poor accommodations, and pay high for it.
Here I grew worse,
having also to reflect upon myself for not standing faithful to my prospect.
In the morning, discouragements prevailed,
so that I gave up the prospect of going forward that day;
but after taking a little breakfast, I thought it best to try to proceed to Pyrmont,
which I did; and though many were my exercises, yet I got through safe,
so as to enjoy the company of my dear friends, especially George Dillwyn and wife,
who still remained here, and whose labors I believe have been of great use,
and a blessing to the people of this place.
Here I again felt my mind humbled under a sense of my
lack of patience to perform what opened on my mind.
I had felt a strong desire when at Berlin to see the King of Prussia,
and made some attempts to obtain an opportunity, which did not then open as I expected,
and we all felt rather unsettled, and left the city,
after leaving a letter and some of Barclay`'s Apologies with a friendly man for the King.
In about two days the King received them, and an officer was sent after us,
but did not overtake us.
The person who had the care of our letter and book sent us the following letter:

[.salutation]
To The Friends who visited Berlin--

My last words to you, my dear Friends, were,
"`God be with you`"--words which evinced the fulness of my heart.
I love you with all my soul.
I never was so soon inclined to unite with any men as I was with you.
I never felt so readily a constraint to open my mind to any men as I did to you.
I have opened this sick heart into your loving souls;
but yet you are not wholly acquainted with my tried condition,
for there are feelings which cannot be expressed in words.
It seems as if I was forsaken of God, and yet I abhor the thought.
I have no desire to live or to die.
For the pleasures of the world, let them be called what they may, I have neither taste,
sense, nor feeling; but who will believe it, that nature can thus loathe,
thus nauseate the world? Yet my heart remains
shut up from higher and heavenly enjoyments:
the precious sense of the communion with God that I formerly enjoyed
in the assurance of faith and the consolations of the word;
all this, which in my former situation I enjoyed, tasted,
and felt of these gracious gifts of God, I have scarcely a remembrance.
My prayers are weak and powerless;
it is as if I cried to God from afar--that he cannot hear me;
and this is also a thought which I abhor.
Such, my dear brethren, is nearly the circumstances of my soul.
Let your hearts now feel with painful compassion how it is with me,
and so fall down upon your faces before the throne of the Great and Merciful Being,
and pray for your poor, weak, and wounded brother,
that Jesus Christ may again be beautifully formed in my heart,
that I may again rightly fix my eyes upon Him;
then shall I be able to stand in this heavy exercise.
I shall take from his hand the bitter cup, and not murmur, but wait for his help:
then I shall be enabled in the end to exclaim, "`Lord God, gracious and merciful;
you are great, and your kindness and faithfulness;
who was ever confounded that trusted in you!`"

Yesterday, my beloved brethren, the Minister Howitz sent for me,
and said that he had just now received a letter from the King,
who was very willing and ready to give you an audience;
and oh how gladly would I have called you back,
as I wished most heartily an interview between you and our good King.
I told the Minister it was possible you might have stayed over yesterday, the 21st,
at Potsdam;
after which he immediately dispatched a chasseur to the general Bishop Wender,
to notify him that you might be there.
Whether the chasseur has met with you I know not, but if it be according to my wishes,
you will have an audience with the King tomorrow morning at nine; and in this case,
I heartily desire, dear brothers, that you will give me, as soon as possible,
circumstantial information of your conference;
persuaded I shall not make any bad use of what you entrust me with.
Your letter to the King, the Minister sent to him yesterday, but the book,
which the messenger could not take, was sent to the monarch to-day.
Now for the conclusion: God be with you; his light be your guide;
his love and grace in and through Christ Jesus
be your protection and defense in all dangers.
Be of good comfort, and be filled with joyful hope.
He that is with you is stronger than he that is against you.
Never shall your memory be effaced from my soul; never shall I cease to love you;
it will be a comfort to my weary soul if sometimes you
will make me joyful by imparting a few lines of love,
and nothing but death will prevent my answering your dear letter.
In love I embrace you in my heart as your ever loving brother,

[.signed-section-signature]
Major Marconnay

[.signed-section-context-close]
Berlin, 22nd Oct., 1796.

Bishop Wender is appointed to introduce all strangers to the King.

This interesting letter we met at this place, Pyrmont,
on our return the 29th of 10th month,
since which we have had our various exercises and services.
We found Friends generally well, and that love appears to be gaining ground amongst them.
We have had a trying time since coming here,
being much shut up as to what way to proceed;
but resignation being our only resting-place,
we have been desirous to cast our anchor in that calm Haven to which, I trust,
some of us have attained.

11th month 5th,
1796.--I this day received a number of letters from my friends in New England.
They seem to be growing in heavenly things,
which is a source of satisfaction and relief to me; but, alas, my journey looks long,
and in my present feeble state,
my return to my dear family and friends looks rather dubious than otherwise.
