== Chapter 9

[.chapter-synopsis]
* Letter to his Wife
* Arrival at Minden
* At Hertford
* At Hanover
* Carriage overturned, and return to Minden
* Amsterdam
* The Hague
* Rotterdam
* Sluys
* Dunkirk

The following letter is addressed to his wife,
giving some particulars of his late travels in Germany:

[.embedded-content-document.letter]
--

[.salutation]
My Dear Wife,

It is now more than a month since I have written to you, for lack of opportunity,
having been far back into Germany.
We have traveled since I left this place more than six
hundred miles in little more than a month;
in which journey I have passed through many principalities and parts of kingdoms,
but principally the kingdom of Prussia.
In my way there I made a visit to the Duchess of Brunswick,
in company with my friends William Savery and our
companions Benjamin Johnson and William Farrer,
the latter of whom continues still with me, and is a great comfort in this land,
having every way continued steady and attentive to me in my many needs.
The Duchess, who is sister to the King of England, received us very kindly,
and conversed freely on various subjects.
We gave her one of Penn`'s "`No Cross No Crown,`"
which she received with much cheerfulness.
She asked us whether there were any of our people in Germany,
or if we ever knew any Germans that were Quakers; to which Lewis Seebohm,
our interpreter, answered he was one, and that there were many more in Germany;
to which she replied that she wished all the world were of our sentiments,
then things would be better,
and that though she had been married to the Duke of Brunswick many years,
and had not seen England,
she still retained the remembrance of Friends and their principles.
We parted with expressions of love,
and desires for each other`'s prosperity in the best things.
Though uncommon for those in her station she
seemed willing to let us take her by the hand,
(William Savery and myself.)

We now returned, and after a little opportunity, with a few friendly people in this city,
we proceeded to a city in Prussia, called Magdeburgh,
the strongest fortified place in Germany.
We found that it contained about 3,000 inhabitants,
and those the most civil and respectful we had met with in Germany.
I think I never saw so well-behaved, clean, and handsome people before,
especially the female part; the goodness of their features,
ornamented with modest countenances and plain dress, joined to a sweet disposition,
made them to appear above the rest of mankind.
This great change from other parts of Germany, made everything look pleasant,
especially as we found here many tender people, who held about six little meetings:
they were not broken off from the public worship wholly;
but met together to edify each other.
They received us with every expression of kindness,
as their dear brethren sent to them from a far country.
Our labors among them in public and private had a tendency to unite us,
and the truth seemed to reign over all.
We left them, and pursued our course eastward,
through many cities and large towns and villages, having meetings as way opened;
and I may say the Great Shepherd owned our movements in a very extraordinary manner,
so that I had to admire how his own arm brought salvation,
and wrought his own acts of wonder.
We at length arrived at Berlin, the greatest city in Prussia, and where the king dwells;
here we met with some trials when we first came,
which seemed to discourage us for a short time.
But we soon found that way began to open for us until our meetings became large,
and I think I never knew more solid meetings,
nor anywhere greater brokenness appeared than among these people.
They stood thick crowded for three hours at a time,
without discovering the least uneasiness, and when we parted with them,
a tender love appeared among them not to be equalled, but by my own children.
Oh! the nearness, the sympathy and affection that was evinced among young and old.
Here I met with several of high rank in the world,
who received us in the love of the truth, and a young man,
one of the king`'s council of war, who had left his post on a religious account,
has been with us more than three weeks,
and traveled with us between three and four hundred miles:
he appears to be a man of steady behavior, and very solid deportment,
and has declared that his sentiments are with us, both in principle and practice.
We left this city a few days, and went east to another place,
where we found several religious people, and had a meeting with them,
to much satisfaction, and returned again to Berlin.

Here I had an opportunity to see the court of the king of Prussia,
composed of many of the greatest people of Germany;
their clothes appeared on most of them as if stiff with wrought gold,
and far beyond what my imagination could form an idea of; but all were civil to us,
from the king and his family down to the lowest subject.
I have had to remark the civility to strangers is beyond
anything I have seen either in England or America.

When I was farther east,
the sun rose seven hours before it rises in that part of America where my habitation is,
and yet, though thus far from home,
I could seem to look with pleasure towards my dear family and friends,
with a hope that if it be the Lord`'s will, I may again be restored to them.
I have had my health well since being in Germany, except on taking colds,
which brought on a cough, though it is better.
I am now with my dear friend George Dillwyn and wife, who seem like housekeepers,
having been here near two months.

I expect to leave in a few days, whether for Holland or to return again east,
and to some other places that way, I cannot now determine.
When I was at Berlin, I wished to speak to the king of Prussia,
having something on my mind to say to him in a particular manner,
which opportunity I could not obtain when there,
he having gone to a seat where he sometimes dwells.
And the minister of state did not open the way for us at that time.
We left a few lines, and a copy of Barclay`'s Apology with a friend of ours,
a man of high rank, who promised to forward them to the king, which he did.
Two days after we left Berlin, a message was sent after us,
that the king would give us an opportunity to see him, and had wished us to return;
the officer did not overtake us,
but a letter was sent forward by our friend who opened the way He is a very pious man,
and one with us in principle The letter was received at this place,
which increased our exercise; as we were not clear when we left Berlin.
Whether I may not be excused from so arduous an undertaking,
and the burden laid on some that can bear it better, I do not at present clearly see;
but desire to do whatever may be right in this and all other things.

This letter seems more like a little journal than a letter,
but I thought it would afford satisfaction to you and my dear children,
to hear how I get on, and of the Lord`'s mercy and goodness to me in this land,
and among a people of strange language.
But I may say the Lord is good, and his tender mercies are over all.
I hope you and my dear children can join me in saying the same.
I have, by attention, learned to read the High Dutch Testament,
nearly as well as English; and speak it so as to hold conversation,
and have the satisfaction of knowing what is said,
which is a very great comfort to me and my friends here, who cannot speak English.
I have not received a letter from you for some time; but hope,
though we are many thousand miles apart in body, yet we are joined together in spirit,
and shall so remain; cherished by an unshaken hope, that if we, in holy appointment,
meet no more here, we shall, before many years, meet again to part no more.
My dear love to father and mother Hallock; tell them I often think of them,
with a hope that the Lord is leading them more and more into the house of prayer,
and retirement from the world, that their sun may set in clearness.
We can have no sanguine hopes of seeing each other again in this world,
but the animating hope of meeting in a better, is much to be preferred;
where the wicked cease from troubling, and the weary are at rest,
in unexplored scenes of joy that lasts forevermore.
I still encourage myself with a hope that I may return next fall, if I live;
but must leave it at present.
I cannot say that I should feel comfortable if I was now at home;
as I frequently dream of being at home and am always in great distress,
looking for a passage to return to Europe; so that when I awake,
I feel glad it is but a dream.

I received a letter this day from Remington Hobby,
expressive of the increase of Friends in his country, which is a comfort to me,
when reflecting on the arduous labor and time spent in that country,
by myself and many other faithful laborers.
I now conclude in dearest love to you and my dear children and connections,
and recommend you to him who neither sleeps by day nor slumbers by night,
who is God over all, blessed forever.
Your ever affectionate husband,

[.signed-section-signature]
David Sands

[.signed-section-context-close]
Pyrmont, 11th month 5th, 1796

--

We have had several favored meetings here at Pyrmont,
and still remain at a loss to know when we shall get clear of our service in this place.

11th month 9th.--We have made a visit to some Friends,
in which we have been favored to get through to our comfort.
This day I attended their meeting, which was a favored opportunity,
and we found our minds set at liberty to proceed when way might open.
This being a parting meeting,
in which some little difficulty having happened relative to some meeting business,
we were engaged to have it settled, and which was now accomplished through divine help,
to our own and Friends`' mutual satisfaction.
I have been renewedly instructed in the necessity of attending
to the little intimations that are afforded from day to day;
notwithstanding we seemed clear, especially my companions,
yet I felt some weight hang upon my mind that I could not cast off,
but by dwelling in the patience, the way was gradually opened to all our comfort,
and now we feel our way clear to proceed.
We set off for Rinteln, which, though not more than twenty miles,
we did not reach till near night, having traveled over a very mountainous country:
but my mind seemed much preserved in quiet through this day`'s journey.
We put up at an Inn, where was very poor accommodation, and high charges.
We found here a few tender people, who received us,
and with whom we had a satisfactory opportunity, and parted in near love.
This city is in the Hessian dominions:
several have been banished and their property
taken from them for embracing our principles;
and still there appears to be an envious spirit against us.
At this place there were many tender people a few years back,
but now they are much scattered.
The city appears ancient, and very little business doing in it,
the people are mostly poor, and of low behavior;
very different to those in the cities of Prussia.
Having done here what we apprehended our duty, we left on the 12th of 11th month,
and proceeded to a city called Minden, in the dominion of Prussia,
where we found several that professed with us,
and who hold a meeting in the way of Friends.
We understood that there had been about sixty persons who met together,
but who were now much scattered.
We had several meetings with them,
and found that some uneasiness had taken place among those that met together,
which we were enabled to assist in settling.
We left Minden on the 14th, and went to Hertford, where we arrived the same day,
and put up at a very good Inn.
Here we found a few people who seemed friendly towards us,
and with whom we had a meeting, which was to our satisfaction.

17th.--We parted with these friendly people in much love,
and went a few miles to a Friend`'s house, where a small meeting was held.
The Friend`'s name was Christian Reckefus;
he had suffered much for his faithful testimony on many accounts,
and has been carried through; so that the cause of truth has not suffered by him.
From there we proceeded again to Hertford.
On our way we met with a tender woman of high rank in the world, who received us kindly;
though her husband was not reconciled to her embracing Friends`' principles.
He had treated our dear friend, John Pemberton, very roughly; yet,
after we entered his house, and had sat a short time, he grew more friendly,
and gave up his house to hold a meeting in.
Several of us dined with him, where we met a young man,
a Lieutenant in the Prussian army, that quartered there, who was very kind,
and also consented to our having the meeting in his room.
He attended, and was much contrited, with several others.
He said he was forced into the army, and had no other way of getting a living;
but wished all the world were of our principles, so that there would be no more war;
and that it would be a great happiness to mankind.
We parted in love, and the master of the house also appeared well satisfied.

11th month 19th.--Proceeded to Bidefield, about twelve miles,
where we were obliged to lodge at a poor Inn,
but the next evening I was invited to a very respectable merchant`'s house to lodge,
which I accepted.
My situation was thus unexpectedly changed, and I was made comfortable.
The family was very kind to me, and I had several religious opportunities with them.
On first-day afternoon we had a meeting with about twenty persons,
whose conduct was very good.
This meeting was in the suburbs of the city.
There appeared no openness to proceed further as to meetings,
nor was the way to leave clear to us, which made it very trying.

11th month 24th.--This day we had a meeting at our Inn.
About thirty persons attended of the better sort, who were kind and friendly towards us.

11th month 25th.--We had another meeting at our Inn.
A number attended, which was some relief;
and after it we had an opportunity with several persons and families,
much to our satisfaction.
From this place we proceeded towards Hanover, but the way being very rough,
we traveled but nine English miles the whole day.
Having to walk most of the way, we felt ourselves much tried, both in body and mind;
but through all, we have found the Lord near to give us patience and carry us through.
This night we lodged at an Inn, much better than we expected,
having given up thinking of getting more than a shelter from the cold; as in Germany,
many villages have not a house where a traveler can obtain a bed.
The people live in a very poor low way;
their floors have little appearance of wood in
consequence of their not cleaning the dirt off them.

11th month 30th.--We reached Hanover, where we met our fellow-laborers,
George Dillwyn and wife, who had a meeting in the morning,
and had also appointed another that afternoon, which we attended,
and it appeared to be a profitable opportunity.
My mind was much comforted in being here,
and seeing what a growth there was among the little flock since we visited them before,
both in weight and number.

12th month 1st.--The meeting was held in the suburbs.
We then rested as to public labor, except to visit some friendly people;
and on the 3rd of the month had a favorable meeting again at the place before mentioned,
where came a larger number;
and in the evening we had a solid opportunity with a
number of persons who visited us at our Inn.

5th and 6th, we spent in visiting some tender people, and receiving such to see us,
which took up our time fully;
and in the evenings we had generally a pretty large number to sit with us.

12th month 7th.--Being first-day, we proposed a meeting,
but the magistrate forbad our holding one;
so that the landlord would not consent to any more meetings in his house;
yet about thirty persons went in to George Dillwyn`'s room, that he hired of the landlord;
where the Lord owned us in a remarkable manner, to the tendering of all our hearts.
Near the close of the meeting, an officer came from the magistrate,
who stayed a short time.
When our meeting closed, we found the landlord and his wife in a very ill humor,
and the officer with them.
We informed him of the matter, and took the blame to ourselves.
The officer went with us to our lodgings,
and took one of our passports to the magistrate,
to show him that we were well recommended by a Minister of State in England;
after which he was satisfied; and though he had fined the landlord where the meeting was,
he recalled the fine, and matters were settled.

In the afternoon we had a very large meeting for this country,
of nearly one hundred people, at a friendly man`'s house,
where the Lord again owned us by his blessed Spirit, to the humbling of our minds.
Although it was thought the meeting was hurt for lack of a good interpreter, yet,
on the whole, I felt much refreshed.
In the evening came several to our lodgings,
where we labored according to ability received to our own comfort.

12th month 8th.--We had a meeting of conference with the most solid or concerned persons,
respecting holding a meeting there regularly,
and some matters connected with their proceedings in future, which ended well,
and they seemed replenished with the showers of love and mercy thus bestowed;
so we parted in near love.
That evening there came nearly one hundred to our Inn,
and filled our room (which was very large)
without any notice from us or expectation given.
Many of them were of the respectable class.
We had a very solid opportunity, which lasted nearly two hours.
The people remained very quiet; no opposition appeared;
after which we took a solemn and affectionate leave of each other.
George Dillwyn and wife believed it right for them to
abide with these tender people a little longer.
Here I first saw my way open to leave Germany and go to Holland.
We proceeded on our journey, but the way being bad and our postillion careless,
(as they generally are),
when it was about dark he overset our wagon one mile from the town.
Here I met with the extension of Divine regard, in being preserved,
so that my bones were not broken,
though I at first thought my shoulder was broken or was out of joint,
as I nearly fainted; but after recovering found it was only bruised.
William Farrer and Benjamin Johnson were much bruised, and bled freely from their wounds.
William Savery escaped unhurt.
We felt tried, both as to body and mind, yet our faith did not fail;
for which favor my soul magnified the Lord.
We got to a very good Inn, where we obtained what was suitable; and,
after washing our bruises, retired to bed,
and the next morning proceeded on our journey to Minden,
where we arrived about eight o`'clock at night, much wearied,
having had a hard day`'s travel, in much danger, as the snow was on the ground.
It was difficult to keep out of the deep ruts.
We went where we had before met with civil treatment,
but could get little refreshment that night, as it was late when we reached Minden.

1796, 12th month 8th.--We stirred but little, being much fatigued.
Under my many trials, I feel something of the Divine presence to be with me,
and it bears me up through them.
Oh my soul, bless the Lord at all times, and praise his holy name forever;
for he alone can be trusted and relied upon:
He has carried me through the deep waters of many afflictions,
and hitherto has not failed in the hour of distress.

9th.--We had a meeting in the evening, attended by about thirteen sober people,
and the opportunity appeared to be owned by the Great Head of the Church.
Great is the mystery of the Gospel: Christ puts forth his servants and goes before them.
I felt in the foregoing meeting the necessity of waiting, in much inward retirement,
to feel the mind and will of the Great Shepherd of Israel.

10th.--This has been a very trying day to me;
though in the morning I felt the Lord to be nearer than usual,
and much sweetness covered my mind.
I then thought this is a morsel to strengthen me against a trial near at hand,
and which came accordingly, and was of a nature very proving.
Yet, as at many other times, I was carried through,
and hope to attain a greater share of patience than at times I fear I possess,
as it ought to shine in a true Gospel minister.
We have had the company this evening of several religious people,
who seem journeying towards a resting habitation.
We had some conversation with them, which seemed to be well accepted,
and we found a door open to propose a meeting to be held,
as a person offered us a convenient room.
The people seem more open to us than when here before.
Being first-day, we attended the little meeting,
usually held by a small number who professed with us, and who appeared to have grown,
both in weight and number, since we were here last.
I felt it my place to be silent, though my fellow-laborer had good service.

That afternoon we attended the public meeting before proposed,
where about two hundred people attended, who behaved quietly during the time of meeting;
and I thought the service was suitable and well accepted,
and the power of truth prevailed over all, to the humbling of our hearts.
Praise be ascribed forever to the Lord`'s holy name, who alone is worthy.

Not feeling our minds quite easy to leave Minden,
we spent part of a day in writing and in visiting some families,
in which service we felt our minds peaceful.
One of the families were people of note in the world on several accounts,
as in the administration of justice, and as one of the King`'s Council.
This man had been formerly visited by Sarah Grubb,
and then was in a tender state of mind, but had since gone much from his first love;
but I felt myself drawn in Gospel love to request an interview with him and his family,
which he readily granted.
It seemed to be a tendering season: he said he had not words to express his satisfaction;
his heart seemed much opened, and full of tenderness towards us.
He invited us to take dinner with him,
and sent us several presents before leaving the city.

In the evening of 12th month 13th, we had a meeting, where attended about forty persons.
The Lord favored us with a sweet opportunity, which was our last there.
Before I close this day`'s exercise,
I may mention that we made a visit to the High Priest, (as he is called,
being the head of the Jewish order in the city),
occasioned by a report circulated by him injurious to
the holy cause in which we were engaged.
He appeared much confused, and gave us reason to believe it had originated with him.
He informed us we could hold no more public meetings, that it was contrary to the laws.
We were convinced that he wished us gone, and we left him,
after laying the weight on himself.
We proceeded towards Holland, and traveling about thirty-six miles, lodged at a good Inn.

12th month 14th.--Proceeded to Osnaburgh, belonging to the Electorate of Hanover.
A friendly man met us at the Inn door, inquiring whether we were from England or America.
He proposed a meeting on the evening of our arrival,
but we were unable to procure a house.
Next day, we dined at the public table at the Inn; where,
as is the custom in many parts of Germany, a band of music attended, which,
however agreeable to some, was quite the contrary to me.
There dined with us two Romish priests and an abbess,
who appeared by her actions to unite with the general conduct.
She was a large woman, of hard countenance;
and although her life by her profession was spent in devotion and acts of charity,
yet I thought I saw little of that life which truly dignifies.
This evening we had a very small meeting, though to some satisfaction.
We prepared to leave next morning.
Osnaburgh contains about ten thousand inhabitants.
The city is very irregularly laid out, but there are many large buildings,
and it appears full of business.
The people were friendly, as in other places; but are divided as to religion.

12th month 17th.--We traveled about thirty miles to Rheine,
in the Bishop of Munster`'s territory.
Here we lodged at a Catholic Inn, and were well entertained.
The inhabitants are mostly Catholics.
We saw them going to their worship on first-day, with crosses hung about their necks,
and other marks of the Romish religion.

12th month 18th.--We traveled about eighteen miles to a town called Bentheim,
where the people are mostly Calvinists,
and appear to be better informed than in many other parts of Germany.
We have had some friendly conversation with our landlord and his family,
who seemed very much of our way of thinking.
This town is well built; there is a castle on a high hill which overlooks the town,
but seems to have stood long, and is now on the decay.
There are many of those ancient piles in Germany,
which now look as though they had forgotten their founders, and were by them forgotten;
both having lost their former dignity, and are going fast down to the dust,
from which they were taken.
We proceeded towards Amsterdam, about twenty-one miles, to Selden,
one of the most beautiful situations we had seen in our travels.
This town appears to have felt the effect of the war:
some of the buildings are large and substantial.
We crossed a bridge of boats, and passed through several fine towns.
On our way we saw one of the seats of the late Stadtholder.
I thought I had never seen a more beautiful place.
Nature and art seemed to have united in beautifying it.
The country around, the fine buildings, and the land,
seemed to exceed anything we had before seen.
We soon reached Amsterdam;
and in the afternoon went to see our ancient friend John Vanderwerf:
he received us with much kindness, as he had long expected us.
Here I felt my mind easy, and it seemed as though I was nearer my own habitation,
and a great weight removed from my mind.

12th month 24th.--Rested to recruit a little; but finding no letters here,
either from my friends in England or America, was somewhat trying to us;
yet in remembering I had taken my solemn leave
of all my near connections before I left home,
and committed them to the care and keeping of Him "`who only has immortality,
dwelling in the light,`" I felt easy.

25th.--Being first-day, we had two meetings, to a good degree of satisfaction;
though the weather being cold made it uncomfortable for the people to sit,
as they have no fires in their meeting-houses; and from several passing in and out,
they were not as quiet as we could have wished.
Not feeling relieved, we had another meeting on the 26th,
which I thought the most favored; several present seemed much tendered,
and the meeting parted, I trust under a covering of Divine love.
Our ancient friend John Vanderwerf has been as yet our interpreter.
We have spent most part of this week in writing to our friends.

1797, 1st month 1st.--Being first-day, we had again two meetings, to some satisfaction.
Though the present race of Friends are pretty much run out,
yet there seems some ground to hope the candle will not go quite out.
There are some who seem looking towards Friends in this city.
I found a young man,
whose father had disowned him on account of his religious principles; he seemed tender,
and often lamented the great lack of a father in the church.
This city is very large, containing about three hundred thousand inhabitants,
mostly Calvinists.
Here also are many Jews, a great part of whom seem to be poor.
They appear in all parts of Europe to experience, and to feel to be true,
what Moses told them, "`That if they did not keep the law of their God,
and walk in his covenant, they should be the tail and not the head,
they should go bowed down always.`"
Our opportunities here have not been extensive for lack of an interpreter,
though I thought I felt as much love towards these people us any I had met with.

1st month 11th.--Being first-day, we had two more meetings, to good satisfaction;
the people behaved very well; and we parted in much nearness of spirit.
9th.--We spent this day in finishing our letters, and prepared to leave this city.
In the evening came two young men, one of them from Manchester,
that had been convinced of Friends`' principles.
We had some conversation with them, and parted in much love.
10th.--We took leave of our friend John Vanderwerf and his son in near love,
and went to a very beautiful city called Haarlem, about ten miles from Amsterdam.
To describe the country of Holland is beyond what I can attempt or pretend to do,
as it exceeds, for improvement and beauty, any part I have seen in Europe.
We passed on about twenty-two miles, to the city of Leyden,
which appeared to be no great place of trade, but very beautiful for situation,
and much famed as the seat of learning.
The people seem, as in other cities, friendly towards us, as far as we could discover.
It contains, by information, about seventy thousand inhabitants, is very clean and quiet,
and the people appear to be very moderate in their dress and very neat.
I felt much love towards them,
though I had not any conversation with them on religious subjects.
We stayed a short time, and proceeded to the Hague, about twelve miles,
and put up at a very good Inn.

1st month 11th.--We visited the American Minister, John Quincy Adams, from Boston,
who received us very kindly, and appeared disposed to do anything for us he could,
in the line of his appointment.
We were desirous that William Farrer should have a line
from some one in power but as he was an Englishman,
we could not obtain any toleration from him for William Farrer to go to France:
he recommended us to the French Minister, and sent his servant to show us where he lived.
When on our way I was conducted into the place where the National Convention sat.
About two hundred were present, who appeared in great state,
some of them with their hats on.
They required ours to be taken off, which we refused, and after a short time withdrew.
Not finding the French Minister at his house,
we were conducted by our guide to see the gardens and houses
or palaces of the late Stadtholder`'s wife and daughters,
which indeed were very beautiful, and are now occupied by the French Ministers.
On viewing these works and buildings,
I was led to consider the uncertainty of all human grandeur and acquisitions;
and with the King of Israel to say, "`Vanity of vanities, all is vanity.`"
True it is when our hearts are set upon earthly things, however flattering the prospects.
The French Minister received us very kindly, and served us as far as was in his power;
but said he could do nothing for an Englishman,
though he thought he might pass without much danger, being in company with us.
He appeared to be of an open disposition,
and expressed a regard for us as a religious society.

This city is said by some to be the most beautiful of any in Europe;
and as we passed through, we thought we had not seen anything to equal it.
The canals are many of them wide, and rows of large beautiful trees, all trained alike,
on each side Some streets are so wide as to have two paved ways for carriages;
and between them, a fine walk for foot people;
so that here are fine rows of trees that make it look
like a city rising on the edge of a large wood.
There are, by information, about fifty thousand inhabitants,
and they generally appear very respectable.
It is the seat of government.
There are none of our society in it,
nor did we hear of any religious people in the place,
so that we saw no door open for religious labor.

1797, 1st month 12th.--Left the Hague, and proceeded about twelve miles to Rotterdam.
We passed through several fine towns and villages, a most pleasing country,
and arrived about two o`'clock.
Here I found a young man from America, of the name of White, a native of Pittsfield,
thirty miles east of the North river.
He seemed to be a kind-hearted young man, who said he thought our business very laudable,
to seek the poor and afflicted; as I had informed him that we had Friends in France,
and were going to seek after them.
The mental exercise of this day has been after more patience,
and a disposition to make the best of whatever happens; to hope all things,
and believe all things, so far as to take, in the most favorable light,
what we meet with, which is our duty, and as such must tend to our happiness.
I am also concerned that I may see with clearness what will be right to do next,
in the line of our service.

13th.--We spent in visiting some English families,
and found many who appeared glad to see us, particularly a man named Shadrach Jones, who,
with his wife, showed us much kindness.
Cornelius Lloyd, a descendant of Friends, and a widow of the name of Tafield,
with her son-in-law, were also kind to us.
Many of the inhabitants speak English, as many English and Scotch have settled here.
The navigation is carried on with more ease than in any city we have met with in Holland;
as ships of burden come up into the heart of the city by their canals.
The river, the Meuse, is navigable above twenty miles above the town,
and is banked off from the town, as is generally the case in Holland.
The banks are very large and expensive, but the people appear very rich,
and their city beautiful and clean.
We found the people generally civil.

1st month 15th.--First-day, we had two meetings,
in the meeting-house belonging to Friends in London,
as all the Friends are dead or removed that formerly occupied it.
The first was not large,
but we were favored to feel that the Shepherd of Israel was near,
and the meeting concluded under a sweet covering.
In the afternoon the number was much increased, and the power of truth arose,
to the tendering of many minds.
Our acquaintance having increased,
we felt easy to propose a meeting for second-day evening.
When the people had gathered, many could not get in,
and the Master of our assemblies favored us with a refreshing season.
The next evening, being the 17th, we had a meeting in the Episcopal Church,
where the people behaved well,
and the Lord was pleased to favor us with a degree of his life-giving presence,
and I left it much comforted.
I had been growing poorly for two days, and could not walk to the meeting,
being so weak and unwell.
My disorder increased so as to confine me to bed most of a day, attended with fever,
and I could take no food with comfort.
Many have been my secret exercises, not only from being in a foreign land,
but without any that professed with me as to religion, except my companions;
and confined to an Inn among Roman Catholics,
who knew not anything of me or my religious character; and no female nurse to call upon.
But this was made more comfortable than I could expect,
as I often felt some secret springs of Divine love opened, that gave me comfort;
though I could not see how it might turn with me.
The families before mentioned were very kind and attentive to me,
and brought several things that they had prepared after the English fashion,
deeming that most agreeable.

1st month 20th.--I am rather better, and hope springs up that I shall be out again soon.

21st.--I still continue to increase in strength,
and my physician thinks I shall get out in a few days.
I still find much lack of patience and resignation to the Divine will.

29th.--I have attended several meetings, which gave me much relief,
and on the 30th and 31st visited a number of my friends,
and took leave of them in much brotherly love and affection.

2nd month 1st.--Left Rotterdam and proceeded in a passage-boat towards Flanders.
There appears to be a number of tender people in Rotterdam,
who seem as a seed hid under many of the cares and concerns of this world.
My going on my present journey has been attended with many exercises,
as I have parted with my kind companion Willam Farrer,
who has borne me company nearly sixteen months;
in which time we have traveled through many exercises, and as I have often been unwell,
he has attended me with care and affection.
At Rotterdam I received a number of letters from my family and friends in America,
which afforded me much comfort to find they were all in health,
and my family blessed with the continued care of Infinite Goodness,
and desires prevailing with them to be found in the way of well-doing.
This has been a great comfort to me in my lonely state,
while I am as a pilgrim in a strange land.
The people here, as in other parts of Holland, are very industrious and careful;
they appear to live comfortably, and many of them are wealthy.
They are a people not inclined to much intimacy with strangers,
as they seem happy in their own way, and among themselves.

2nd month 4th.--I have had many secret exercises which have been of a most trying nature,
on entering a land whose language I was altogether a stranger unto,
and whose laws and customs were also strange; there was war also,
and a probability of its increasing.
All these circumstances made my way look more gloomy,
and at times tended to weaken my faith with respect to our getting along;
yet as I apprehended I should not feel easy without making a trial, I gave up to it,
and what may be the event is uncertain.
I have several times conversed with the passengers, who are mostly from Flanders,
or on its borders, and who speak Low Dutch, or a mixture of Dutch and French.
They appeared kind towards us, and seemed willing to help us forward.
Our way of traveling being by water, at this time of the year,
it was very trying to my weak constitution; being in the cabin without fire,
and much damp and foggy weather;
but He that commands the winds and seas has hitherto helped;
in whom alone I humbly trust and depend for strength of body and of mind,
and to whom be the glory and praise forevermore.

2nd month 5th.--We landed at Sluys,
a town about one hundred and thirty miles from Rotterdam, formerly belonging to Holland,
in Flanders; but now under the direction of the French Republic.
This town withstood the French army more than twenty days,
but was finally obliged to submit.
During the siege it suffered much; many of its inhabitants were killed,
and many of the buildings much defaced by the bombs, cannon, etc.

After being landed,
I felt desirous to get where I could rest and nurse myself until I got better;
and being conducted to an Inn, found a very obliging landlord and his wife,
and everything very comfortable and convenient, which tended very much to my comfort.
Yet exercises of mind remained, being among a strange people,
and where a law existed that required every person, both male and female,
to wear a cockade in their hats, as a mark of unity with the Government,
and the war then carrying on between several of the powers of Europe;
but knowing that we had a testimony against war, we could not do this,
which made our way look dark; as the people told us we were in danger from the mob,
and of severe imprisonment if we did not comply;
and also that it would be impossible to proceed unless
we would comply with the laws of the country.
But faith in Him that can and does overrule the nations,
and makes a way beyond what we can reasonably expect, sprang up.

There appears a great difference between this place and Holland,
both as to the manners of the people and their buildings;
and they seem to be less cleanly than the Hollanders.
The religion here is that of the Roman Catholic.
I understood there were no Protestants here.
After spending two days, we set off for Bruges, twelve English miles, where we lodged,
and found the people very civil and kind to us,
making no inquiry about our not conforming to their laws respecting our hats.
On our way we stopped at a poor Inn for our coachman to feed his horses,
where a very good-looking young man came to the coach where we were sitting,
and spoke to us in English, and informed us that he knew our friends at Dunkirk,
and that he was an agent from some part of America.
He invited us into the house.
We informed him what we had heard respecting our hats: he told us a law had existed,
but that they had exempted our Society, and that we might proceed without molestation.
He openly told the people then present that we were not under that law,
and offered us all the service that lay in his power: informing us where he resided,
and to make his house a home.

We reached Dunkirk about five o`'clock, and soon found our friend Benjamin Hussey,
who received us very kindly; his wife being a kind friend and good nurse,
I soon felt altered for the better.
I took lodgings with these kind friends; but my companions,
William Savery and Benjamin Johnson, went to the widow Gardner`'s,
a Friend from Nantucket, where they were very kindly received.
We rested here two days, in which time William Savery was taken ill with a cold.

2nd month 17th.--They left Dunkirk for Paris, where, as William Savery relates,
they had an interview with Thomas Paine, to little satisfaction.
They had to lament over the vice and infidelity which abounds in that city,
and found little opening for religious service.
From Paris they reached Fontainbleau, 2nd month 25th, and Lyons on 3rd month 6th.

David Sands remarks:
As we entered Lyons we saw the ruins of many large buildings on the side of the river,
and the rocks seem almost perpendicular;
for more than a mile there is but little room for building on level ground;
and where it is in the power of art to form a place to build a house, there is one;
so that in some parts of the city they appear to be one above another,
until they reach the top of the mountain.
The houses on the level parts of the city are
most of them from three to six stories high,
and very thickly crowded, so that there is but little room left for passengers.
This city is called the second in France,
and suffered much in the dispute with the Republicans, during a siege of several weeks,
before they submitted to the general government;
but now they appeared very quiet and in business; so that things among themselves are,
I hope, growing more comfortable.
It contains about one hundred and forty thousand inhabitants;
its situation is very wild and beautiful; they appear to be a wealthy people.
We tarried here one night and part of two days.

3rd month 8th.--We took our passage down the river, in a flat kind of batteau or shallop,
with many other passengers.
At night we landed at a village, where we lodged, this being their custom,
as the river is difficult to navigate, winding through among mountains:
there are many shoals, on which our shallop often struck.
We continued to pursue our course through a very mountainous country,
though mostly under cultivation;
and to a stranger it looks almost impossible for human
beings to climb and work on places nearly perpendicular.
Many families build a kind of house or cave where they dwell,
in the side of the mountain, in their vineyards.
In every small opening, where the mountain does not reach the bank of the river,
is a village.
One night we lodged in Montlemart, a very ancient city,
the wall of which was said to have been built by Julius Caesar.
The manner of building appeared very plain and strong.
There was not much appearance of business, and the people being poor,
we found much difficulty in obtaining lodging among them.

The next day we passed within a few miles of the Alps,
where everything wore the appearance of the depth of winter.
We met with a man of note in the world,
who told me he had once attempted to ascend the highest of them; he traveled five days,
though still he found himself far from the top,
and so became discouraged from further attempt to gratify his curiosity,
in seeing that line of the Alps whose tops were never known to be clear of snow.
On the third day, we left our shallop, as the wind blew too hard for us to continue,
and traveled about twelve miles, to a very ancient city called Pontesprit,
in a carriage belonging to the person before mentioned,
who had been very kind to me in particular.
He was a man of good education and manners, and seemed much interested in our favor,
and said he owned our principles and approved them,
and that he had some thoughts of going to America.
He informed me that this city had stood for more than two thousand years,
and was built by the Romans, and a bridge of stone which we crossed,
near forty feet high, of great length, was built by Julius Caesar.
This city is strongly walled,
with many other indications of having been held in high estimation,
but is now much neglected.
The houses are high, and so crowded together,
that a common width carriage could not pass through between them.
The people looked at us with a kind of pleasing astonishment,
and some spoke as we passed them.
We intended to have gone farther to lodge,
but were informed it was very dangerous traveling at night on account of robbers,
who frequently both robbed and murdered people.
We concluded to tarry there that night, and had very comfortable entertainment.
Next morning we set forward with our friend, and went to a city called Bagniol,
where we tarried a day and night.
In this place, several people of some note in the world visited us,
with whom we had some friendly conversation, and to whom we gave books,
which they appeared to receive very gladly.
Here we parted with our friend who had brought us thus far,
after having given him some books, which he received very kindly.

We then set out for Nismes, in a small cart, which was very fatiguing,
as it traveled slow, and was crowded with passengers.
Most of the day was dull and rainy.
