== Chapter 11

[.chapter-synopsis]
* Attends the Yearly Meeting
* Quarterly Meetings at Banbury
* Buckingham
* Reflections on Visit to Jordan`'s Burial Ground
* Woodstock
* Letter from Ebenezer Cresson
* Travels in Wales
* Arrival at Waterford
* At Clonmell
* Letter from James Bringhurst
* Visits Cork--Limerick

Before resuming the Journal kept by David Sands,
of his labors and services in England and Ireland, it may be proper to remark,
that for the last twelve months he had been subject to
frequent threatenings of serious interruptions to his health,
which involved him at times in deep trial and anxiety,
especially when traveling amongst people of a strange language; yet, during that journey,
he was generally soon recruited again.
It is highly probable that his long and hard travels in
the newly settled parts of his native land,
where proper accommodation was scarcely to be had,
and his deep trials by shipwreck and at sea,
which were both of a bodily and mental character, had impaired his constitution,
and affected his nervous system.
Hence it will be found that, in his subsequent travels,
there were frequent interruptions to his progress,
having sometimes to lay up for several weeks together.
We shall now proceed with his own account:

1797+++.+++ The yearly meeting coming on, I was glad of an opportunity to rest a few days.
The select meeting began the 20th of 5th month.
This was a very solemn meeting,
and I have sometimes observed that the yearly meeting throughout has been
very much of a similar character as the select meeting has previously been,
and I have sometimes called it a "`forerunner;`" as indeed this was,
in the opinion of Friends, a very favored one.
Many matters were brought forward, and the state of Society gone into very weightily;
and Friends appeared to be preserved under a humbling sense of
their own insufficiency to transact the affairs of the church,
but as they were favored by Him who has hitherto
been the stay and strength of his people.
My health was such as to enable me to attend all the sittings of the meeting,
which continued, by adjournments, until the 30th of the 5th month.
The business being over, Friends parted under a sense of Divine favor.
I continued in and about London, visiting my friends and the different meetings,
until the 23rd of 6th month, when I felt easy to move towards Bristol; my kind host,
Joseph Smith, bearing me company.

On the 25th, had a meeting in Oxford, a place long esteemed as the seat of learning.
Here are a few Friends, but they do not hold a meeting.
From this city I proceeded to Banbury,
where the quarterly meeting was held for the counties of Berks and Oxford,
which was a favored meeting in many respects.
I was much spent when it was over, but soon recovered,
so as to attend the quarterly meeting at Buckingham, which was also a favored one.
After the close of this meeting, my friend Joseph Smith left me,
and John Lury became my companion.

6th month 30th.--I had a meeting at Jordan`'s;
on my way I called to see the place where Thomas Ellwood had lived, called Hunger-hill.
The house appears to have been but poor in its best day, and is now much decayed.
It was long used for the monthly meeting, or one room of it,
which now serves as a kitchen.
Taken together with the thought of the worthies who used to attend meetings here,
it was a lesson of instruction.
I was ready to say, "`How is the gold changed!`"
Though there is a very convenient meeting-house at Jordan`'s,
and a beautiful burying-ground,
with stable and walks in a small wood belonging to Friends,
there are now but two ancient men, who attend to keep up the meeting.
Notice being given, many attended, and we had a meeting to some satisfaction;
but such places seemed to be but dry spots,
where Friends have been thriving as a society and are gone.
After meeting, I went to see the graveyard,
and one of the old men showed me where lay William Penn,
his two wives and eight of his children; Isaac Penington and wife,
Thomas Ellwood and wife, and several others of the most worthy of our Society,
who were useful men in carrying forward the Reformation.
This graveyard is kept in the neatest manner;
the graves are raised so as to be seen distinctly,
and most of them are known by the aged Friend.
I observed all whose names I have mentioned were in one row, very close to each other,
with many others who had been laborers in their day.
I thought there seemed to be something there more than I had ever seen or felt before,
in visiting the sepulchers of the worthies who were gone;
yet I was ready to look down and say,
is it possible that this little spot contains the mortal
remains of all those great men who once made the world wonder;
some of whose talents were rarely equalled,
and whose tongues were so capable of setting forth the
work and the way to obtain an immortal crown,
and the joys of it? But alas! so it is, and will be.
"`Man is of few days, and vanishes away with all his parts and powers.
After taking a view of these sods or spots of grass,
I returned to my kind friend Adey Bellamy`'s, at High Wycomb,
a place often mentioned by Thomas Ellwood,
where now live several Friends who hold meetings, and seem likely to grow.
I had some service here among several families.

On first-day morning, I was at a burial, to which many people came;
it was a time of favor, as was also a meeting held in the evening, at the same place.
From there I returned to High Wycomb, where I had a public meeting, to much satisfaction;
and had several opportunities among Friends, and was at the monthly meeting.
I attended a meeting appointed by Ann Alexander and her companion, held near Jordan`'s,
much to my own and their satisfaction.
Many persons attended, and much of the service fell on me.

From this place I again proceeded towards Bristol; stopped on my way at Oxford,
and had much comfort with the few Friends who live there.
I then went to see a large library erected by Dr. Ratcliff;
the building and books said to have cost forty thousand pounds,
which I thought very poorly laid out,
as most of the books seemed more for ornament than use.
I also visited All-Saints`' College, but saw little worthy of remark,
except having been treated civilly by the scholars and inhabitants.
We then proceeded towards Chipping Norton.
On our way we stopped at Woodstock, where is the seat of the Duke of Marlborough;
and where was the residence formerly of several of the kings;
but the building was pulled down before the present one was erected.
Here I was led to view the shortness of all human glory with a kind of astonishment,
as I looked back,
and remembered what I had read and heard relative to many who had lived at this place,
as all seems to be not only removed out of sight, but no marks of their feet left.

I visited Fair Rosamond`'s Spring; it still bears her name, and is very beautiful,
flowing from the side of a pretty hill; but her fine buildings,
and all her fond delights are no more, except a few shattered remains.
The delighted monarch, his cruel queen, and fair favorite, are all now laid in dust;
no more jars or disputes are heard amongst them.
A stone covered with moss, and sullied by time,
is perhaps all that remains for the traveler to look upon;
and even these have almost abandoned their charge,
as the persons who had the care seemed weary of relating who laid beneath.
Worn by time, they speak with a faltering voice,
so that it is difficult for the traveler to understand what they say.
The palace is very large, and beautifully surrounded by fine gardens and sheets of water.
It seemed very interesting to me,
while contemplating how many had walked there before me, who now were no more;
and I was brought by these considerations to reflect on my own situation; how,
in a short time, I also should be known among men no more,
by any part I should take in human concerns.

Next day I attended a meeting at Chipping Norton,
where I was favored to open some points of doctrine, to the satisfaction, I believe,
of some present not of our Society.

The following letter from his friend Ebenezer Cresson, of Portland, Maine,
was written about this time, and probably received soon after:

[.salutation]
Dear Friend--

Feeling, I trust, a degree of that uniting love which time, nor distance, sea or land,
cannot extinguish, to flow towards you, I seem willing to write you a few lines,
remembering that love is one of the most valuable things.
It is now about fourteen months since I have undertaken this pilgrim`'s life,
with our endeared friend John Wigham, (except for about six weeks),
in the course of which time we have been through some parts of New York Government,
and the greater part of New Jersey, Pennsylvania, and Delaware States;
some parts of Maryland and Virginia, South Carolina and Georgia.
We reached Newport in time to attend half the yearly meeting.
We have since been on the Island of Nantucket, and attended several meetings on the Main.
We are now accompanied by your old companion Joseph Wing,
on a long journey to the eastward, perhaps as far as Halifax.
I have need of the prayers of those who are favored to approach the Throne of Grace,
that I may, through all, be enabled to stand.
This is often my prayer, desiring to be preserved from asking any great things,
but only that preservation may be vouchsafed from falling,
on the right hand or on the left.

Dear friend, remember me; I have often remembered you with affectionate regard,
and I trust in sympathy, according to my small measure.
Oh! that Zion`'s borders may be increased; her posts and her cords strengthened;
that she may more and more arise and shine in her ancient splendor,
and put on strength in the name of the Lord.
It now looks as though a considerable shaking was coming over Christendom, so called;
and oh! that we may be able to endure the turning and the overturning;
that that which cannot be shaken may remain,
being founded on that immutable and eternal Rock of ages,
against which the very gates of hell cannot prevail.
Your wife and son attended the New York yearly meeting, and were well.
You have perhaps heard of the sudden and affecting removal of Mary Gray,
by a fall out of a chaise; not being sensible after it.
What an awful instance of the uncertainty of men`'s continuance in these poor tabernacles,
and an alarming call to others, "`Be you also ready.`"
But how often does it sorrowfully happen that such
impressions are as characters written in the sand,
which are obliterated by a blast of wind!
The accounts from Ireland look increasingly awful.
How sorrowful is it that nothing but scourges will keep mankind on any dutiful
terms! and it is cause of rejoicing when even these have a proper effect.
May they be more and more sanctified.
The prospect looks gloomy also with regard to England;
and what shall be the fate of this country, in the bustle, is behind the curtain.
Dear John Wigham desires his love to you.--Farewell;
and may we all fare well in the best sense, is my ardent desire.

[.signed-section-signature]
Ebenezer Cresson

[.signed-section-context-close]
Portland, Maine, 7th month 10th, 1797.

7th month 16th, 1797.--Went to Burford and put up with Thomas Minchin,
whose wife is in the ministry, and appears to be a very valuable minister.
From this place I attended many meetings that lay not far distant;
in all which I was favored to experience some help, so that I was enabled to get through,
to a good degree of satisfaction; and on the 27th I reached Bristol,
and was kindly received at the house of my dear friend John Lury,
where I tarried until the 20th of 8th month,
visiting meetings and families in Bristol and thereabouts.
There are many Friends in this city, very respectable, and many very promising youth.
I felt my mind much attached to them,
and thought I had not felt a greater nearness to my friends since being in this land;
and I believe they received me with much love,
especially my much-loved friend James Harford and family.

8th month 20th.--Left Bristol and traveled twenty-four miles,
and lodged at a town called Usk in Wales.
The following day, traveled about fifty miles through a very mountainous country.
We passed many towns, but they, with the inhabitants,
appeared far inferior to the towns and people of England.
The inhabitants are mostly in low circumstances.
We lodged at Llandovery, where the half year`'s meeting was held for North and South Wales.
It continued three days.
The sittings of this meeting were attended with a good degree of satisfaction,
and Friends parted in much nearness of spirit.
Here I parted with my much esteemed friends John Lury and his daughter Lydia,
who had been very affectionate to me;
and joined in company with my much-loved friends James
Harford and his daughters Mary and Elizabeth,
and his son John.
The company of these dear friends made my way look more
pleasant than otherwise it would have done.

On the 25th, left Llandovery and proceeded to Llangadoch,
where a meeting was held in a barn; and in the evening, attended another at Llandillo,
where we lodged.

26th.--Went to Swansea.
27th.--Attended a meeting at Friends`' Meeting-house,
and in the evening had a meeting in the Town Hall.
Swansea appears to have been a place where was a considerable number of Friends,
but now they are very much reduced.
From this place we went to Neath, a market-town distant eight miles,
to the house of our kind friend Evan Rees, who, with his family,
are the only Friends in this place.
Here we had one public meeting, and attended their fifth-day meeting;
and after taking an affectionate leave, set out for Swansea,
and arrived on the 31st. Next day, called on W. Padley and had a public meeting.

9th month 3rd, being the first day of the week, we went to Friends`' morning meeting,
and to an appointed one in the evening.
Left Swansea on the 6th, and in the evening arrived at Carmarthen, a seaport town,
twenty-seven miles from Swansea, where once was a considerable number of Friends.
On the 7th we had a public meeting; and proceeded to Haverford West,
and attended Friends`' meeting; and in the evening, an appointed meeting.
After visiting some families, attended the week-day meeting in the morning;
and in the evening, another appointed one.

9th month 14th.--Had a meeting at New Milford,
and returned in the afternoon to Haverford West;
and having visited the few families of Friends and a few friendly people,
we went to Milford,
where we had several meetings amongst Friends and other tender people,
to a good degree of satisfaction.
9th month 25th.--I took leave of my dear friend James Harford and children,
who had been very kind to me, and went on board a packet bound to Waterford, in Ireland,
where we arrived next day, about five p.m. Our passage was unpleasant,
through the roughness of the weather; but I suffered little on that account,
my exercises being of another kind, which reduced me very much,
yet I was graciously preserved above despair.
After we landed, I went with my beloved friend, Abraham Jackson,
to the city of Waterford, and took lodging with Thomas White,
who received us very kindly.
The next day, attended their meeting,
where were gathered a large body of plain-looking Friends.
I felt quite shut up in the morning meeting, and was very low in the afternoon,
yet had a few words to offer, and proposed a meeting to be held in the evening.
There was assembled a large body of respectable people,
and I thought that some help was experienced;
so that the meeting was in some measure comfortable.
I attended their weekday meeting, where also was gathered a large number of people,
and I had some labor amongst them; yet the power of truth did not seem to rise high.
Since this time, being unwell, I have traveled but little,
except to visit a few families, and attend their meetings, as they came in course.
As I seem bound to remain here until the quarterly meeting,
I have continued to visit families, though but few in a day, as my health is poor.

10th month 14th.--The meeting for ministers and elders began, which I attended,
and found some relief in opening my mind to them respecting some matters,
especially relating to ministers and elders dwelling in unity,
in order to the maintaining a harmonious labor.
The quarterly meeting continued five days, as there were many matters brought before it,
which required the deep and solid attention of Friends.
The business appeared to be conducted in a good degree of brotherly love,
and concluded under a solemn weight,
that had attended more or less through the several sittings thereof.
I have had several satisfactory opportunities, though in general I felt very low,
and mostly sat in silence in their meetings for worship,
and seemed to feel myself the most like a pilgrim of any time since I left America.

The situation of the people here seems very distressing,
as the greater part appear pinched for both food and raiment;
and what they call comfortable living seems little besides potatoes and salt,
with some milk, and sometimes a meal of fish or flesh.
The beggars are very numerous,
and seem to be of the most distressed of that sort of people that I have met with.
I often found myself straitened in eating more than I thought nature required,
and that of the common kind of food.
I left Waterford and went to a bathing place (Tramore) that had been
recommended by my kind friend and physician Joseph Hoyland,
of Waterford.
There I spent several days, in company with Mary Dudley and her husband,
the latter having come here for the purpose of bathing also.
We had a meeting amongst the people of the town, to some satisfaction;
Mary Dudley being a very valuable minister, and had, I thought,
good service in this meeting.

After having made trial of bathing, and finding myself a little strengthened,
I left my near friends and proceeded to Clonmel, and took lodgings with Isaac Jacob,
who keeps the school that was established by Robert and Sarah Grubb.
They left much of their property for the support of the school; an example for others,
to look forward to the welfare of another generation.
I seemed much shut up in several meetings, not finding it my place to open my mouth.
After spending a little time here with Friends,
I went to the place where lived my companion, Abraham Jackson`'s father,
with whom I lodged; who, with his family, were very kind.
He had lost his eyesight, but appeared to bear his loss with great patience.
At this place I found my mind much relieved, and my body strengthened;
and after spending a few days, I returned to Clonmel, and attended a monthly meeting,
and one public meeting, to which came many of the inhabitants;
and although the power of truth did not rise as high as in some meetings,
yet I felt relieved by it, and returned again to A. Jackson`'s, where,
after tarrying a few days, and visiting some families, I went to Youghall,
for the purpose of bathing, but found it would not do for me,
as the season was so far advanced.

At this place I found myself much tried with my former complaints,
but was enabled to attend meetings as they came in course;
but passed them mostly in silence, and with my mind often much exercised.
Mary Dudley was here with her husband, for the purpose of bathing, he being very unwell.
She was sometimes favored with strength to communicate something to the people:
her gift being suitable to administer to those of other societies.
I lodged, while here, with William Harvey, whose kindness was very great,
with that of his children, he having lost his wife some time before.
I tarried here about two weeks, and visited most of the families of Friends,
and some of other societies, in company with Mary Dudley,
and had several appointed meetings,
which I believe were satisfactory to Friends and others.
Here my dear friend John Lury, from Bristol, came to join me as a companion,
in visiting the nation of Ireland.
While at this place I had often to look back on the many
trials I have had to pass through in the course of my life;
and more especially since I joined the Society of Friends,
and have been called to the work of the ministry; and on taking a retrospective view,
I am ready to say, how little has been my progress!
What need to double my diligence in advancing life!
I have read much, and traveled more than most others,
yet have advanced nothing to what I apprehend many others have,
that have been called long after me.
A sense of my own infirmities has of late much impressed my mind;
but I hope that a greater improvement will be made,
so that when the time of my dissolution comes, I may be found ready.
Youghall has a number of promising young people, to whom I felt much nearness.
This place appears to have been settled by people from England and Wales;
and they having retained something of their forefathers`' customs,
made it more agreeable to me than in some other places.

11th month 27th.--I left Youghall and came to Cork; distance thirty-two miles.
The country is more pleasant than many others; being better cultivated,
and the people appear more comfortable.
I have been at four meetings.
There appears to be a large body of Friends;
but I have been ready to conclude there has not
been that faithfulness that ought to have been;
as they appear to have been a highly favored people.
In this city lived Samuel Neale, who had once visited America,
and appeared to have been a chosen instrument, and died a few years since.

I received here several letters from my family, expressive of their health,
which has given me much comfort; not having heard from them for several months.
I have had several public meetings in and about Cork, and two at Kinsale,
a seaport town about twelve miles distant; and one at a town called Bandon,
also twelve miles distant; all which were to a good degree of satisfaction.

At Kinsale I visited the French prisoners, who complained much of the lack of provisions,
as they had lately had their allowances shortened.
Here I had a view of the fatal consequences of war,
as many of these poor prisoners seemed very ignorant as to knowing
why they engaged in a dispute with any nation or people.
Oh Lord! when will the time come that an end will be put to these things;
when the earth will enjoy her Sabbaths, and mankind become more as brethren!

Since being in this city I have been much afflicted with various complaints of body,
and much exercised in mind, having sat most of the meetings in silence.
This city lies very low, and is often overflowed by the rivers which pass through,
the principal of which is the river Lee.
I have visited many families of Friends here, to a good degree of satisfaction.
My esteemed friend Mary Dudley has been at most of the public meetings,
as a partner in the work, and her company has been very agreeable.
About this time,
David Sands was cheered by the receipt of the following valuable letter from his friend,
James Bringhurst, of Rhode Island:--

[.salutation]
My dear Friend, David Sands--

Under a deep feeling sense of that uniting love which extends over sea and land,
cementing together in spirit those who are desirous of becoming the
sincere followers of Christ into one bond of fellowship,
do I now desire to address you, my beloved friend;
and acknowledge the receipt of your very kind and acceptable letter,
dated at Dunkirk in the 2nd month last.
I was rejoiced to find you were favored to get from
place to place with some degree of satisfaction,
in these perilous times; and where you and your dear companion, William Savery,
had to travel, as at the risk of your lives, through much danger:
yet wherein I have not the least doubt that the never-failing
arm of Divine Sufficiency was at times experienced,
sustaining you through every difficulty, although there were some seasons of sore dismay.
Faith might sink to a low ebb, and you be scarcely able to perceive it.
Oh, how have I felt and sympathized with you,
and have greatly desired you might be yet farther strengthened
and abundantly qualified to go through it all,
in the heights and in the depths, to the honor of your Great Master,
and the abounding peace of your own minds.
How have I wished at times that I could in the least
degree become assistant in holding up your hands,
and in any manner help the work forward; I feel as if I should very gladly do it,
I well know there is great need of Aarons and Hurs in the present day.
But there are often too many hindering things suffered to take up our minds,
filling them with the cumbers and cares of the world,
and thereby preventing our truly and earnestly becoming such
fellow-helpers in promoting the spread of the glorious everlasting truth.

My dearly beloved friends, for such I can sincerely call you both;
I at this time feel much love towards you, as at many other times;
you being often in my mind in my lonely walks on the road, and through the fields,
where at times I take solitary steps,
thinking on the many dangers and various difficulties
many of my dear friends have to pass through;
and how many there are who, like Gallio of old,
"`care for none of these things,`" though I do believe it is not the case with all.
Impressions are made, and I hope lastingly so,
on some minds by the preaching of the Gospel,
in the demonstration of the Spirit and with power, pulling down and destroying in some,
the strongholds which sin has made; those high imaginations in which they were building;
bringing all down as under the cross,
in true subjection to that holy Spirit of Christ in them;, and thereby we see that,
after a thorough change is witnessed, and patience has had its perfect work,
such are sometimes mercifully raised again, and made as fellow-helpers in the good work;
and this proves a means of encouragement to those who have faithfully labored with them,
in seeing the fruits of their earnest endeavors so brought forward and blessed.
Thus it has proved in some very dark parts of this continent.
At West Harford, in Connecticut, there are now about twenty valuable Friends.
They hold their meetings for worship twice a-week at present,
in one of their dwelling-houses.
They are members of Oblong monthly meeting.
I have several times been to see them, and have sent them many Friends`' books:
many of the people of that State are very desirous of reading such publications.

On our way to Philadelphia, last fall,
my wife and I called and spent a day or two with them;
and as a strong testimony in their favor, one of the principal men in the Government,
Jeremiah Wadsworth, Senator in Congress, meeting with us soon after, in Newhaven,
said if he had known we were going to West Harford, when he saw us passing,
he would have come out there on first-day, to have spent the day with us.
He had been very desirous of being at one of their meetings; saying,
some of those people had been valuable men in their lives and conduct,
and were not worse now; but that others had been addicted to vices,
but were greatly reformed since they had joined with Friends.
One had been a deacon among the Presbyterians, who is now become a useful Friend.
One has his aged father living in his family,
who yet remains in the old bitter persecuting spirit.
I told him, when at the house,
that I had a hope that his valuable son`'s good
conduct would be a means of convincing him,
and of bringing him over to the same wise care for himself

I believe of late many have been shaken from their false rest and love of ease,
and that others will be, or at least I hope so; as a fresh visit of sickness,
called the yellow fever,
has been permitted to remove many of the inhabitants out of the world,
in many places this summer; as at Philadelphia, Baltimore, Norfolk, etc.:
and at Providence, and the town of Bristol, in this State,
the people have been greatly alarmed,
and some have been aroused to a sense of their duty.
But there is danger of these feelings too soon passing away, like the morning dew.
The wickedness in many places is become so great that it seems
as if good impressions could scarcely be lasting,
or fix deep in their minds; the people are so vain, light, and airy.
May these afflictive visitations be permitted to have their proper effect,
is my earnest desire.
Our great and kind Almighty Benefactor seems to be trying many
ways to bring the people to himself I firmly believe the
preaching of the everlasting Gospel has its part therein;
and whether the people will hear or not, the Lord`'s dedicated servants will be clear;
who are concerned to labor faithfully with them.
Often, very often, have I thought of that dearly-beloved Friend, the late Job Scott,
who laid down his life while abroad in the cause; whose memory is very dear to me.
Perhaps it may prove encouraging if I here insert a small part
of one of the many valuable letters I received from him,
a little before his close.

+++[+++After mentioning a Friend whom he thought near his end, he says,]
"`Oh! how often I think what a blessing it is to
have lived to advanced age in the life of truth;
to have almost weathered the storms, probations, and manifold temptations of this life,
and to be nearly arrived at that happy shore, and at that haven of eternal rest,
where Satan himself can no more assault us; where the wicked, who oft in life molest us,
must cease from troubling, and where the weary, tried, and often tribulated soul,
forever finds the holy rest.
Oh me! what unknown conflicts, perils, and snares have I yet to encounter.
Oh my God! my only helper, keep, I pray you, and preserve my soul; lest,
after all I have known of your love, your aid, your wonders in the deeps,
and the turnings of your mighty hand and arm, in many, yea in mighty waters,
I unhappily should let go my hold on you, and slide, as many have slidden before me,
from the line of your holy commandment.
But where, my dear friend, has the unexpected effusions of my heart transported me? Well,
forgive me if I deviate from the common law of letter writing.
I have my ebbings and flowings, and may be too much influenced by them;
but what shall I do with such tender emotions as I sometimes feel
when looking at the faithful who have almost run their race,
and are (as lively hope is representing it) nearly
arrived at the fruition of endless enjoyment.
My soul expands at times, under the lively sensations hence arising,
in a manner better felt than described.`"

Job Scott had his fears respecting himself, yet was enabled to hold out,
as a valiant in Israel, to the final close; and, beyond all doubt,
is now in that exalted state of bliss, enjoying the fruits of a life spent in toil,
for the benefit of others.
May you both be encouraged steadily to hold on your way,
and I feel no doubt but you will be abundantly blessed through all, to the end,
which will then crown you with glory unspeakable.
In deep-felt love I remain your sincere friend,

[.signed-section-signature]
James Bringhurst

[.signed-section-context-close]
Tiverton, Rhode Island, 10th month 25th, 1797.

12th month 21st.--My valued friend William Savery, with William Farrer,
having come to Cork, we had two public meetings, which were, I believe, satisfactory;
William Savery having most of the service:
and after having the company of each other a few days, we parted, he going to Youghall.

12th month 28th.--Parted with my much-esteemed friend Mary Dudley,
and many other friends in Cork, which was trying, as they were made very near to me;
but I believed that He whose tender mercies are over all his works,
would still be near to those who went, as well as to those that stayed.
My kind friend and host, Edward Hatton, accompanied me to Limerick,
about fifty-six Irish miles, where we arrived on the 30th.

In coming to this city we passed through many towns, and a fine tract of country,
but the people here live in a poor dirty style; their Inns are very indifferent,
and provisions but poorly dressed; but they were friendly towards us,
notwithstanding there were great commotions, and the spirit of war amongst them.

31st.--Being the first day of the week, I attended both meetings, in which I was silent;
but proposed a meeting in the evening, which was large, and I hope to some advantage,
as a very solemn calm seemed over it.
Spent the next day in visiting some families of Friends in the country.
On third-day, attended the meeting, in which I had a satisfactory season;
and in the evening had a public meeting, and many attended who appeared sober,
and the public labor appeared to be well accepted.
Not finding my own way open to leave this city,
I have spent this day in writing and visiting a few families.
There appears here a very goodly company of young Friends,
and there is a prospect of more joining them.
This city has been strongly fortified,
but was surrendered by the natives to Oliver Cromwell;
since which it has been under the British Government.
Part of the city is called English,
from the great number of English that are settled there.

1st month 4th, 1798.--I left Limerick and went to Birr, (now Parson`'s Town),
where a small number of Friends reside, who appear hopeful.
We reached it on the 5th, and have had three meetings, one in Friends`' meeting-house,
and two in the Town Hall, which were very large, and, I believe, satisfactory.

On the 8th, I left this town in much nearness of spirit, both towards Friends and others,
and went to Roscrea, and lodged at the house of John Pim, who received us kindly.
Next day we had two meetings, both to a degree of satisfaction.

1st month 10th.--Attended a meeting at Knock, to satisfaction;
after which we went to Montrath, and on the 11th had two meetings,
one principally with Friends, and the other more of other societies.
Here is a pretty large number of Friends.
I lodged with James Walpole, who, with his wife, was very kind,
and had a comfortable opportunity in his family.
I went to a meeting about six miles distant,
where was gathered a pretty large company of Friends and others,
which proved a favored time.
I had a little meeting in the evening, and one the next day, on our way to Mountmelick,
was very satisfactory.
The people who attended were mostly of other societies.
I have often admired that they should be so kindhearted as many of them appeared to be.
We reached Mountmelick about five o`'clock, and took lodging at John Gatchell`'s,
where lived our friend Mary Ridgway, who had visited America, but she was not at home.
We stayed there three days, and were at two meetings on first-day.
Next day visited some families, and one school;
and before we left we visited all the schools, (as there are a number),
to good satisfaction.
We went about fourteen miles to Rathangan, where Jane Watson resides,
who also has visited America.
