== Chapter 12

[.chapter-synopsis]
* Illness at Edinderry
* Arrival in Dublin
* Breaking out of the Rebellion
* Ravages of War
* Quarterly Meeting at Enniscorthy
* Letter to his Wife
* Conversion of a Military Officer

Having been unwell for some time, I did not attend their meeting at Rathangan.
Here I met with Mary Ridgway, who I was glad to see.
From hence I went to Edinderry, and attended their monthly meeting, which was small,
and things appeared low, though there are several who were active,
and the meeting for worship I thought was much favored.
Being unwell before, I now increased my complaint by taking cold,
so that I could move no further for the present;
and in a few days my disorder increased to such a
degree that I consented to call in a physician,
who, after several days`' trial,
could do nothing to my relief I became so reduced I could not help myself.
I then sent for Dr. Bell, of Dublin, who, after spending some time,
could not do much to my relief, though I considered him a man of judgment.
In about three weeks I recovered, so as to be carried in a canal boat to Dublin.
To give an account of my sufferings while in Edinderry is out of my power;
they having exceeded all that I ever met with before.
I was at the house of a kind Friend, whose name was Isaac Jackson;
his wife was also very kind, though unacquainted with me or my complaint.
The people here being generally of a hardy make, it was more difficult for me;
yet I met with kind sympathizing friends, and those who had a near feeling for me,
particularly a young woman, who attended me with much kindness and nearness of spirit;
and having cast myself on Him who is above all, I experienced His goodness,
in manifesting His care and regard towards me.

I reached Dublin, and was carried in a sedan to the house of Thomas Bewley,
where I continued near ten weeks, without getting out, except a few times to meeting,
having several attacks of my disorder.
The aforesaid Dr. Bell attended me through the whole of my illness.
My confinement was in every respect a most trying one,
it happening that while I was in Dublin the Rebellion broke out,
and the people of all descriptions and ranks were much divided,
and confusion and bloodshed appeared daily.
Many were taken up and found guilty, and suffered death;
and many others were put into prison, and some were sent on board of king`'s ships,
and others transported to penal settlements.
Many also fled to England and America for protection.
Thus new scenes were daily opening of a most melancholy nature,
so that I seemed like one plunged into sorrow for myself,
and on account of my fellow creatures; many painful circumstances taking place.

6th month 20th.--I left Dublin, in order to attend the Leinster quarterly meeting,
which was held on the 23rd, at Enniscorthy,
(several Friends accompanying us.) We stopped at Ballitore,
where we held a meeting on the 21st,
which place had been greatly distressed by a battle fought a few days before,
between the insurgents and the British army, in which many of the former fell.
At this place is kept a boarding-school for the tuition of Friends`' children,
formerly by Richard Shackleton, and now by his son Abraham.
From Ballitore we proceeded to Carlow, where we lodged.
A number of the slain having lain a few days before in the streets,
their blood was yet to be seen.
But Friends and their property were wonderfully preserved.
From there we passed to Enniscorthy, through a desolated country,
the towns and villages mostly burned.
When we arrived we were presented with a view of all the horrors of war;
the houses had been set on fire the day before, the inhabitants mostly having fled,
and those who remained were without the common necessaries of life.
On our arrival at Enniscorthy, we were met by a number of officers,
who inquired from where we came, and after being in formed from Dublin,
they asked what we came for; we replied, to attend our quarterly meeting.
They queried how we expected to hold it,
when the town the day before was in possession of the rebels.
Our reply was that we believed way would be opened, at which they appeared satisfied.

We then sought after our friends, as some of them had remained during the siege,
this town having been in possession of the insurgents four weeks.
I shall not attempt to describe all their sufferings,
but just remark on some of their closest trials, one of which was the frequent,
solicitation to change their religion, and embrace the tenets of the Romish church,
being told "`There must be but one religion in Ireland,`" (that is,
the Roman Catholic.) And I was informed by many
Friends that many Protestants did suffer death,
and others turned to save their lives.
Of the number who suffered were two young men who frequented our meetings,
though not members.
These stood steadfast, and departed this life with calmness, after saying that,
though they were not members of the Society of Friends,
yet they could not change their religious opinions, which were those of the Society.
After visiting our friends who remained in town,
we went into the country about two miles, to seek some others.
In our way we saw great numbers of dead bodies, that were slain the day before,
some of which we had to remove, to make way for our carriage to pass.
Thus destruction appeared in every place, both of lives and property.
Many horses, sheep, swine, and goats, were killed.
The insurgents`' camp was entirely broken up.

The next day we met, and held our select meeting, which, though small,
was favored with the overshadowing wing of Divine love;
and I believe I may say that the several sittings of
the quarterly meeting were also favored:
and though we came through many discouragements, yet we rejoiced,
not only in seeing our friends, but under a sense of the Lord`'s goodness,
who had made way for us through many troubles.
Having concluded our meeting, after taking a solemn leave of each other,
I proceeded towards Waterford,
taking meetings in my way that lay in the county of Wexford;
and had many opportunities with Friends in their families,
who had been greatly distressed by the insurgents.
And I had also many public meetings,
wherein I was often favored to hold forth the truth in a good degree of clearness,
and some convincement appeared to take place.

At Ross, I found my friends pleased to see me,
and after a short stay I went forward to Clonmell,
and to the quarterly meeting held at Limerick, for ministers and elders;
where I found some strength to clear my mind.
After it concluded I returned to Tencurry (the residence of Abraham Jackson),
and after having some public meetings, went to Cork; where I tarried for several months,
visiting families, and having public meetings in Bandon, and at several other places.
During my stay in Cork,
I met with my dear friend William Savery on his return to America;
the vessel in which he took passage, putting into Cork harbor to wait for a convoy.
During his stay here we had many opportunities together, to our mutual comfort.
On board this vessel was Elizabeth Hoyland, a Friend bound to America in order to settle.
She appeared to be a worthy woman, and had a valuable gift in the ministry.

The following letter from David Sands to his wife belongs to this period of time:

[.salutation]
My dear Wife--

In that love that changes not I most affectionately salute you.
In my last I informed you that I was recovering from a very severe fit of sickness,
which prevented my traveling for nearly four months,
which has detained me in this nation to witness
an awful scene of distress and destruction,
both of lives and property.
I had previously a prospect of what was likely to come upon this nation,
and much desired to make my escape before it did come, but was not permitted;
and can now say that I believe my being here at this time,
is in the ordering of best wisdom; as Friends seemed quite unacquainted with such trials,
which have come upon them from various quarters.
And though they were often warned of what was coming, yet all would not believe.
But now they need no orator to change their minds.
I have had many trials in this land, yet have been carried through all thus far.
I am now favored with better health than I have been since arriving in this nation.
My return this fall seems doubtful at present,
but for your comfort I may say that I have met with many things that
have been as seals to the propriety of my present detention,
and of its being in the appointment of the Head of the Church.
Some convincement has appeared in the course of my late journey,
and that amongst the men mighty in war.
A person who had long approved himself one of the most fearless and undaunted,
and an officer of no inferior rank,
having sat with us in several meetings which I had in a town that had been besieged,
and many lives lost, and from which the clergy had fled,
invited me to his house to breakfast, which I felt easy to accept.
After it was over, I had a religious opportunity with himself and his family.
He was much tendered and reached, as he had been in meeting before.
He arose, and stripping off his military clothes, and laying by his sword,
asked for some other garments, saying to his wife and children,
"`I shall never fight more,
for I am convinced it is not in accordance with the spirit of Christ.
I am a Quaker.`"
Since this, he appears very solid,
and I hope he will make a valiant man in the cause of Christ.
Many others seemed inclined towards Friends of late.
I mention these things for the encouragement of yourself and our dear children,
whom I long to see; but whether I ever shall, is uncertain; and I hope, if I never do,
we will persevere onward in that line that will bring us together in a better world.
I think a more tried man is scarcely to be found,
though I do not wish to magnify my difficulties.
I know there is no such thing as being a soldier and not having to undergo hardship.

[.signed-section-closing]
Farewell, my beloved wife: affectionately yours,

[.signed-section-signature]
David Sands

[.signed-section-context-close]
Waterford, Ireland, 8th month 11th, 1798
