== Chapter 13

[.chapter-synopsis]
* Letter from Joseph Wing to Clementina Sands
* Letter from David Sands to James Harford, of Bristol
* Case of Meditated Suicide prevented
* Return to England
* Letters from Richard Reynolds

The following letter from Joseph Wing to Clementina Sands is deemed
worthy of a place in these Memoirs:--Joseph Wing to Clementina Sands,

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend--

Having you and your dear children so fresh in remembrance at this time,
I felt a freedom to communicate a few lines, in a sense of that love which changes not.
To give you a particular account of all my travels since I saw you,
would swell this to a large bulk;
but I may just inform you that it has been my lot to travel
twice through Nova Scotia--the last time was with John Wigham.
I was three months from home,
and traveled by land and water one thousand seven hundred and seventy-five miles.
Some part of the journey was very fatiguing.
Once we laid at night on the sea-beach, by the side of a fire,
and had our saddle-bags to lay our heads on, with our greatcoats to cover us,
(among swarms of mosquitoes.) Once we lay in the bottom of our boat;
and on another occasion we expected to have lain in the woods,
without the advantage of fire or food;
but just before daylight left us we reached a house.
But, fatiguing as it was, I have felt a great satisfaction in it,
firmly believing that it will be the lot of those who travel in the work of the ministry,
to visit that land oftener than it has been visited.
And I thought there was a perceivable growth in some places since last year,
or since I was there before:
and I do believe that there will be meetings set up in several places in that land.
And I think I have very satisfactory information of the
growth of our Society in our Eastern country;
in particular, where the lot of your dear companion, David Sands, was cast.

Five meetings are now set up within the compass of Vassalborough monthly meeting,
since he was there; and two in other monthly meetings.
Those within the compass of Vassalborough are, Sidney, Holywell, Bristol, Broadcove,
Camden, and the East Ponds.
Three meeting-houses are building this summer, thirty feet wide and forty feet long;
that at Bristol I think will need an addition in a few years.
The information I gave in regard to the spreading of truth, where David had traveled,
was thought by some to have been rather exaggerated,
especially by those who were ready to take him by the shoulders and haul him home,
or push him across the Atlantic Ocean.
Such judges as these, who presume to get into Moses`' seat, without being in his spirit,
I think must be very dangerous persons as to the progress of truth.
I trust I shall see one of them in a few days, and if I do,
he will hear the truth told him.
But to return, and give you some further account of our travels.
When we had gone through the howling deserts of Nova Scotia,
and had reached that meeting at Vassalborough,
I could compare my feelings to those of a man who had
traveled on such a small allowance of food,
that he was almost ready to faint.
My pen is not capable of setting forth the wide difference there was to be felt.
We had a highly favored meeting; indeed, never to be forgot by me.
Here are now five meetings, under the care of committees,
and so many requests for membership,
that they (the concerned Friends) are almost always traveling.
Such an exercise of labor I believe is not to be found upon the Continent.
I have at times been ready to conclude that it is owing to the great
extent of their labors here that they are so much favored.

The meeting of Camden, which is within six miles of the place where David Sands embarked,
is about seventy miles from Vassalborough.
I have visited those meetings twice since I parted with David,
greatly to my own satisfaction, although nearly five hundred miles from where I live.
At this meeting of Vassalborough, lives our dear friend, Remington Hobby,
who has had a double share of labor in those parts.
I believe he is more than half his time from home, ever since David left.
He has a fine family of children.
Micajah Dudley, a minister, who was convinced of our principles by David Sands,
has been removed by death.
His labors will be greatly missed.
Vassalborough is more than three hundred miles from our yearly meeting.
We have a number of members who live four hundred miles beyond them.
I may inform you that I saw the man last summer who commanded
the vessel when David Sands and I were cast away.
We were glad to meet.
I must now take leave of you, and bid you most affectionately farewell,

[.signed-section-signature]
Joseph Wing

[.signed-section-context-close]
6th month 29th, 1798.

--

The following letter, from David Sands, is supposed to be addressed to James Harford,
of Bristol.
Some of the trials to which he so feelingly
alludes in this letter are explained afterwards.
The defection from sound doctrine was creeping in,
though more fully developed at a subsequent period:

[.embedded-content-document.letter]
--

[.salutation]
My very dear Friend--

I returned to town this evening, where I met with your kind letter,
which was a cordial to my tried mind and fatigued body.
Since I wrote you last,
I have been mostly employed in visiting the families of Clonmel meeting,
which has been a laborious service both to body and mind, as they are pretty numerous;
but I feel a hope that it will tend to the furtherance of Zion`'s cause.
I have also had many public meetings with those not of our Society,
which appeared to be favored opportunities; one, I think,
it will not be unpleasant to you to hear of: it was with a large company of soldiers,
from Lancashire, who are mostly men of good families, and appeared to be well-bred.
They accepted the offer of a meeting with apparent gladness,
and during the time sat with great composure of mind;
and the Friends who were with me observed they had seldom known a more solemn season.
Many of them, after meetings, acknowledged it had been to them a time of favor,
which they hoped never to forget.
It may seem, from what I have written, that I am stationed in a land of favors,
where I might sing a song of Zion oftener than the returning light of the morning; but,
my dear friend, it is far otherwise with me.
I feel myself surrounded with many discouragements; and did I not believe,
beyond the shadow of a doubt, that I am here in Divine appointment,
my situation would be insupportable;
as I feel much of my time like a sparrow alone on the house-top;
yet I do not desire to complain of Him who has not only
a right to dispose of his servants as he pleases,
but knows how to do it for their good and His glory.
Therefore, I can only say,
"`Your will be done,`" which I am often unable to say in that humble manner I could wish.
Your continued brotherly care, with that of your dear children,
joined with your near sympathy, is very strengthening to me;
as I have every reason to believe your desires are for my preservation,
and that I may endure through all storms;
in which I trust you are joined by many brethren and sisters,
who have expressed a near sympathy with me, since being in this land.

I came here with a hope I might be set at liberty to return to Milford;
but this at present seems uncertain, as I have not yet been in the North,
nor has there a way clearly opened for it.
Traveling remains to be attended with many difficulties,
as robberies are daily committed on most of the roads throughout the nation.
Yet, should that now appear to be the way cast up for me,
I hope I shall still persevere therein with a becoming cheerfulness, nothing doubting:
knowing that I am safe always, while He whose name is "`I am that I am,`" is with me.
I often think of the time I spent in company with you and your dear children,
which appears as a day of feasting,
and of drinking wine refined from the lees of insincerity,
which greatly abounds in some parts of the world.
The value of the choicest comforts are best known by the lack of them.
Oh, could I have an opportunity of opening my sorrows,
and to pour them out to a bosom friend!
I believe I should often find relief; but that I cannot, at least am afraid of doing it.
I must, therefore,
conceal my grief and hide my trials for the present
until I meet my dear friend and his beloved children,
when my sorrows will be turned into joy.
Until then, farewell, my tenderly beloved friend.

[.signed-section-signature]
David Sands

--

The Journal proceeds:--After parting with my friends at Cork, I returned to Youghall,
and tarried some days, visited several families, and had some meetings.
From this place I went to Clonmel, and from there to the quarterly meeting at Waterford,
which was large, and owned in a good degree with the overshadowing of Divine love.
From Waterford I returned to Clonmel,
and joined Ann Broadhead in a visit to the families,
which we accomplished in much nearness of spirit;
after which I had many public meetings in and about Clonmel, which were favored seasons.
From this place I returned to Waterford, and tarried several days,
and visited some families, when able.

Here I received many kind letters from my friends in England,
towards whom I felt my mind drawn, as they seemed very near to me,
and with whom I greatly desired to spend a little more time;
yet no way opening to leave Ireland at present, I must still obey my best Guide,
though it is hard to my natural inclination,
as traveling here is in every respect unpleasant,
the country being in general thinly inhabited as to respectable people,
and now these are driven into garrisoned towns, for many have been murdered,
or have fled to some other country;
so that poor Ireland at this time exhibits a mournful appearance;
yet I have been permitted to pass along without any obstacle or hinderance.
At Waterford, I met with my dear friend Elizabeth Usher, whose kindness was very great;
as she furnished me with a comfortable carriage, of which I stood in need.

12th month 28th, 1798.--I left Waterford to attend the quarterly meeting at Carlow,
in Leinster Province, which, though not large, we were favored with Divine help.
Here I met with my kind friends Mary Ridgway and Jane Watson.
After the quarterly meeting,
I felt inclined to visit the famines of Friends in this monthly meeting.
During my stay, I had several public meetings,
which were attended by many very respectable people, and were solid opportunities.
From there I went to a town called Athy, where a few Friends reside,
and there are many seeking people.
I had several public meetings with them, much to my comfort.
From this place I went to Baltimore,
and visited the few families of Friends at that place, and had one public meeting.
This was once a place of note as to Friends, but is now much on the decline.

During the latter part of the time in which
David Sands was engaged in the visit to Ireland,
he appears to have discontinued his Journal;
so that from this period we can only notice his movements from the
brief biographical sketch prepared by some members of his own family,
and which has already been largely quoted from in the early part of these memoirs;
or from letters or other fragments.

During the time of the Rebellion,
Friends in Ireland were very careful that nothing
should pass from one to another in writing,
which, if it should fall into improper hands, could be construed to their disadvantage.
Another consideration might possibly have weight with David Sands about this juncture,
arising out of the agitated state of the Society,
from the dangerous defection from the fundamental doctrines of Christianity,
which several who had been high in profession gave way to;
and which ended in the secession or separation of many of them from the body.
Deep were the mental conflicts and depression of spirits which
he had to pass through for a length of time on this account;
believing himself often called upon to unite with the sound
Friends in earnestly contending for the faith of the Gospel,
against those who denied the Godhead of Christ,
and the efficacy of his propitiatory sacrifice;
as well as embracing other foolish and unsound opinions.
His labors and services were a great support to
many of his friends in this critical juncture;
though it drew upon him some unfriendly and improper animadversions from some,
who attempted, through the medium of the press and otherwise,
to maintain the cause of those who were caught even in such great delusions.

After visiting Ballitore, as noticed in his Journal,
he visited the families of Friends in Dublin; and proceeding to the north,
engaged in other services in the Province of Ulster.

In the course of his service and travels in Ireland,
the following very remarkable circumstance occurred;
proving that the ways of Providence are frequently inscrutable,
in his gracious interposition for the deliverance of
his creatures from the power of the enemy,
and in leading his ministers and messengers by a way that they know not,
in the simple obedience of faith,
that so he may make them instrumental in effecting his wise and gracious purposes.
As he was riding along he felt a concern to stop and appoint a meeting,
to which his companions offered some objections; as it was a place but thinly peopled,
and the night very stormy; so that probably few would attend.
But David Sands did not feel easy to give it up, saying, "`If there are but few,
the great and good Shepherd has promised to be with us,
and I shall feel clear in having done what appears to be my duty.`"
They yielded to his concern, and notice was given.
At the time appointed a greater number assembled than was expected.
The meeting became settled in much solemnity.
He arose, commencing his testimony with these words,--"`Resist the devil,
and he will flee from you.
Turn unto Him who is able and willing to save; although your sins be as scarlet,
He will make them white in the blood of the Lamb.
He is still waiting to be gracious, and though you have strayed far from the fold,
He will lead you as unto pleasant pastures,
where streams of living water flow forevermore.`"
He had much to offer, all pointing and leading to the one great Fountain of Mercy;
and then added,--"`I am bound to express my feeling and impression,
(though I know not for whom it is intended),
that I believe there are those present who have been so
far led astray by the Enemy of their soul`'s salvation,
as to be ready to take their own life.`"
Soon after this the meeting broke up, when a man of a respectable appearance,
under great distress of mind, approached him, saying,--"`Your message is to me;
it is true that I now have the instruments of death in my pocket.
I have become weary of life, and have no resolution to withstand the Tempter,
so as to face the cruel blasts of adversity,
and had determined this night to commit the fatal deed.
Yet I felt the awful responsibility; and having heard of this meeting,
and knowing that Friends often sat in silence,
I believed that I should be enabled to become
calm and composed before the awful close of life.
But now I have abundant reason to bless God,
in that he has made you the instrument of saving my life, as also my immortal soul;
which, but for this interposition,
would have rushed unbidden into the presence of an insulted God.`"
His heart now overflowed with gratitude both towards David Sands as the instrument,
and unto the Lord, by whom he was thus sent to save a fellow creature from destruction.
It is stated that soon after this wonderful providential interposition,
this person became a changed and greatly improved character.

The time of David Sands`' travels in the north of Ireland was a
period of deep exercise to rightly concerned Friends,
with whom he sympathized, and largely partook of their trials.
He felt that great care was needful that he might be
preserved from giving any just cause of offense,
so that no advantage might be given to the adversaries of truth;
while he was desirous to contend earnestly for the faith once delivered to the Saints.
It was the truths of the Gospel, as taught by our Holy Redeemer, our Lord Jesus Christ,
and his Apostles, for which he contended:
and he was enabled to discharge his duty as a faithful messenger,
charged with Divine authority, to the comfort of many minds.
Thus he felt the necessity for daily watchfulness,
depending upon that Divine power and support which
through all his trials and exercises had never failed;
but which,
like the manna by which the children of Israel were sustained in the wilderness,
had to be gathered daily.
After feeling released from further service in Ireland,
he returned to England with peace of mind, about the 5th month, 1799,
and was received with much kindness and affection by many Friends,
who truly sympathized with him in his unwearied labors,
both among Friends and those of other societies;
in his extensive journeyings in the cause of truth,
and in his love to his fellow creatures,
that they might receive the word of eternal life.
The unity of his friends he felt to be very precious,
and cause of thankfulness to his great and good Master,
who had preserved him through so many close trials, had so graciously owned his ministry,
and favored him to return to his friends in England with the reward of peace.
There does not appear any memorandum of the
exact date of David Sands`' arrival in England;
but it is apprehended that it was a little previous to the London Yearly Meeting of 1799.

The unsoundness in doctrine which had manifested itself in
Ireland was now attempted to be infused into the minds of some
of the inexperienced and unwary among Friends in England,
(chiefly through the influence of Hannah Barnard,
who came over as a minister from America,
and her adherents.) We shall again have occasion to revert to this individual.
These insidious attempts deeply affected the vigilant
and tenderly concerned mind of David Sands;
to whom the truth, as it is in Jesus, had ever been very precious;
and some allusion will be found to them in the following letters from Richard Reynolds:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend--

By your acceptable letter of the 6th instant,
I was glad to find not only that you are better in health,
but that you so remember me as to inquire if I am still in the land of the living.
I continue to breathe the air of this world;
but such has been my spiritual poverty and desertion,
that if I may yet be written "`among the living in Jerusalem,`"
the strongest indication of it seems to be that I am not
always insensible of my own lacks and weakness,
or indifferent to the cause of truth,
or to those who are engaged in the propagation or promotion of it.
And among them, you have been frequently remembered by me,
though I admitted that your late arduous engagements might
sufficiently account for your appearing to have forgotten me.
I have heard, and was grieved as well as surprised,
to hear of the departure of some in Ireland from the faith of their
forefathers--may I not say from the faith once delivered to the Saints:
of some to whom I looked up, not only as being further advanced,
but more established in it than myself.
But I rejoice that some have returned;
and earnestly desire that your hope for the rest may be accomplished.
By a letter received this week, I understand William Savery has been ill,
owing to his great exertion in his vineyard,
which he found in great disorder when he returned from Europe.
He had been confined, but was then getting better.

Of those in this land from America, I hear that Thomas Scattergood is in London,
being lately returned from Kent, where he attended the funeral of our ancient Friend,
Sarah Beck, at Dover;
that Charity Cook and Mary Swett had nearly concluded their
visit to the families in Gracechurch-Street monthly meeting;
and that Sarah Harrison was yet detained at Mary Alexander`'s, at Needham,
poorly in health.
I hope this will find you well on your way in the important
service of visiting the families of Friends in Dublin;
and if, at the completion of all that is or may be required of you in Ireland,
you should find freedom to visit your friends in Old England once more, I shall rejoice;
and more especially in the hope you permit me to indulge,
that you will come pretty directly to my habitation,
where you may depend on a cordial reception;
and that many will be glad to see you at the Dale, where I think you have not yet been.
I shall address this to the care of Joseph Williams, to whom please give my love;
and I hope he has received a few lines,
by which I took the liberty to request him to procure
some books for me that were printed in Dublin.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Richard Reynolds

[.signed-section-context-close]
Coalbrook Dale, 2nd month 26th, 1799

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Reynolds to David Sands.

[.salutation]
Dear Friend--

I am glad to find my letter of 2nd month 26th, was acceptable to you,
that my very low state of mind obtains your sympathy, and, I trust,
your prayers likewise; for certainly very few, if any, stand more in need of every help;
as I also confess as few, if any, are less worthy of it.
Your speaking of me as an elder brother,
and to me as qualified to admonish one I so justly prefer, is humbling to me.
Alas! how little you know of my weakness.
So far as love to the good cause in which you are engaged, and to you,
as one laboring in word and doctrine,
can qualify for sympathy with you in your present arduous engagement,
and very trying situation, I am not altogether deficient.
I am much grieved by the account you give me of the
state of society in that part of the country where,
perhaps, I might have expected the greatest soundness of faith and purity of manners:
the nearest approach to primitive simplicity,
and the most exemplary compliance with the (Society`'s)
recommendation to the frequent reading of the Holy Scriptures;
and a conformity in the other particulars,
which most conspicuously distinguish us from other professors of Christianity;
as well as in the maintenance of our more important testimony against war, oaths,
and all ecclesiastical impositions,
which are inconsistent with the freedom and spirituality of the Gospel dispensation.
The pleasing expectation of the returning of those who had strayed,
which I indulged from your former account, is much lowered by your last representation;
yet I desire to be enabled to pray for their restoration, and confiding that,
by the superintending providence of the Almighty,
all things will work together for good to those who love him;
and to unite with you in your comfortable hope,
"`That he who only could support his own cause, and carry on his own work,
will lift up a standard against every attempt of the enemy,
however artful or hidden his design may be.`"

I am obliged by your caution against the reading or spreading of mixed books;
though I think the supposed occasion originated in a mistake.
You says Joseph Williams told you I had given him an
order to purchase the writings of Lady Guyon,
which did not feel pleasant to you.
In my letter to Joseph Williams,
I informed him that I had seen some extracts
from the writings of the Archbishop of Cambray,
published in 1797, by our ancient and well-esteemed friend, John Kendall,
who told me they were taken from an edition of two volumes octavo, printed at Dublin.
Those I requested J. W. to procure for me; but if he has misunderstood me,
and purchased any of Lady Guyon`'s works,
I shall be much disappointed--not to say mortified.
I think neither her name nor opinions are once mentioned in the extracts,
though there may be coincidence between them and some contained in the book.
I am also of opinion with you, that reading certain books,
though written by men acknowledged to be pious and sincere,
has retarded the religious advances of some,
and prevented them from receiving the truth in the simplicity and love of it.

Some painful instances you have mentioned,
and I am far from being offended by your cautions:
though I trust to be preserved from grieving or
offending any brother who may not think exactly as I do,
or who may not concern himself at all with the opinions or practices of others.
Your faithful friend,

[.signed-section-signature]
Richard Reynolds

--
