== Conclusion

In the year 1818, the infirmities which now increased upon David Sands,
subjected him at times to great bodily pain;
but his mind was supported with an unshaken hope that all was well,
as respected a future state; saying that he had no fears,
except that he might not bear the pains of his
departing moments with as much patience as he ought.
His greatest anxiety seemed to be for an increase of the kingdom of Christ,
and of the religious Society of which he had long been a deeply-exercised member;
and to whose religious principles,
identical as he believed them to be with genuine Christianity, he was deeply attached.
He declared, in these solemn moments,
that these considerations were dearer to him than his natural life.

About this period a number of Friends met after a monthly meeting at Cornwall,
to which he belonged; and he requested a religious opportunity with them; when,
after communicating suitable counsel and encouragement, he said;
"`I wish my friends everywhere to know, that I am like the children of Israel,
when passing through the wilderness; my shoes are not waxed old, nor my garments rent;
but the same living exercise and travail of spirit that I have witnessed in early life,
is yet my experience; and the prayer of my heart often is,
that my sword may remain bright, and that I may go down to my grave in my harness.`"
And this his request seemed in a remarkable manner to be granted;
as much of the last part of his life was spent in
visiting the families of his own particular meeting:
and when he had completed this service, he attended the meeting on first-day,
and was remarkably favored in testimony, having much to communicate on many subjects,
though in great bodily weakness.
When returning home, on passing by the burying ground,
he queried with his wife if everything did not appear unusually pleasant; remarking,
"`I do not expect to pass this place again:`" and
though he was then in nearly his usual health,
within a week, his earthly course was terminated; and we believe it may be said,
with his sword bright, and duly harnessed.
The powers of his mind appeared bright, and his zeal to increase.
He often expressed that he believed his time in this world would be very short,
and that he wished to improve every opportunity, both public and private,
and to encourage all.
He knew that nothing could take away the sting of death,
but freedom from sin and transgression, through the power of the Holy Spirit,
and the sprinkling of the blood of Jesus.

His nights were painful;
and he was often heard supplicating at the Throne of Divine Grace,
that they who sat in darkness,
might be brought to have faith in that Divine power which caused the blind to see,
and the lame to walk.
Thus the exercise of his mind for the good of
souls continued almost to his latest moments.

On his return home from the last meeting he attended,
he said he had taken a final leave of the meeting;
but that there were a few individuals on whose account he still felt some anxiety,
as they were not enclosed within the pales of our church.
But that his prayers were, that others might be raised up to feel for those,
and to bear the weight of his concern, and labor with them.
He feared that many felt a disposition to withdraw
their necks from under the yoke of Christ;
and that though he should be removed from works to rewards,
he believed the cause would make progress,
though many might "`fall out by the way;`" but the truth was the same that it ever was,
and that all who were clothed with it,
would rise superior to all the power of an unwearied adversary.

He remarked that he had never felt such happiness before,--that he felt himself
surrounded with heavenly spirits--that his sensations surpassed description.
"`I think,`" said he, "`that some great change will soon take place with me.
Come life or come death, my joy and happiness seems complete.
My cup this day has been made to overflow.
I never experienced such a meeting as I have had this day.`"
On second-day morning he was very feeble,
and his general appearance indicated the approaching change.
It was proposed to call in a physician, to which he consented;
but said it was to gratify his friends,
for he considered his case beyond the reach of medicine.
He remarked that his day's work was done, he had nothing more to do,
as respected a future state: he had not left his concern for that to a dying hour.
He desired that all mankind would be willing to labor as he had.
"`Behold, I have left all to follow you, the only true God;
and you alone have I worshipped and adored.
You have been my morning song; and my evening prayer has been to you.
How is my soul replenished with your sovereign grace!

You have preserved me by sea and land: You have never forsaken me,
though my trials have been many.`"
He proceeded to speak of his experience saying,--
"`I have also been persecuted by false brethren,
and many proving dispensations have been allotted to me;
but blessed are they who are persecuted for Christ's sake.
I have rejoiced that I was found worthy to suffer in so glorious a cause.
If I know my own heart, from the commencement of my religious exercises,
I have preferred the experience of the mercies of a gracious God to all other things.
By Him have I leaped over the walls of opposition that at times have encircled my path.
But now the time draws nigh; the curtains of the evening of this life will soon be drawn.
I have many precious friends who will lament my loss;
and I am sensible that I have had their tender sympathy,
though many of them are in a far distant land;
yet I seem to feel their tender spirits hovering round my dying bed.
But I must resign them,
with a confident hope of ere long meeting them in the realms of endless bliss.`"
In the afternoon, a neighbor who frequently attended meeting,
called and was desirous to see him; but feeling too feeble,
he objected to engage in any further labor,
aware that probably he might feel anxious to say something to him;
but on reflecting a little, he seemed desirous to see him.
When he was introduced, David Sands made some very close remarks;
advising him to pursue for the future a different course of conduct,
if he wished for happiness here or hereafter.

After he left, David Sands observed that he had been closely tried;
but found he must not withhold what presented;
probably it might be the last of his labors; and so it proved, except in his own family.

He had often expressed a desire that he might be released from
the suffering of much bodily pain in the closing hour;
and he was favored to have his desire granted.
In much quietness and composure he breathed his last,
like one falling into a sweet sleep, on the fourth day of the same week,
being the 4th of the 6th month, 1818; and on the 7th of the same,
after a large and solid meeting held at his own house,
his remains were interred in his own family burying ground;
aged seventy-two years and eight months; a minister about forty-four years.
