[short="Testimony from Cornwall Meeting"]
== A Testimony Monthly Meeting of Cornwall Concerning David Sands

He was the son of Nathaniel and Mercy Sands, of Cowneck, on Long Island,
and was born the 4th day of the 11th month, 1745.
He came among Friends by convincement,
and appeared in the ministry about the 27th year of his age,
in which service he labored abundantly both at home and abroad;
having devoted the greater part of his life, from his entrance into the ministry,
to visiting Friends, and in appointing meetings among other denominations.
And we have reason to believe that he has been instrumental in
stirring up and convincing considerable numbers,
in many places,
as he was led to feel and sympathize with the religiously exercised of all denominations;
and he was often qualified to reach those in a more insensible state.
He visited New England several times, in the course of his life;
and it appears to have been a principal field of religious exercise and labor with him.
On his first visit in these parts,
there appeared to be very little convincement in many places;
but by faithfully laboring in obedience to divine direction,
he was made instrumental in gathering several meetings.
Where he traveled and labored in some parts of that country.
Friends have so far increased as now to hold both monthly and quarterly meetings.

He also visited Pennsylvania several times, and some of the Southern States,
as well as performed several religious visits to the families
of Friends in the cities of New York and Philadelphia.
He likewise labored extensively within the compass of
the yearly meeting to which he belonged;
and was particularly useful in the first rise and spreading of
the Society on the west side of Hudson River,
within the verge of Cornwall Quarterly Meeting.

He also visited Europe; and informed us on his return,
that he had visited the Islands of Great Britain, Ireland, Jersey, and Guernsey;
and attended all the meetings of Friends, which he had an account of, on the continent.
He also traveled much in France, Germany, and other parts of the continent,
in which he had frequent opportunities of religious
conferences with others not of our Society;
and his returning certificates evinced the satisfaction
of his friends with his religious services among them.
After his return from Europe,
he visited occasionally many places within the verge of our own yearly meeting,
and also paid a religious visit to Canada, and the city of Quebec, in the winter season.
Shortly after his return, he set out on his last visit to New England,
in which he was from home about a year.

This, our dear Friend,
experienced many vicissitudes and trials in the
prosecution of his temporal concerns through life,
and was frequently tried with much bodily indisposition; however,
none of these things seemed to abate his concern for the
accomplishment of what appeared to be his religious duty.
He appeared to be much exercised on account of many speculative and
unsound opinions that are circulating in the present day,
and was often led to caution his Friends lest they should be drawn aside by them,
and recommended them to maintain that simplicity and stability in principle and practice,
which was so conspicuous in our worthy ancestors.
He was very particular in noticing strangers that attended our religious meetings,
as well as in exercising a fatherly care and sympathy with the members of our Society,
who were within the compass of his labors.

The latter part of his life, he seemed to be occupied very much about home;
and was made particularly useful in bringing forward
some under religious exercise in his own neighborhood;
and near his close,
he was engaged in a family visit to Friends of Cornwall monthly meeting,
which he partly accomplished;
and was favored to attend our first day meeting the same week he died.
While on his way there,
he signified he thought it would be the last he should ever attend.
He appeared to be much strengthened in the public testimony he bore in it;
and at his return, he expressed that he felt great satisfaction in being there;
and that a more than ordinary sweetness seemed to cover his spirit.
He had often expressed a desire that he might not
experience much bodily pain in the closing scene,
and was favored to have his desire granted,
and to part with his friends in much composure and quietness,
as one falling into a sweet sleep, on the 4th day of the 6th month, 1818,
aged seventy-two years, having been a minister about forty-five years.

Thus ended the pilgrimage of this our much beloved friend, who,
after a life of many and close conflicts, and great travail and exercise, was favored,
we trust, to arrive safe in the haven of everlasting rest,
out of the reach of storms and tempest, and beyond the noise of archers.
May we, his survivors,
be engaged to imitate him in all his virtues and religious industry; that so,
in the conclusion of time,
we also may be favored with the reward of that peace and everlasting consolation,
which we humbly hope is now his portion.

[.signed-section-context-close]
New York Memorial of Deceased Ministers.

The date of the Memorial is not given; but probably it was issued in 1818,
the year of David Sands`' decease.
