[quote.epigraph, , Dan. 12:2-3]
____
Many of them that sleep in the dust of the earth shall awake; some to everlasting life,
and some to shame and everlasting contempt:
And they that be wise shall shine as the brightness of the firmament;
and they that turn many to righteousness,
as the stars forever and ever.
____

== Introductory Remarks.

The following account of David Sands has been compiled,
partly from a brief biographical sketch found amongst his papers,
and also from the Journal of his travels, kept by himself,
whilst engaged in the work of the ministry, in America, in England and Ireland,
and on the European Continent.
In making these memoranda, he does not appear to have had any view to their publication;
which has occasioned their being left in a less perfect
state than they otherwise would have been;
and has rendered many little corrections expedient and necessary,
for the sake of perspicuity;
but great care has been taken to convey accurately his real meaning.

The Journal was discontinued whilst he was in Ireland, about the year 1799,
and does not appear ever to have been resumed.
From that period,
the notices of his religious services have chiefly been collected from his correspondence,
part of which was found transcribed by his own hand.
A few miscellaneous pieces, written on various occasions, have also been inserted.

These documents have been for many years in the possession of his daughter,
Catharine Ring; and have lately been confided, with a view to their publication,
to the care of Edward Pease, of Darlington, and his son, John Pease.

In preparing these papers for the Press, it was, as might be expected,
found desirable to abridge them,
otherwise the volume might have been swelled to a much larger bulk.
In the form in which they are now presented to the reader,
it is hoped they will contribute to edification, and tend to preserve for posterity,
the memory of an individual, precious to many yet living;
of one whose long-continued arduous labors and services
were eminently owned by the Great Head of the Church;
and blessed to many, to the promotion of the Redeemer`'s Kingdom;
and we reverently trust to the salvation of souls.

[.signed-section-context-close]
Newcastle-Upon-Tyne, 1 Mo. 3rd, 1848.
