== Chapter I.

[.chapter-synopsis]
* Parentage
* Convincement
* Marriage
* Thoughts on Slavery, etc.
* Appears in Public Testimony as a Minister, and Travels in the Service

David Sands, son of Nathaniel and Mercy Sands, was born the 4th day of the 10th mo.,
1745, at Cowneck, on Long Island.
When about fourteen years of age, his parents removed to Cornwall, Orange County,
State of New York, where he was instructed in farming, etc.; the country being new,
he had but little opportunity of improvement by the assistance of schools.
He was very industrious, in order to acquire an education;
and having commenced learning the Latin language, previous to his removal,
he improved every opportunity of persevering in it, and much of the time,
without the knowledge of his father, studying often by fire-light.
His father feared such close application would be too much for his delicate constitution,
as it was necessary to have his assistance through the day,
he being the eldest of a large family.
He was brought up in the Presbyterian profession;
but being given to see and understand the necessity of being a true Christian,
and not merely a nominal professor, and of seeking to know the will of his Creator,
and to do it according to the light he had received,
he was not entirely satisfied with many parts of his profession of religion,
and earnestly desired to know the truth as it is in Jesus.
His inward exercise increased, and for several years he suffered great anxiety of mind,
insomuch that his parents became very uneasy on his account,
although it was out of their power to relieve him through their own religious apprehensions;
but they often expressed that if he could but find peace of mind,
they would be satisfied to give him up to it, let his name to religion be what it might.
Meanwhile,
he was diligent in his duty in assisting his parents in raising their large family.
He commenced the mercantile business, with his father`'s assistance,
and continued in it some time; but his great exercise of mind increasing,
his health became seriously impaired.

About this time, he attended a meeting appointed by Samuel Nottingham, a Friend,
from England, whose testimony,
and the religious views and principles which he offered for consideration,
were fully consistent with his own exercised state of mind,
but the idea of being a Quaker seemed then impossible for him to reconcile.
The plain humble appearance seemed to him to be more than was necessary
for any man to adopt in order to assist him to be a Christian.
In the desire more fully to be at liberty to pursue his religious exercises,
and to establish his mind on what appeared clearly made known to him as his duty,
he gave up his business, left his home,
and commenced teaching school in a village a few miles distant.
His close exercise of mind continuing,
he retired daily to a secret spot some distance from his dwelling,
to supplicate his Maker for knowledge to enable him
to go forward according to his divine appointment.
He never lost sight of the principles of Friends,
though he could not feel satisfied to take up the cross which they appeared to lead to.
After one of his lonely supplications to his Divine Master,
to know clearly his will concerning him,
and what steps to take further in the line of duty to advance the
glorious cause of the salvation and redemption of the sons of men,
through Jesus Christ his Saviour, upon raising his eyes,
after this solemn dedication of body, soul, and spirit,
there appeared to his view two men plainly dressed in light clothes,
as if walking from him.
He was struck with the sight, and in thought exclaimed,
"`It is impossible for me to be a Quaker--I would rather die.`"

He had been informed a Friend, named Edward Hallock, had removed,
with a large family of children, from the east end of Long Island,
and settled at New Marlborough, about twelve miles distant.
His exercise continuing, he determined on paying him a visit,
which he did on the seventh day of the week.
When he arrived at his house, he inquired for Edward Hallock, who met him, saying,
"`That is my name;`" to which he replied, "`My name is David Sands;
I have come to pay you a visit.`"
He received him very kindly, inviting him in,
and introduced him to his wife and family by saying,
"`This friend has come to pay us a visit.`"
The subject of religion was soon introduced; E. Hallock being of a friendly,
interesting disposition;
they soon acknowledged a unity of sentiment on many important points,
and an entire freedom of communication and inquiry was made by David Sands;
many obstacles were removed by the candid and Christian feeling shown towards him,
and on various points so kindly explained to his understanding.
In the course of the evening David Sands inquired if there
was a Friends`' meeting for him and his family to attend,
to which E. H. replied,
"`We hold our meetings here,`" alluding to the room in which they sat.
"`We commence our meetings at eleven o`'clock;
sometimes our neighbors come in and sit with us.
Our meetings are often very comfortable,
and I feel thankful in believing they are owned by the Great Head of the Church.`"
David Sands said he felt it right to stay and sit with them.

Afterwards much religious conversation took place, producing a uniting freedom in both,
and had a blessed effect in opening the eyes of David`'s understanding in such a way
as to relieve his doubts respecting the religious society which it would be right,
according to his present feelings, to unite with, when fitly prepared,
and the way more fully opened for his future course in pursuing
such paths of duty as would bring peace of mind.
In the course of the meeting E. Hallock had considerable matter to offer by way of testimony,
and much to the encouragement of David Sands,
who freely acknowledged his satisfaction therewith;
after which he invited him to come up at the time of their monthly meeting,
held at Nine Partners, and accompany him to it,
by which he would obtain a further knowledge and acquaintance with the Society.
He readily accepted the invitation,
and in this opportunity he made an acquaintance with a number of Friends,
particularly Solomon and Elizabeth Haight, Aaron Lancaster, Aaron Vail, Paul Upton,
Paul Osborn, and many others.
In this visit he became fully satisfied, and his mind was relieved,
and a willingness produced to embrace the truth according to his present views.
His health became established,
and he soon after gave up his school and resumed his former business,
a part of which brought him frequently to New York.

The first Friends he made an acquaintance with there were Joseph Delaplaine,
and another of the name of Underhill.
They came on board his vessel to make some purchases, and after leaving it,
and proceeding some distance, Joseph stopped, saying to his friend who accompanied him,
"`There is something in that young man which has interested me very much;
I feel it right to return and invite him to my house.`"
The other Friend replied, "`I also felt exceedingly interested in him, (not knowing why,
as he made no appearance of a Friend,) and I shall be glad to return with thee.`"
And on their making known the object of their return, David Sands replied,
"`I also had feelings which I am unable to express by words,
and most gladly accept your kind invitation.`"
The time appointed for the visit was on first day afternoon, at which time he went,
and accompanied them to Liberty-Street Meeting,
(then called Crown-street,) this being the first
Friends`' Meeting he attended in New York,
and also eventually the first house in which he appeared in public testimony.
He steadily attended meetings as far as it was in his power,
principally those of New York, as his business for some time called him there weekly.

In the twenty-first year of his age he requested
to be admitted a member of the Society of Friends,
at Nine Partners, and was received with much satisfaction to himself,
and generally so to the Society,
having evinced a steady and exemplary walk through his various conflicts and trials.
Notwithstanding his parents`' former anxiety had been very great,
on account of his close exercise of mind, respecting his religious course,
yet when they became satisfied that nothing but being
a Quaker would give or had given peace to his mind,
it was a trial to them;
and to consent to his marrying a Friend seemed almost too great a trial to be borne,
they having had no knowledge of, or any acquaintance with Friends, except through him.

In the 11th mo., 1771, he was married at Nine Partners, to Clementine Hallock,
daughter of Edward and Phebe Hallock.
Many kind and interested friends evinced their unity on the occasion by their attendance.
They saw that it would be a means of opening the way,
and establishing Friends in those parts where he was about to settle.
Soon after his marriage he accompanied his wife,
to pay a visit to some of her connections with whom he was not personally acquainted.
They received him with much kindness, and welcomed him as a near friend and connection.
Soon after his arrival he discovered that they kept a number of slaves,
for at that time it was not generally thought to be wrong for Friends to hold them;
he became much exercised in feeling it wrong for
him to partake of the products of their labor.
His wife and her friends had no idea of the cause of his apparent change,
otherwise than that he was not well.
In the morning he appeared no better,
and could not partake of any thing that was offered.

Their next visit to their connections was attended with the same difficulties,
as slaves were also there employed.
He was then obliged to inform his wife of the cause of his suffering,
and requested she would be willing to return home without further delay,
and give the most satisfactory reason she could as
to the non-fulfilment of the remainder of their visit.
If they could attribute it to sickness he did not feel it necessary to contradict it,
as in truth his heart sickened at the thought.
He felt that this testimony against holding slaves was a great work for him to commence,
and must be carefully investigated, as it would be a work of time,
and would not bear hasty resolutions,
but firm and steady measures only would support him in it.

After their return from this visit they spent the winter with his parents and family,
who soon became reconciled to his choice of a wife,
and treated her with much kindness and affection.
Her steady and consistent deportment,
added to a disposition to increase the happiness and best
interest of all those to whom she had become so nearly connected,
made way for her, so that the time spent with them was truly edifying in the family,
and produced lasting and blessed fruits to many of them.
His parents, through him, became convinced of the truth as he had embraced it,
and became members of the Society, as likewise did some of his brothers and sisters.^
footnote:[It is apprehended that his brothers, Benjamin and John,
became members of the Society.]
In the spring of 1772 they commenced housekeeping near his father`'s,
in a house belonging to him, and in which David Sands lived the remainder of his days.
The house still remains in his family, and much interest is attached to it,
both on account of its ancient appearance,
and its having been for so many years the residence of one so well known and beloved.
It continues to be a house for the accommodation of the Society,
as it was when he occupied it, and according to his own wish.
They immediately commenced a meeting,
to be held on the first day of the week at his own house;
the first was attended by several Friends of New York, and Joseph Thorne from Flushing,
Long Island, who had recently settled near, and who, being a worthy member,
much interested for the welfare and increase of the Society,
soon became as a pillar among them.
They soon after commenced a week-day meeting,
which continued to be held for eleven years, except on the days of attending Preparative,
Monthly, and Quarterly Meetings, at Nine Partners.
A number soon joined their little band through convincement,
and others settling near them from other parts made the increase considerable.

This meeting was often visited by Friends from Nine Partners, particularly ministers,
as Aaron Lancaster, Aaron Vail, David Haviland, and many others.

In the latter part of the year 1772, David Sands first appeared in public testimony,
much to the encouragement and furtherance of their meeting,
establishing the faith of many seeking minds.
He was concerned to pay short visits,
laboring in the ministry of the Gospel for the increase of the Society,
and that the great work of salvation might be carried on to the glory of his Maker,
in whose cause he felt willing to give up all for the advancement
of truth and righteousness in the earth.

In the year 1775, he was recorded by his monthly meeting as a minister of the Gospel.
At the same time he requested a certificate to pay a religious visit to Friends at Newport,
Rhode Island, and parts adjacent.
This visit was not extensive, and the following account of it is from his Journal:

[.blurb]
=== An account of my journey into New England in company with my friend Aaron Vail.

"`I left my home the 5th of 11th mo., 1775; went to Edward Hallock`'s at New Marlborough,
and attended their first-day meeting: though small, yet I was comforted,
and truth seemed to own us.
After meeting I parted with my wife and friends, and proceeded to Nine Partners,
in company with Samuel Hallock; the next day set out for New England,
with my friend and companion Aaron Vail; lodged at Oblong,
and reached Moses Varnum`'s at Uxbridge, and attended their meeting,
which was refreshing, truth prevailing to the comfort of many.
On seventh-day was at a meeting at Winsocket, which was large, and, I trust,
edifying to many who were inquiring the way to obtain
the salvation of their immortal souls;
next day attended the meeting for sufferings, held at Providence,
and lodged at Moses Brown`'s, where we stayed two days;
the week-day meeting at Smithfield was attended with close labor,
though it ended to a good degree of satisfaction.

"`We returned to Moses Brown`'s, and next day attended Providence week-day meeting,
which was solid and comfortable, though silent;
next day was at an appointed meeting at Swansey, which was large and satisfactory,
and it was cause of thankfulness to us that the Great Master continued his renewed favors,
in a time of deep trial and exercise, which often is our portion.
We parted with our companion Aza Arnold,
and came in company with Ebert Chase as our guide,
and lodged at Joshua Davil`'s in Dartmouth;
the next day attended the monthly meeting held at Coaxet,
where we met our esteemed friend Robert Willis,
who was paying a religious visit in those parts, and who was largely opened in testimony;
there appeared to be some in the meeting concerned for truth`'s prosperity.
On first-day attended the meeting again at Coaxet, which was large,
and the way opened feelingly to labor in the service;
my companion also being largely opened in prayer.
There seems a remnant here concerned for truth`'s prosperity.
At Poneganset we attended their monthly meeting, which was large,
though there is a declension from the simplicity that truth leads into.
It ended to a good degree of satisfaction.
Robert Willis was engaged in prayer.
My companion was much exercised on account of the shortness
that appeared in many in their neglecting to attend meetings,
which he was favored to speak to with much clearness,
and I believe to the comfort of the faithful.
Next day were at an appointed meeting at New Town, which was large,
and attended with close labor,
but through Divine favor we were enabled to clear our minds, and the meeting ended well.
Blessed be the name of the Lord, who has hitherto extended his tender regard to us,
and owned us with the openings of life,
which has been as a staff to lean upon through the
many exercises we have had to pass through.

"`We went from New Town to Redford, and had an evening meeting at Joseph Rotche`'s,
who received us very kindly;
from thence we went to Cushinet weekday meeting--there appeared to be
a remnant who were concerned for truth`'s prosperity in the earth;
from thence to Nathan Davis`'s, and at their week-day meeting, which was silent;
next day, to Rochester, and had a small meeting, to some degree of comfort.
At Falmouth we attended their first-day meeting, and appointed another the next day,
which was to satisfaction; thence to Sandwich preparative meeting.
In this meeting we had to pass through many close trials.
We attended a meeting at Pembroke, to some relief;
at Free Town we stayed with Job Anthony,
who appeared like a kind friend--we attended their first-day meeting.
Here we met our esteemed friend, Thomas Gawthorp, and his companion, Paul Osborn.
We went with them to Evert Chase`'s, in Swansey, and attended their monthly meeting,
and next day their select meeting; thence to Dartmouth,
and had a meeting to good satisfaction; from thence to Philip Tripp`'s,
and attended their preparative meeting at Coaxet,
and their meeting for ministers and elders, all to the comfort of the faithful.
Blessed be the name of the Lord for his many mercies
bestowed upon us from time to time under many probations,
which have often been our portion.
At Little Compton we had close hard labor;
there appeared a great declension from the primitive purity of our religious profession,
though there appeared to be some young concerned Friends, which was a comfort to us.
At the first-day meeting at Tiverton, which was large, and mostly of other denominations.
At Newport we attended their Quarterly Meeting,
where we had hard labor and close exercise,
but through Divine favor we were enabled to discharge our concern.
Thanks be to his holy name.

"`We had many satisfactory opportunities in this Island,
though many hard struggles with some who appeared
to have taken a part in the spirit of war,
to the wounding of themselves and faithful brethren--we were at their meeting for sufferings,
which was also trying to our spirits, by reason of some opposition,
which was to the distress of the faithful.
From thence to Smithfield, in company with Thos.
Gawthorp, Robert Willis, and Paul Osborn, and had a meeting at the old meetinghouse;
from thence to George Smith`'s. The next day we had a meeting at Mendow, to satisfaction;
from thence to Daniel Southwick`'s,
who appears to be a faithful friend and father in Israel; his family also were very kind.
We attended the meeting at Uxbridge, which, I trust,
was to the edification and comfort of the tender ones.
Next day set forward towards our homes, which we reached to the comfort of our own minds,
and that of our dear connections and friends, having been absent several months.
To the Lord be ascribed thanksgiving and praise,
which are due to His worthy name forever and ever.`"

[.small-break]
'''

+++[+++After this, there is no account of his travels, by Journal, until the year 1777,
and about this time, the subject of slavery became a great exercise to him,
and he felt it right to refrain from the use of articles,
the produce of the labor of slaves,
which he adhered to until Friends generally became concerned to liberate them.
In several cases he purchased them in order to effect their emancipation,
when their owners declined to set them free lest they should become chargeable to them.
Whilst travelling he often found the inconvenience
of declining to partake of food used in families,
and felt thankful when the restraint was no longer necessary to his peace of mind.]
