== Chapter V.

Second Visit to Philadelphia,
and Awful Warning to the Inhabitants--Yellow Fever breaks out--Prepares to Visit
Europe--Another Visit to New England--Letter from James Bringhurst--Takes Ship
for Halifax - Escape from Shipwreck--Letters from Remington Hobby and John Tabor.

In the latter part of the year 1792,
David Sands felt a concern to visit Friends in Philadelphia again,
and obtaining a certificate of the unity of his friends with his prospect,
he proceeded to that city, and attended many meetings both for worship and discipline.
In the course of this service he was many times closely proved and tried,
and on one occasion he felt constrained to declare unto them that
he believed that the judgments of an offended God were about to
be poured out upon the inhabitants of that city.

He remarked that "`it is appointed unto all men once to die,
and after this the judgment.`"
"`There is something like death imprinted on all your houses,
in measure according to the value you set upon them,
and which with great care and pains you have erected.
The handwriting upon the wall is found upon all your pleasant walks, beautiful trees,
fine gardens, lofty buildings, and pleasant streets;
and what if these very things which you have taken so much delight in should, in time,
become the graves of some of you; yea, all these things become a ruinous heap,
and some of you be buried in the midst of them, for we know such things have been;
and what sins were there committed in Sodom that are not committed here?
And before very long, according to my present prospect, it must be the case here;
for like causes may produce like effects.
And some of you that have become vessels of wrath
and displeasure in the hand of an offended God,
may be swallowed up in holes in the earth,
part of your bodies in and part out of it and above ground,
for examples or warnings to those who may see it.
And this city may become a stinking hole, and they who pass by may say,
'`Where are all those lofty buildings,
and those pleasant things?`' And what if I should say,
the child is now born that may live to see these things come to pass,
unless there be a turning to Him who hath all power in his hand,
and who can cause the earth to reel like a drunken man.`"

This remarkable testimony was delivered publicly,
at an evening meeting held in the High-street Meetinghouse in Philadelphia,
on the 18th of the 11th mo., 1792,
previous to the breaking forth of the awful and most desolating yellow fever,
the first that was permitted to visit that part of our land, at least of late years.
The disease commenced almost like the plague in violence,
attended in many instances with immediate death.
The alarm was sudden, and the results, in many cases, so fatal,
that for a time medical aid was of little or no avail.
It was the most trying scene ever witnessed in that city.

The conflict and trial of faith which David Sands had to pass through,
in connection with the delivery of the foregoing communication, was very great;
but he was fully aware that omitting to perform what appeared clearly
to be required of him would have been of still more painful consequence.
In the course of his engagement he was concerned to exhort them "`to flee
from the wrath to come,`" and to seek refuge in the Lord Jehovah,
in whom is everlasting strength.

In the course of his ministry, David Sands,
having himself a deep and abiding sense of the mutability of all things here below,
and in the ardor of his soul to warn men against
placing their affections unduly upon sublunary objects,
it was not unusual for him to express himself in language
which some undiscriminating hearers regarded as prophetic,
when such was not his real intention or meaning.
In some cases this has been attended with inconvenience,
the event not answering the expectations thus unintentionally excited.

His ministry was frequently of a searching, awakening character,
attended with a large degree of power and of the Divine anointing.
It fell to his lot to labor much in parts but newly occupied,
bordering on the wilderness,
where he found many of the inhabitants like the parched thirsty ground,
drinking in with avidity the instruction communicated.
Many of them possessed very few opportunities of instrumental
help in their concern for the salvation of their souls.

For several years a prospect of duty opened and pressed on the mind of David Sands,
of his being required to travel in the service of the gospel in Europe.
This concern increased until the year 1794.
In the spring of that year he spread his prospect before his friends, and in the 5th mo.
he obtained a certificate from the yearly meeting of New York to Friends in Great Britain, etc.
He felt his mind drawn to pay another visit to New England,
and then embark from thence to Halifax or Liverpool, as way might open.
But this visit and these labors were ultimately more
weighty and extensive than he had anticipated,
which was at times cause of much anxiety both to himself and his friends.
But though at times very deeply tried,
he found that the only path of peace was to be found in following his guide,
and moving cautiously along in the performance of apprehended duty from day to day.
He was thus enabled to finish his service, before embarking for England,
to his full satisfaction, and had the acknowledgment of the full unity and fellowship,
both of his Friends at home and those brethren amongst whom he had been laboring,
many of whom had been sharers with him in various exercises and arduous
labors for the promotion of the cause of truth and righteousness.

His Journal of these services thus commences:

=== An Account of my Travels from my own Home, on a Religious Visit to Friends in Europe.

My mind having been long exercised with thoughts of crossing
the seas to pay a visit to Friends and others in Europe,
after having obtained a certificate from the monthly and quarterly meetings,
and the yearly meeting of ministers and elders, I set off,
after a tender parting with many Friends, and with some of my own family,
on the 29th of 6th mo., 1794.
My wife and son accompanied me to a meeting in Smith`'s Close,
after which I parted with all but my wife, who remained with me,
and we parted in the morning, after a solemn time in a friendly family.
I proceeded to New York,
taking several opportunities of holding meetings amongst those not members of our Society,
where I met my aged father-in-law and my daughter Martha,
and having spent some time with them, and sought an opportunity of a vessel to embark in,
but finding none that I was easy to go in, I felt my mind turned towards Long Island,
and proceeded accordingly, visiting all the meetings of Friends,
and holding some amongst other people, I believe to good satisfaction.

I rested the 6th of the 8th mo., at the house of my friend John Searing,
having passed through many close trials since I set out from my own house,
which I hope may serve to carry on the work of sanctification,
and prepare and purify me more and more for service.
I wrote several letters to my wife and children, and also to a number of my friends,
and thence proceeded to visit several places,
in company with my much-esteemed friend Jacob Willis;
and as I thought I might now leave Long Island, I came to Newport, Rhode Island,
where I had several meetings; from thence proceeded to Tiverton,
where I met with my much-loved friend James Bringhurst, who was very low in mind,
but was much better before we parted.^
footnote:[The following letter from James Bringhurst will be read with interest:
{footnote-paragraph-split}
My
Dear Friend,
{footnote-paragraph-split}
For such I may truly call thee,
from a sense of thy kindness in coming to visit me,
in my low distressed situation of body and mind,
wherein thou wast made instrumental in raising me in a good degree out of it,
to a feeling of that power which is lastingly good; on which,
if our trust and dependence is wholly placed,
we are supported and enabled to bear up in and through the many
troubles we find by sorrowful experience are allotted to us,
in passing along through this world of danger and of conflict.
May I be kept truly humble under them,
and sensible of the kind hand of Him who permits these afflictive dispensations,
and who yet gives strength and ability to bear them,
to our own improvement.
{footnote-paragraph-split}
I
thought I should be most easy to write a few lines,
and express a little of that sincere love I feel towards thee, my beloved friend,
in which I much desire thou mayst be, from day to day,
favored with a renewal of strength,
and of right qualification to go through the arduous work before thee,
to the honor of our great Master, and the full establishment of thy own peace,
which in the end will happily crown all.
I feel more towards them than I can express;
mayst thou sometimes think of me with desires that
I may be supported through every trouble and danger,
(as there are many in this world,) so that I may hold out to the end,
and then all will be well.
My earnest desire is,
that I may be favored with patience and with resignation
to whatever is permitted to be my experience,
without any murmur or repining,
though sometimes this is hard to come at so fully as ought to be the case.
{footnote-paragraph-split}
{footnote-paragraph-split}
Thy
sincere friend,
{footnote-paragraph-split}
James Bringhurst]

I next proceeded to Providence, where I stayed some time,
and visited my old friend Daniel Howland, who, with his family, were very well,
and Friends generally were glad to see me.
Returning to Rhode Island, I went to a quarterly meeting, in company with J. Mott,
held at Bedford, where I met with my much-loved friend William Rotch,
who had just arrived from Europe with his wife, two daughters, and two public Friends,
John Wigham and Martha Routh.
Here we parted, and I went to Nantucket,
where I spent about ten days to my great satisfaction, and then returned to Bedford,
and so to Longplain, Sandwich, Pembroke, Boston,
and after acceptable service in each place, I proceeded to Lynn,
and so on to the eastward; finding many of my friends glad to see me.

I was at the quarterly meeting at Davom, formerly called Royals Town,
where many had been convinced by my ministry, who were like my children.
At this quarterly meeting I had to look back on the former travail of my soul,
when passing through this most gloomy wilderness, then with few inhabitants,
and those very ignorant of Friends`' principles,
and in many respects an uncultivated warlike people.
Oh, what alterations are made for the better, when the Lord`'s hand is in the work!
I do not see any thing in myself that is worthy to claim any share,
more than as an instrument, and that of a weak kind.
At this quarterly meeting I met with Martha Routh,
on her return from visiting Friends to the eastward;
and here we were favored to put many things in order that were otherwise;
having had much of the Lord`'s presence with us,
we were enabled to conclude our meeting in brotherly love,
and I returned to Dover quarter,
where Martha Routh and I continued laboring in much nearness of spirit,
and having waded through many exercises we were favored
to close in much love and tender regard.
I may say I have had many trying seasons since I have been in this land,
sometimes being silent for many meetings in succession,
and my way in the ministry much closed, though I have no just cause of complaint,
as the least favor is more than I really deserve.
I believe I have been enabled to move so as not to
give any occasion of complaint to my friends.
Since visiting Dover quarter I have been laboring constantly among Friends and others.
The attendant exercises and various trials are not to be described fully,
and as they are often much the same,
I think no great advantage can arise from any endeavor to open them very frequently;
yet I may say, for the encouragement of Zion`'s travellers,
that I believe there is no great cause to fear,
but that if we are sufficiently resigned to the Divine will we shall be carried through,
so that at last we can say, "`His ways are ways of pleasantness,
and all His paths are peace.`"
Many circumstances have turned up,
but to take notice of them all would soon swell the account,
therefore I have omitted naming those families where I put up, as they may alter,
and sometimes I have seen something of pride arise
in families because Friends frequently with them.
I wish to make no remark of any thing that may be
applied to families or meetings to their disadvantage,
as they that are pretty well off in various respects, sometimes soon alter for the worse,
and some that are in low circumstances alter as soon for the better;
so that as all ministers are left to feel their own way,
without anything to mislead them,
they will be most likely to speak to things as they are.

Having spent considerable time at Ware or at Harris Town (where
is a pretty large body of Friends) to a good degree of satisfaction,
I now felt bound towards Amberry, where I made but little stay,
but proceeded towards Boston, taking Salem and Lynn in my way,
where I attended several meetings, generally large, and I hope not without some use.

=== Sails for Halifax.

I was now very much straitened in my own mind as to what I should do; but thought,
under all circumstances, it was best for me to take shipping for Halifax, which I did,
on board a schooner bound to St. John`'s, in Nova Scotia Government.
After being out about three days, in Marble Head Harbor, we were driven on shore,
in which time of trial no tongue can tell what I underwent.
About four o`'clock in the morning,
myself and companion were called to get up and put on our clothes,
to make the best shift we could,
as our vessel was near the rocks and would be on them in a few minutes.
The countenances of the seamen were expressive of the most awful danger.
They stood trembling, saying, "`We are or shall be lost;
there is no hope for ourselves or the vessel.`"
We got our clothes on, and made ready to shift for ourselves.
My dear companion being struck with sea-sickness added to my difficulty,
as he was unable to help himself;
but seeing no way open but by urging on the seamen to exert themselves,
looking unto Him who makes a way where none appears, I ventured on deck,
where I saw all the appearances of immediate death,
as our vessel was dragging towards a point of rocks
whose top appeared higher than our masts,
and so steep that there was no way to ascend them.
In this awful moment I had to resign my spirit into the hands of Him that gave it,
and my body, not only to a watery grave, but to be dashed to pieces against the rocks.
I advised what I thought our only way of escape,
but the master thought it would be of no use.
The storm was violent, mixed with hail and rain, and being dark,
the dashing waves resembled fire, without giving light.
In this situation, I felt so poor I thought I did not feel worth begging for,
but found a little strength to do it for my companion and the poor seamen.
I say so poor, but I may add, so unworthy.
Here our anchor hitched, and held until daylight, which was a favor I had begged for.
We lay within a few yards of the place before described,
and saw ourselves as in the arms of death, when one of the seamen cried out,
"`We are just upon striking; all hands upon deck.`"
At which time, the master proposed to try the measures I had previously recommended,
saying, "`It is only trying, as nothing could add to our difficulty, turn how it would.`"
At which critical moment, we may say, we were snatched from the arms of death.
The mate said there had not been such a time before, as the wind favored us two points,
and as our vessel wore round under her jib, having cut one cable and slipped the other;
her stern struck, as we suppose, twice,
while the dashing of the waves carried away our boat.
Thus we escaped,
without any other prospect than that of running her
ashore in some place where we might save our lives.
I was obliged to stand by and assist what I could, though I fell several times.
We soon arrived at a place to run ashore.
I cannot describe the joy that filled every countenance,
notwithstanding the sea was breaking over us in a most violent manner,
and our vessel trembled as if she would burst in pieces every moment.
After the storm had subsided a calm ensued,
and our friends came alongside of our vessel with a sleigh, and took us out.

On leaving the vessel we returned to Salem, and after a short stay there we went to Lynn,
from whence, after recruiting again, with the advice of my friends,
I proceeded towards the eastward on horseback, taking meetings as they fell in course,
and appointed many others.
The journey was very trying to my feeble constitution, and I had a heavy cold,
yet continued our course towards Kennebec, where we arrived 5th mo.
9th, 1795, and found things greatly altered since my first visit,
being now a pretty large monthly meeting,
where there was not the face of a Friend to be seen when I first visited the country;
but rather a hard warlike people, addicted to many vices, but now become a solid,
good-behaved body of Friends.

After paying a pretty general visit here, I set forward, still eastward,
intending to go to Penobscot;
from which place I expected to ship either for Halifax or Europe,
and having had many meetings in the way, and in some places where I had travelled before,
wherein I thought the power of truth was felt, to the convincing of many;
and I believe that amongst them there are divers who will stand as seals to my labors.
I have had in this part of my journey my much-loved friend Remington Hobby,
a man of a good gift in the ministry; and having now accomplished my service,
took leave of many tender people in great brokenness of spirit,
as also of my dear companion, Joseph Wing, who had borne me company near nine months,
in which time we were so nearly united to each other that
not one hard word or thought had taken place between us.
Parting also with my companion and fellow-laborer, Remington Hobby, was very trying,
being now left to go on board amongst strangers,
having taken my passage to Liverpool on board the ship "`Two Brothers.`"

The following letters by Remington Hobby,
written to David Sands after his departure for Europe,
are expressive of his feeling towards him.

Well-Beloved Friend--

A few hours since I heard of an opportunity by which
I could have the comfort of writing to thee.
My dearest friend and father, though my heart seems destitute of good,
I cannot omit embracing it; and am instantly led to look at the solemn, yea,
very solemn period of our parting,
which so continued to shed over our minds a solemnizing awe that on our return,
for five miles, we scarce broke silence; but oh! my friend,
although I powerfully felt what I now write, why was it that my heart ached with anguish,
yet I could not weep; I seemed to look at thee as solitary and alone in the cabin:
yet surrounded by Him on whose great errand of glad tidings thou art sent,
with a promise of sure reward and a bright crown of glory prepared by Him,
for his faithful and obedient servants.
In looking over our journeying,
I am sorrowfully affected with a fear that thy anxious and tender concern,
(as that of a most affectionate and pious father for a son,) in the renewed
instances of thy indefatigable care for my growth and preservation,
will fail of those happy effects which it seems might have been expected.
I have been ready to conclude I have not prized thy society or encouragement,
and sometimes feel as if I was a poor unfruitful creature,
though I earnestly desire that, having sinned much, I may love the more.

I am sensible that I need more and more to be refined,
and feel the necessity of looking through all that is visible to the invisible God,
and beg that I may have no confidence in the flesh.
Oh! my friend, if we are never more permitted to meet in mutability,
may the Merciful Preserver engage my heart so to act that
we may ever enjoy each other in the realms of joy,
where nothing can annoy our rest.
When thou hast access to the throne of mercy,
mayest thou be encouraged to ask for me an increase of faith,
that I may have a seal and testimony that I am a true son,
and although born out of due season,
I may yet be gathered with others into the fold of rest; but, dear David, I desire,
though ever so poor, not to clothe myself with unfelt expressions,
or higher notes of dignity than becomes that abasedness of spirit which can say,
"`I am a worm;`" in which disposition of mind I wish only to say to thee, spare me not;
never suffer partial affection to supersede the testimony of truth,
whether it be the rod or in love,
and believe me thy friend in that love that changeth not,

Remington Hobby.

The following is an extract from another of Remington Hobby`'s letters,
setting forth the love he bore to David Sands, as also his devotedness to truth,
fearing lest the messenger bearing glad tidings should not tarry
long enough in the field of service to see the fruits of his labor:

In those seasons wherein heavenly power has seemed to silence all flesh,
I have often ventured to say, concerning my dear friend and father who is absent,
if I may be allowed the expression, "`Let him see of the travail of his soul,
and be permitted to rejoice in thy presence.`"
I dare say no more, nor indulge a wish for thy return.
I know not whether it is owing to ingratitude to my most faithful friend.
Yet so it is, I would rather be forgotten of thee,
and that thou shouldst write me no more,
than to omit thy duty to a single individual on the other side of the water.
Take all the time the Lord allows thee, let others think or say what they will.
If their gifts or labors differ from thine, so may thine differ from theirs.
Which has most the criterion of righteousness--that which makes
haste through fear of breaking the tradition of the Elders,
or that which, beholding the husbandman`'s care,
is willing to wait for the precious fruits of the heavenly Canaan,
and hath long patience for them?
Seeing to the confirmation and establishment of the convinced, as did the Apostles,
when they said,
"`Let us go again and visit our brethren in every
city where we have preached the word of the Lord,
and see how they do.`"
Something of this, thou devoted servant of the Most High God,
thou mayst see and feel that may escape the notice of some others;
and if thou shouldst presume on other conduct, I think thou wilt smart for it,
and perhaps have to cross the ocean again.
My wife and family all love thee,
and I doubt not all Vassalbo rough would unite in love to thee,
did they know of my writing.
May we, in the Lord`'s time, be gathered into the fold of everlasting rest, so wisheth,
so prayeth, and more than all earthly happiness desireth, thy sincere loving friend,

Remington Hobby.

The following letter to David Sands, from his friend John Tabor,
was written about this time, though it reached him after his arrival in England.
It evinces much brotherly sympathy with him under the many
and varied trials which fell to his lot about this time,
and also bears witness to the high estimation in which his ministerial labors
were held by those who had the best opportunity of observing their effects,
and the evidence of the Divine power and authority
with which they were often eminently accompanied:

Vassalborough, 8th mo.
6Th, 1795

Dear Friend, David Sands,

It is in much brotherly love and near sympathy that I salute thee in this way,
feeling that near fellowship that distance cannot quench.
Although it did not seem to be my lot to travel much in body with thee,
whilst within our borders, yet in my small measure, I did travail in spirit,
and have to rejoice that thy labors have been greatly blessed in our parts,
divers having been convinced by thee as an instrument,
and many of them appear very hopeful.
But may we ever remember that though "`Paul plant and Apollos water,
it is God that giveth the increase,`" to whom may
we ever ascribe all the honor and praise,
and nothing to self, but that we are poor unprofitable servants.

After remarking on David Sands`'s long detention before embarking for England, he adds

I wrote to Robert Benson,
and informed them of thy uneasiness with thy detention in our land;
and that I hoped that the oldness of the dates of thy certificates
might not hurt or lessen thy service in their land,
as I was fully persuaded that thy detention in our parts was by Divine direction;
and that thy labors, especially among those not of our society,
had been remarkably blessed by Him who had called thee to labor in His vineyard;
which has been cause of humble thankfulness to many,
who I believe could set their seals to what I have
written respecting thy detention in our parts.

I came from Portland in company with Deborah Darby, Rebecca Young, and William Rotch:
their labors have been very acceptable.
They had two meetings in our meetinghouse,
which I believe will not soon be forgotten by some.
They have been to see thy family,
and were much comforted in feeling that the Great
Master`'s presence was near to them in thy absence.
Joseph Cloud is expected here in a few days,
and I think he will not get out of our eastern parts suddenly,
as he seems to be led much as thou wast, among those not of our society.

I received thy acceptable letter by our friend Remington Hobby, who, I think,
has made considerable improvement, and probably will not be long at home.
I shall be willing to accompany him in travelling the ground over again,
where he and thou have been.
I feel more and more of late that it is my place so to arrange my business
as to be more at liberty to accompany my friends on religious visits,
and in a particular manner my dear friend, Remington Hobby,
who I believe the Great Master is about to call to more labor in His vineyard.

Speaking of his own family, he remarks--

I hope and believe that the close trial they met with in
our absence will prove a blessing to some of them.
It was quite a comfort to my wife and me to find they had
mostly conducted to good satisfaction in our absence,
and a lively concern appears to rest on some of them to come up in faithfulness,
which I esteem a great favor.
With near love and sympathy, thy assured friend,

John Tabor.
