== Chapter VI.

Voyage to Liverpool--Advice to his Children--On the Inward
Witness--Letters from James Neal and Jonathan Dow.

=== Voyage to Europe.

Thirteen months after leaving his own habitation, he thus proceeds with his Journal:
"`On the 23rd of the 7th mo., 1795, I went on board the ship Two Brothers,
bound for Liverpool, since which time we have had dull foggy weather,
so that our progress is slow.`"

He next describes a peculiarly deep and distressing
baptismal conflict with which he was overtaken,
perhaps to prepare him for some of those services which afterwards fell to his lot,
and in which he had to deal with some who were so far deluded as to seek
to subvert the very foundations of the Christian`'s faith and hope,
even denying the Lord who bought them,
and holding the Scriptures of truth in very light estimation.
Very mysterious are the Lord`'s dealings with his servants and ministers,
in order to fit and prepare them for such services as he sees meet to
call them to perform for the manifestation of His own power and glory,
and the instruction of His children, amongst whom they are called to labor.
He thus describes his conflicts:

I have had two meetings on board, to some satisfaction.
About the 8th mo.
2nd, I was taken unwell, and continued so for about ten days,
in which time I had many deep trials of mind,
I believe beyond what I ever experienced before, being now amongst strangers,
whose dispositions were not of the most feeling kind, and withal,
no sense of any supporting arm near that I could rely on.

I was reduced to that state that I gave up all,
and saw no other way but that I must submit to death, and be buried in the ocean.
After having been in this condition for several days,
I became apprehensive that my senses would depart from me, which was an additional trial;
yet I was so far preserved as to keep my state of mind to myself,
which I apprehended many times I should not be able to do,
as I sometimes seemed as though I should cry out through anguish of mind;
but having given up all hope,
and now only wishing to hide my miseries as well as I could,
and if the sea was to be my bed to make the best of it,
and so I concluded all would be for the best.

I walked upon the deck of the vessel, and being retired in deep thought,
I felt a little hope spring up, but had no relish for any alteration,
having now settled matters in my own mind; but as I could not command help,
so I could not refuse it when it came, therefore, retiring into the cabin,
while sitting and viewing the alteration I felt, and thinking what could be the cause,
and feeling a fear of being deceived, I durst not touch what seemed to be offered.
I now felt an increase of draft towards looking into the Bible, and, taking it up,
and opening it, without any intention towards any particular place,
I cast my eye on the 20th Psalm, "`The Lord hear thee in the day of trouble,
the name of the God of Jacob defend thee.`"
I seemed to feel my mind drawn to read it, with which I felt a little hope spring up,
having before given up all expectation of any more satisfaction
either in what I had done or should ever be able to do;
but as this was pressed on me I was made willing to comply;
and as I began to read all my troubles seemed totally to disappear,
and my faith was raised beyond what I ever had experienced before.
And I thought the Psalm seemed to be applied to myself, "`The Lord is my shepherd,
I shall not want,`" when looking on the 23rd, I thought I must read that too,
which still increased my strength, and spread a calm over my deeply afflicted mind;
on which I retired to bed, and after lying down awhile I began to doubt,
through reasoning; and, getting up, I went on deck,
where I still remained in some doubts, and the wind being now against us,
as it had been most of the passage, I was ready to say,
how shall I be certain that what I felt and thought I saw is true,
when it seemed like a voice spoken intelligibly, "`The wind shall suddenly change,
and continue fair until thou arrives at land,`" which again brought me into quiet.
I laid me down again,
and had not lain but a few minutes before the man at the helm cried out,
"`A fair wind,`" which continued,
so that we went but little out of our true course until we saw Cape Clear, in Ireland;
though, I may remark,
that when the wind changed it soon began to blow
so hard that the sails were necessarily furled,
and by day we were obliged to scud under a close-reefed topsail and part of the foresail.
The wind was very fair, but violent, for forty-four hours,
so that we put in our dead-lights and burned candles.
Our ship being so under water that we could cook nothing,
and with much difficulty could we cross the cabin,
the ocean being in a most dreadful motion,
and the wind so strong as to blow off the tops of the waves,
that made it resemble a very driving snow-storm.
But my mind now was quite easy,
and my body seemed to gain strength even when feeding
on a piece of raw meat and a bit of hard poor biscuit;
for thus the Lord makes hard things easy, and bitter things sweet,
when we abide in the patience.

In passing Ireland everything appeared beautiful,
as we sailed near it for more than one whole day.
We saw the towns and fields of harvest, until we fell in with Wales,
where we had the like pleasant prospect,
until the pilot came on board to carry us into Liverpool,
where I arrived in thirty-nine days after my embarking.
Being the first day of the week, about eleven o`'clock in the forenoon, when I landed,
I went directly to the house of our beloved friend, Robert Benson,
who was then gone to meeting with his wife and family, a maid being left,
who told me I was expected soon.
She got some refreshment for me, and I being weary I lay down a little while.
When the Friends returned, they met me in much love and affection,
and very kindly welcomed me to their house.
In the afternoon I went with them to their meeting, in which I had something to offer,
which seemed to give relief to my mind.
And to see a meeting of Friends after such a long confinement, and again to be on shore,
seemed to be more than I could bear without weeping for joy.
I had not been at a Friends`' meeting, where Friends were settled,
for more than three months.
I was much refreshed during my stay at Liverpool,
where I remained from the 2nd to the 8th of 9th mo., 1795, visiting some families,
and writing home to my own family and friends.

In the course of his late voyage,
David Sands evinced his concern for the improvement and welfare of his
own children by writing some instructive hints for their government,
which are thought worthy of preservation here,
and possibly may be profitably read by others.

=== David Sands`' Advice to his children, Written at Sea.

Ship "`Two Brothers,`" 8th mo., 11th, 1795.

Having felt some secret drawings of spirit towards my dear children,
and not knowing certainly that I shall behold all or any of them again,
I think it right to employ some of my leisure hours, whilst confined on board of ship,
in leaving some remarks and advice that have or may
arise in my mind for their perusal and service.

Inasmuch as it is appointed unto all men once to die,
and after death to appear before the judgment seat of Christ,
to receive a reward according to what their works have been here on earth,
it ought to lead us with holy care and circumspection, not only to number our days,
but diligently to scrutinize all our thoughts, words, and actions,
that fill up and occupy our time, in order that we may see the state of our accounts,
as in the Lord`'s sight;
inasmuch as nothing can escape the knowledge of Him with whom we have to do.

I may here lay before you, my dear children,
those well-adapted and beautiful passages of the pious King to his son,

"`Be thou in the fear of the Lord all the day long, for surely there is an end;
and thine expectation shall not be cut off.`"
"`Hear thou my son, and be wise, and guide thy heart in the way.`"

The directions you will expect from me naturally divide themselves into three parts,
viz., "`How we are to remember God in the beginning, in the progress,
and to the close of the day.`"
I will open my heart freely to you with respect to each particular,
and leave you to judge how far these hints may suit
your circumstances or accord with your inclination;
desiring to avoid every extreme, both that of superstitious strictness in trifles,
or of an indolent remissness; which, if permitted to prevail in little things,
may soon draw after it criminal neglect, and at length more criminal indulgences.
In the beginning of the day it ought certainly to be our
care to lift up our hearts to God as soon as we awake;
and on rising from bed,
to endeavor to have our minds brought into seriousness and stillness;
to thoughtfulness as in the Divine presence;
for this is a season when there are many considerations which may, or ought,
to suggest a variety of pious reflections and ejaculations,
which are so obvious that a mind inclined to piety could hardly forget or miss them.
The cheerfulness natural on our first awaking; the refreshment we have found from sleep;
the security we have enjoyed during that defenceless condition;
the enjoyment of witnessing once more the reviving influence of the sun;
the recollection of the many comforts and conveniences which we have enjoyed or received,
and are surrounded with, so graciously provided by the great Author of all our mercies;
and now, having the prospect of one day more, not only to see our dear connections,
but to serve our heavenly Father, whose service is freedom and whose labor is love;
and continued opportunity for the improvement of our minds; and, above all,
cherishing a lively hope of finally witnessing a perfect
resurrection to an eternal day of happiness and glory.

If we have our hearts in such a state as to long for further improvement
in a still nearer and more humble approach to the Divine footstool,
accompanied with desires to maintain a closer walk with the Lord;
this itself is matter of thanksgiving and praise;
and the rather if it may be regarded as the answer of the
prayer with which we lay down the preceding evening.
The exercise of private devotion in the morning I hope you
will engage in as the first work of the day,
yet I cannot prescribe a particular method to any of you, my dear children.
Consult the witness for God in your own hearts.
The constituent parts of duty are generally plain, as are our common mercies;
and sometimes special favors are manifestly great,
and consequently call upon us for corresponding services,
with humble and grateful acknowledgments to Him who is the bestower of every good thing,
whether temporal or spiritual.

It may now be proper to take a view of the day before us.
So far as we consider, yea seriously consider, how and where it may be spent;
and once more deeply think, how shall I employ myself for God this day,
what business is to be done, and in what order;
what opportunity may I expect either of doing or receiving good;
that so we may carefully mark the providences of the day,
and carefully guard against the temptations incident to it;
that we keep up a lively humble dependence upon Divine influence,
which is suitable to every emergency;
that we govern our thoughts well in the solitude of the day,
and our discourses well in the conversation of it.

Having proceeded thus far, may I now offer some hints further respecting devotion.
It certainly ought to be performed with great seriousness, whether public or private;
therefore let us take a view of it before we enter upon such solemnities; which,
though they be performed here on earth,
yet are connected with the invisible realities of another world:
and in order to increase a suitable reverence of spirit, in the improvement of time,
and the proper discharge of every part of our duty, let us often take into view,
as far as we can, the divine perfections of that glorious Being whom we profess to serve.
And let us guard against every wandering thought,
and maintain a strict watch over our own spirits,
especially when we attempt to enter as into the immediate presence of God;
and when we have performed our duty, as we suppose, let us not be deceived,
but keep a strict eye on all the various duties of the day,
for as our blessed Lord Jesus Christ declared,
we are no longer safe than whilst on the watch.

The following remarks on the Inward Witness were found among the papers of David Sands,
without date, and may perhaps be usefully inserted here,
previous to the account of his Gospel labors in Europe.

=== On the Inward Witness.

"`He that believeth on the Son of God hath the witness in himself.`"
--1 John 5:10.

Many and glorious are the outward testimonies that God has given to the Christian religion,
both in the days when His Son Jesus Christ dwelt on earth
and went about doing good to the bodies and souls of many,
and in the time of the ministration of the apostles, who followed their Lord and Master.
The miracles wrought, the prophecies fulfilled,
and the various glories attending the ministration
of the Gospel conspire to confirm our faith.
Each of them are evidences of the truth and divinity of this doctrine,
and all of them joined together, bear such a testimony as cannot be resisted.
We live in these latter days at a long distance of time
from those seasons wherein those miracles were wrought,
and wherein God appeared in so immediate a manner from heaven
to witness to the truth of the Gospel of his Son;
but God has taken care to furnish every true believer with
sufficient witness to the truth and efficacy of Christianity.
We are not left void at this day.
"`He that believeth hath the witness within himself.`"
There is an internal testimony given to the Gospel of Christ
in the heart of every one that receives it in truth.
These are the beginnings of that eternal life wrought in the soul,
which the Son of God bestows on all believers: "`He that hath the Son hath life.`"
Oh, the spiritual life of a Christian runs into eternity!
It is the same Divine temper, the same peaceful and holy qualities of mind,
communicated to the believer here, in the days of grace and visitation,
which shall be fulfilled and perfected in the world of glory.
And this is a blessed witness to the truth of Christianity;
it proves with abundance of evidence that it is a religion sufficient to save souls,
for salvation is begun in all that truly receive the good tidings of it.
What sort of witness is this which true faith gives to the Gospel of Christ,
and what are the remarkable properties of this testimony?
I answer, it is a witness that dwells more in the heart than in the head;
it is a testimony known by being felt and practised,
and not by mere reasoning--the greatest reasoners may miss of it;
it is a testimony written in the heart,
and upon this account it has some prerogative above all the external arguments
in favor of Christianity--this inward argument is always at hand.

[.asterism]
'''

The following letter, from James Neal, belongs to this period of time,
and bears evidence of the continued warm attachment of those amongst whom he had labored:

Killery, 12th mo.
9th, 1795.

My Dearly Beloved Friend and Brother in the Gospel--

As thou art very far separated from all thy dear connections in this life,
and now in a distant land, I greet thee well in this silent way,
and rejoice with many more of our friends that thou art safe arrived in England,
in health, and moving forward in thy Master`'s cause.
I believe thy journeying will be blessed to thyself,
and also to those where the Divine Parent of all shall see meet to send thee,
as thou hast left all to gain all.
But, dear brother, remember that tribulation is added to the promise of an hundredfold;
but what crowns all is, "`that in the world to come is eternal life.`"
Thou knowest, dear David, how we have journeyed together in love; in hunger, in cold,
in the winter season, and sometimes in dejection of spirit;
yet we were taught to know that the Lord`'s mercies continue to be over all His works,
and His good presence is sweeter than honey,
and He indeed continues to be the best paymaster.
I did not think it my duty to crowd thy pockets with letters;
but I loved thee beyond expression by pen,
as I have been a sharer of the great love of God through thee as His ambassador.
Thousands in our land have cause to love thee unfeignedly,
and to glorify God on thy account; and though we be thousands of miles separated,
as to the body, yet, dear brother,
may we know a participation of refreshment in the one spirit.
May the Divine Shepherd continue to supply and feed thee as with His sweet presence,
by which only thou canst be abilitated to feed His sheep and lambs in a distant land.
May thy labors be blessed, keeping in the faith;
which is the substance of things hoped for,
and sweetens the mind with the evidence of things not seen.

Andrew Austin and wife have been to see thy wife,
who informed them of the welfare of thy family.
She appeared comforted in resignation to the Divine will,
in giving up her dear husband in so good a cause,
and has participated with thee in thy joys.

As thou wilt have access to the Throne of Grace for
the welfare of thy dear wife and children,
forget us not, dear David, in this land where thou hast labored night and day,
in the love of the gospel.
My petition is, that God Almighty may continue to bless thee;
fit and prepare thee for his own work.
He who makes the clouds his chariot, and walketh as on the wings of the wind;
who makes his angels spirits, and his ministers as a flame of fire, and that of love;
and thou knowest that nothing destroys in all his holy mountain.
And if we never see each other again,
oh may we be filled with spiritual blessings in Christ Jesus,
and close our days in the joys of God`'s salvation, by and through his dear Son.
So prays thy affectionate friend,

James Neal.

[.asterism]
'''

Dover, 12th mo.
11Th, 1795.

Dear Brother--

These, with my kind love.
I am glad to hear of thy safe arrival in England.
I heartily wish thy welfare and preservation in the truth,
and that the Shepherd of Israel may be with thee in thy journey,
and support thee in all thy travels, and bring thee to thy family and friends again.
My prayer and sincere desire are for thy welfare.
I conclude,
thy real friend and brother in the fellowship of the gospel of the dear Son of God,
and bid thee farewell.

Jonathan Dow.
