== Chapter X.

[.chapter-synopsis]
* Arrival at Congenies
* Giles`'s
* Nismes
* Return to Paris
* Dunkirk
* London
* Letter to M. Linskill
* To Isaac Cooke

3rd mo.
12th.--Reached Nismes, where we lodged, and finding none of our friends there,
after paying a visit to the mother of John de Marselac, who is now in America,
we took a conveyance to go to Congenies, which we had travelled so far to see,
and where we arrived 3rd mo.
13th. Lewis Majolier came to the Inn and took us to his house,
where we met several of those called Friends, who were pleased to see us.

To express the feeling and exercise attending my
mind since I left Paris is out of my power;
but this I can say, the Lord is good,
and his lovingkindness has been abundantly and renewedly
manifested to me from time to time;
and I have been strengthened beyond my expectation;
having travelled in rains and all kinds of weather, and been preserved from taking cold,
or being otherwise indisposed so as to lay by one day,
and am now in better health of body, and more peaceful in mind,
than I have been since being on the Continent.
The hope of being soon at liberty to return to my friends in England, and,
if the Lord permit, to my family in America,
affords me a sweet comfort beyond what words can set forth.

The state of the friendly people here whom we came to visit appears low at this time:
many have flinched from the religious profession that they once made,
during the present war;
yet there remains a small number who appear concerned for the cause of righteousness,
who are made near to us in Gospel love;
and a hope remains that many of the scattered ones will be again brought to the fold;
and that the Lord will yet raise up a people here, who shall show forth his praise.

3rd mo.
14th. We had a meeting, where most of those who had been considered friendly attended.
Both William Savery and myself having something to offer, though in a broken manner;
as there were none who could interpret for us except my young friend, Benjamin Johnson,
who, understanding a little French, assisted another Friend,
who could speak a little English;
so that the substance of what was delivered was not lost.
After we had relieved our minds, Lewis Majolier spoke at length to them; and after him,
another arose and took off his hat, which had a cockade on it; he also had much to say,
and was followed by an ancient Friend, who spoke for a length of time;
and though it appeared singular, a solemnity seemed over the meeting,
and we were favored to part in much nearness of heart.
We spent most of the next day in visiting families; though we could say but little,
yet something very solemn attended, and they were often much broken.
We found about fifteen families who called themselves Friends, whom we visited,
which occupied our time until first-day, the 19th, when we had two meetings,
attended by about seventy persons.
We prepared in writing what we wished to say:
we had it translated and read at the close of the forenoon meeting,
which affected them much, and the meeting parted without much more being said,
except by their own members.
The afternoon meeting appeared still more solemn,
as there were many things brought forth of which they gathered the substance;
we parted again in a very tender and broken manner.
We found that in their troubles, during this present year,
they had dropped three monthly meetings; which brought an exercise over our minds,
and a concern to propose the reviving of them again;
this we found many of them desirous of; and having proposed the time for the meeting,
there came about forty of those they called members, who appeared solid.
None of them were plain in their dress, so as to hold up our testimony in that respect;
yet they acknowledged the propriety of it,
and seemed under some concern for an improvement in that and other respects;
so that a comfortable hope was experienced that they would make such alterations
as were necessary for their own present good and the honor of their profession.
They are a very kind hospitable people, though generally in low circumstances,
and we felt much sympathy for them.
They live in a very beautiful valley (the mountains lying
on the north and east) which is under cultivation with vines,
almonds, olives, and figs,
which affords a beautiful prospect from the small adjoining mountain.
We saw mountains covered with deep snow, while others were in a flourishing state.
South of the village, we had a view of the Mediterranean sea.
They work in the sides of the mountain with great labor and pains:
it is said the best olives in France grow there.
The people here keep no cows, but are supplied with milk from the sheep and goats.

Having done what we apprehended was our duty,
we took leave of our friends in much nearness of spirit,
recommending them to the Shepherd of Israel;
as not expecting to see them again in this world;
and I felt a full reward for all my trouble.
I may, in much humility, mention that, before we took leave,
I felt drawn to supplicate the Great Father of the family, which was a new trial,
as there were none to interpret; having submitted to the intimation of the Divine will,
I thought I had seldom had more strength given, and the people appeared much affected;
so that the Lord works by his Spirit when and as he pleases,
even where the words spoken are not understood by the outward ear.
We parted from these tender people after spending eighteen days with them,
being a longer time than we intended;
having been detained by the illness of our young friend Benjamin Johnson.
The Lord was pleased to raise him so far that we
felt it safe to leave him a few days to rest,
and to meet us at Nismes.

3rd mo.
30th.--We left Congenies, and reached Giles`'s near night,
travelling over a very rough way, which fatigued me very much,
as my horse was poor and myself feeble.
We were conducted by our friends to the house of Peter Massignon,
who received us very kindly; several others soon came, who call themselves Friends,
though they had no appearance of it by their dress, yet seemed very glad to see us.
In the evening we had a meeting with them,
where about fifty very sober kind of people attended,
who seemed acquainted with sitting in silence.
The meeting seemed to be owned by the Lord`'s presence,
and several short testimonies were borne, though I felt it my place to keep silence,
as I have done most of the time since I have been here; the meeting parted solidly.
We visited some of them in their families, which was a time of favor.
Next day we had two meetings; that in the morning was attended by about seventy persons,
and several testimonies were borne.
One by a young woman, Mary Ventigole, who had acceptably appeared in the ministry;
and two of them were lively in their gifts.
They seemed to have a very great influence on the people.
Our meeting in the afternoon was not quite so large, but appeared to be a tender time.
In this meeting I felt drawn to prayer;
it was a season that greatly refreshed my deeply-tried mind;
and though the people did not understand my language,
yet they felt their hearts humbled much; and soon after I arose, a young man appeared,
in ministry, in a very tender broken manner, it being the first time,
and the assembly was much affected.
Thus our meeting was crowned with life,
and we parted under the solid covering that had been felt to be over us.
In the evening we assembled a few of the most concerned men and women,
to lay before them some things affecting their society,
which they seemed willing to take into consideration.

4th mo.
1st.--This day being wet, we have not been able to get out;
but at seven o`'clock in the evening had a meeting, which the most of them attended,
and we were favored to feel our minds measurably
baptized by the one Spirit into one body;
and after opening our prospects to them,
respecting the necessity of keeping up their meetings in the authority of truth,
they appeared sensible of the necessity of dwelling near the Fountain of Life.
We then felt easy to inform them that we intended leaving the next morning,
when most of them came to take leave of us.
It was a season in which our hearts were tendered, not expecting to meet again.

Proceeded three leagues to Nismes.
This city has many places of antiquity.
That which most particularly struck my attention was one said to
have been built forty years before the birth of Christ;
and one other building, which appears very ancient, as the pillars, though of hewn stone,
were much wasted by time.
Here is a fountain which rises at the foot of a mountain
that lies on the west of the town,
and affords an abundance of water, which runs through the city:
it is about three rods wide and five feet deep.
This appears to have been a place of great repute in the time of the Roman government,
which was its most flourishing period, more than a thousand years since.
We here met with several people who treated us respectfully.
We parted with our friends of Giles`'s at Nismes,
who had stayed with us in much nearness of spirit, and proceeded on our way.

We reached Lyons 4th mo.
9th. Here we tarried two days, for Benjamin Johnson to recover his health,
which he did sufficiently to travel.

The country, since we left Lyons, looks very fine and highly cultivated;
the valleys spread wide, and are the most beautiful I have seen in France.
The cities and villages are near each other, and all seem flourishing.
Having pursued our journey, as Benjamin`'s health would permit;

4th mo.
20th.--We arrived at Paris, where we again met with our former friends,
and I believe we were rejoiced to meet again.
After staying a night there, we laid our intention of leaving before the American Consul,
who engaged to provide us with a passport, and forward it to Dunkirk.

On the 25th, we left Paris, after having taken leave of several of our countrymen,
amongst whom was a kinsman, a son of Comfort Sands.
On our way, we met with an Englishman, who invited us to his house,
as we could go no further, owing to our carriage having given way.
We found him of an open disposition, but in his principles he inclined to Deism.
He signified he wished well to all men, but as to a hereafter,
he did not trouble himself about it.
We proposed having a meeting, as there were several Englishmen there;
but he thought it would not be expedient at that time,
considering the state of the French nation; as they were living among them,
and they were already very jealous of them.
We tarried until the next afternoon.
He invited us to take breakfast and dinner with him, which we accepted;
and took a walk with him to see the seat of the Prince of Conde, who had fled,
during the troubles, into Germany.
The situation and buildings, I thought, exceeded any thing I had seen in France.
It looked as though nature and art had united to render this place every way desirable;
the waters around it, with an abundance of fish; the various walks winding through woods,
with beautiful plains and delightful meadows, all unite in one view,
rendering it desirable to possess, and highly pleasing to look upon.
Yet, what is it, when compared with the expected joys of an eternal inheritance,
when the honors and distresses that attend the things of this world are felt no more?
This place now lies desolate,
though some part of the estate is occupied by our aforesaid friend, whose name is Potter;
he carries on the making of china, and many other branches,
and has in his employment about one hundred men.
We found several here who were called Quakers, who have come from England.
We left some books with them, and took leave,
after having a little to offer by way of advice, of a religious nature.

4th mo.
24th. We arrived at Dunkirk much fatigued:
having travelled seven hundred miles with but little stopping,
we were glad of a little rest, but my prospect was to go to Geneva.
I felt but little satisfaction or rest here; yet as I did not act in wilful disobedience,
and as Benjamin Johnson had been long sick,
and William Savery under the necessity of keeping with him, we came to this city,
where we have been waiting for an opportunity to get back to England.

We have had two meetings that were in a good measure favored seasons,
to the renewing of our strength, and that of the few Friends in this place,
and some others who attended the meetings.
We waited many days before receiving any passport;
during which time we had several meetings to general satisfaction,
A way was opened for us beyond our expectation,
as the mayor and some of the principal people became concerned for us;
and after proposing many plans with which we could not feel easy,
such as passing under the names of others (which
was frequently done) in order to get away,
as no vessel could leave for any English port.
However,
we could not feel easy without letting the magistrates
know it was our intention to go to England,
if we could get there; that we would not clear for any port;
only wishing to go on board a ship to get out of their ports,
which was not taken ill by him; but seeing our uprightness,
they were the more loving towards us, and made matters so as to be quite easy to us.

5th mo.
14th.--We left Dunkirk with Captain Johnson, who agreed to land us in England,
where we arrived the next day, after a pleasant passage;
but we soon perceived that we had a new trial to encounter,
as the captain told us he was obliged to land us in the night or secretly;
as it was against the laws to land any from France.
We objected to proceeding in this way, and while consulting what course to pursue,
a small fishing boat came alongside;
and we agreed with the captain to land us at Margate;
or if they objected to our landing there, to carry us to Gravesend.
We therefore left the ship; and the fishermen landed us at the former place, where,
being examined by an officer, we told him our business and from whence we were come.
He said we could not land, and that the boatman who brought us was liable to be fined.
We told him we had no intention of landing contrary to law, which made him easy.
Several of our friends came to see us,
particularly a young woman with whom I had before a near acquaintance.
They were very anxious for our landing, but considering our delicate situation,
we chose rather to go to Gravesend.
Our dear friends gave us up, after furnishing us with some necessaries,
which we stood in need of.
After a trying passage, considering that we had scarcely a place where we could lie down,
through the goodness of the Lord we were favored to land safely next day,
about ten o`'clock.
After resting a short time, (having left our dear friend Benjamin Johnson at Margate,
where he was permitted to land as he was very sick) we took passage to London,
without any questions being asked, where we arrived 5th mo.
16th, 1797, and were received with much openness by our beloved friends.

The following letter, addressed to M. L. of Whitby,
affords lively evidence of the humble yet confiding frame of his mind at this time,
in the review of his Continental travels:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 6th mo.
5th, 1797.

[.salutation]
Dear Friend--

Our beloved friend George Saunders being here,
by whom I have been informed not only of thy health,
but of many others of my near friends in the north,
which has afforded me much satisfaction.
I have been favored much as to my health since I left England,
and am at present much better than when I was travelling in the north of England.
I often think of thee as a sister who has been made near in the best sense, and who,
I believe, travails with me in desire for the prosperity of truth.
I sometimes find my mind turned to look towards Whitby,
and I think it may be possible that I may break bread under thy roof; but as to the time,
I must leave it for the present.

I may inform thee that I met with much openness in many places, when on the continent,
amongst different nations and classes of people; so that, in looking back,
I feel a comfortable hope that I have not run wholly in vain;
yet have abundant cause to reflect on my own unfruitfulness and unworthiness;
but I am supported so as to move forward as way may open,
in humble hope that I shall be as one accepted; if not for my own sake,
for the sake of the Beloved of souls; in whose name, and by whose righteous Spirit,
I expect to be justified.

I lately heard from my family, who were all well, and, I believe,
endeavoring to do well every way.

Dear George Saunders is waiting, and meeting time near; I must therefore conclude,
and in near affection and tender love to thee and Friends in Whitby,
I do desire that the Lord may bless both thee and
them with the choicest blessings of the goodly mountains;
that, under his care and protection, we may all journey forward;
and at last be admitted into those beautiful mansions,
where the morning stars sing together, and all the sons of God shout for joy.--Farewell,
my dear sister in Gospel fellowship: thy affectionate brother in Christ,

[.signed-section-signature]
David Sands.

--

The following extract of a letter from David Sands to Isaac Cooke, of Manchester,
though not in the order of date, yet having come to the hands of the editor,
is thought worthy of a place in these pages:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Warrington, 12th mo.
15th, 1795.

[.salutation]
Dear Friend--

In much sympathy and true brotherly love I present thee with these lines,
being much disappointed in not meeting thee here.
I hope you are on the mending hand,
and that I shall yet be favored to enjoy under your roof,
and amongst your very affectionate children, a few more of such agreeable hours,
of which I have already passed so many; when we had, added to our family comforts,
that of a most agreeable circle of dear brethren and sisters; and above all,
the Divine Master`'s presence to crown our little assembly;
when our parlor became as the school and nursing-room
for the disciples and children of Christ.

As to the business of the day, thou may be better informed than by me at present;
but may let thee know I am nearly through the visit to the families of Friends,
except to those in this place;
and though it is a work which has required much patience and perseverance,
yet it now affords me a secret satisfaction, and I seem clear that stopping amongst you,
and visiting the families in this monthly meeting, has been the way of peace.

Now, dear Isaac,
I have little more to say than that I wish thee to
keep above sinking under thy varied exercises;
as I think thou hast no just cause to distrust the arm that
has always borne thee up under all thy former troubles,
and brought thee up as from Jordan`'s bottom,
more fit for the Master`'s use than when thou wast going into it.
Thou hast my little help in spirit, which will not hurt thee, if it does thee no good.

If the state of thy family did not prevent,
I should write thee to meet me at Langtree meeting tomorrow.
Thou art still near and dear to me, with thy companion and children.
I take leave in much love and affection, and rest thy affectionate friend,

[.signed-section-signature]
David Sands.

[.postscript]
====

P+++.+++ S.--My love to dear John Thorpe,
with whom I have felt much since I heard of his trials in his family,
followed by his own indisposition: and to all my friends in thy freedom, in Manchester;
for sure I am, I love you, and you are near to my best feelings as a meeting.
I often look back with a humble hope of your growth in the best things

[.signed-section-signature]
David Sands

====

--
