== Chapter XIV.

[.chapter-synopsis]
* Interview with King George the Third
* Visit to the Southern, Western, and Northern Counties
* Meeting at Berwick
* Visit to Scotland and Carlisle
* Letters from Margaret Jecto
* Richard Reynolds
* Lindley Murray
* Case of H. Barnard
* Letter from D. Darby.

It was probably soon after his return from Ireland, in 1799,
that David Sands was permitted to have an interview with King George the Third,
at the Royal Palace;
when he was received by the king with much kindness and friendly feeling.
The king remarked to him that he had a high esteem for the Society of Friends,
and that they ranked amongst his most valuable subjects.

In the latter part of 1799, David Sands was engaged in some of the Southern counties,
particularly Sussex and Surrey;
and partly on account of the delicate state of his health,
he appears to have spent some months about Bristol.
In the first and second months of 1800, he visited some of the Western counties,
as Devonshire and Cornwall; and after attending the yearly meeting in London, he,
in company with his kind friend, James Harford, and his daughter Mary,
proceeded northwards, by way of Doncaster, York, Darlington, and Newcastle, to Edinburgh.
The writer of these memoranda well remembers his labors during a part of this journey,
having been appointed to accompany him as guide from Newcastle to Edinburgh.
His service in Newcastle was lively and edifying.
On the way from Newcastle to Edinburgh,
his mind seemed vigilantly awake to the pointings of duty;
and evincing a concern to have a public meeting at Belford, a large room was prepared,
and was well filled with an attentive audience.

At Berwick-on-Tweed he had also a public meeting.
The Town Hall was prepared and seated, and notice was well circulated.
By the hour of meeting, a rude rabble assembled;
and there being no Friend but his guide to attempt to keep order,
a scene of confusion was presented,
such as he never witnessed elsewhere on such an occasion.
They even attempted to break the deals which were used in seating the place.
When David Sands and James Harford arrived, he repaired to the seat provided for him,
and, without sitting down,
proceeded to remonstrate with the people with regard to their rude behavior,
especially on such an occasion; and as he proceeded,
his love to souls rose above their perverseness,
and he passed from expostulation to persuasion,
and to the inculcation of the precious truths of the Gospel,
in such a manner as riveted the attention of many, who listened with devout attention.
But the room being large and very full, and not being sufficiently lighted,
there continued to be annoyance from unruly people during nearly the whole of the meeting.
Notwithstanding these unfavorable circumstances, the writer left the place,
thankful in the persuasion that the power of Divine mercy
and truth had prevailed to the edification of many,
and to the honor of the Lord`'s holy name,
who enabled his servant to proclaim the glad tidings
of salvation through our Lord Jesus Christ.

There is reason to believe that David Sands paid a general visit to Friends in Scotland,
and attended the general meeting at Aberdeen.

In 1801, he again visited some of the Northern counties, and at Carlisle in Cumberland,
his labors appear to have been peculiarly blessed to some,
as the following letter evinces; we trust it may be read to profit:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Carlisle, May 13, 1801.

I trust, my dear friend,
(for such I shall ever esteem you,) that it is unnecessary for
me to apologize for the liberty I now take in addressing you.
You have, since your departure from Carlisle, employed much of my thoughts;
and I have frequently meditated with pleasure, and I hope with some profit,
on the discourses I heard you deliver,
and the serious conversations I have held with you.
I have regretted that I had not resolution to lay my heart open to you,
and to acquaint you with all my doubts and fears respecting my own situation.
I have the most earnest desire to serve God, in spirit and in truth.
I feel myself so much weaned from this world that I have not a wish concerning it,
but that I may use it in such a manner as not to abuse it.
My daily prayer to God is, that I may feel more and more what a poor, blind, helpless,
dependent creature I am; and that He would strengthen me by His mighty power,
to do His will on earth, even as it is done in heaven.
I bow with submission to His fatherly corrections,
being well assured that they are intended for my good.
I have been a rough oak, my dear friend, and required much hewing;
and it is still a source of great grief and sorrow to me to find
that my heart is far from being so humble as I wish it to be.
I am perfectly sensible of my own weakness,
and the proneness of my heart to be led away by the seducements of the world,
which has made me strictly adhere to the resolution I had formed,
on my first entering on a religious course of life,
of withdrawing myself entirely from its allurements and fascinations.
This perhaps is the cross I have to bear;
as it is the only thing in which I meet with opposition from my husband.
Yet I dare not give up this point;
fearing if I did I might fall back into that lukewarm state from which,
by the grace of God, I have been delivered.
I have now no enjoyment in the society and amusements of my former gay companions.
The sweetest hours I spend are in my own closet,
in meditating on the rich mercies of God, in holy contemplation of Him;
in a delightful survey of the person and offices of Christ my Saviour;
and in offering addresses of praise and thankfulness to Him,
and in devoting my whole soul to His service.

Yet I am often harassed with doubts concerning the safety of my state.
I see so many defects in myself daily, so much unlikeness to God, so much working of sin,
so much coldness of duty, and so many enemies to struggle with,
that I frequently feel quite discouraged;
and I am sometimes tempted to believe that a Divine
change has not yet been wrought in my heart.
This, my dear friend, was what I wished to communicate to you.
Can you give me any comfort?
I can with the utmost sincerity declare that my inward
desires are toward God and His glory,
in the present life,
and towards the enjoyment of Him in the world to
come--that I have a settled aversion to sin,
and a restless breathing of soul after likeness to God, and communion with Him.
I love his Saints, and delight in their society;
and much of my time is spent in prayer and supplication,
that he would sanctify by his holy Spirit, and assist me by his grace,
to prepare for that eternity to which I am hastening.

The severe affliction with which I have lately been tried, has loosened me from the world.
Oh may my whole concern for the future be "`so to
number my days that I may apply my heart unto wisdom.`"
Religion has indeed afforded me the strongest consolation,
under this afflicting dispensation of providence.
I have been enabled to say with the sweet Psalmist of Israel,
"`In the multitude of my thoughts within me thy comforts delight my soul.`"

I am afraid, my dear friend, I have trespassed too long on you,
therefore I must hasten to conclude my letter by assuring you that
you are daily remembered in my prayers before the Throne of Grace;
and if it should please the Almighty that we should see each other no more in this world,
I trust and hope we shall meet in a better, where all tears shall be wiped from eyes;
where there will be no more cloudy seasons or gloomy hours;
where we shall enjoy uninterrupted happiness in the presence of God.
Pray for me, my dearest friend,
that those clouds that hide the love of God from me may be dispelled;
that my faith may be strengthened, and that all hardness of heart may be removed.
(The conclusion wanting.)

[.signed-section-signature]
Margaret Jecto.

--

The following letter from his valued friend, Richard Reynolds,
is deemed worthy of preservation:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Coalbrook Dale, 4th mo.
30th, 1801.

[.salutation]
Dear Friend--

I am pleased to find I still retain a place in thy friendly remembrance,
and share thy brotherly sympathy, under my conflicts of mind; which,
though as I trust thou truly observes,
are more about things of an enduring nature than of this transitory world,
yet some outward occurrences have increased; and which bodily indisposition at times,
with the rapidly increasing infirmities of old age, have made me less able to bear.
Still I have to acknowledge, with humble thankfulness,
that hitherto I have been so supported that I faint not;
and though I am still surrounded with trials and temptations of various kinds,
and seem as weak as ever I was;
I endeavor to derive some confidence from experienced though unmerited preservation;
and some consolation from the certainty that the time of my probation and of my sufferings,
whether on my own account or that of others, must soon terminate,
and that if I do but hold out to the end I shall be saved.
For this I doubt not thy prayers will be united with mine,
when so engaged I may be brought to thy remembrance; and to be told so by thee,
will at all times be cause of rejoicing.

My sister, Deborah Darby,
is to accompany Rebecca Byrd from London into some of the Eastern counties;
as is our beloved friend Priscilla Gurney, (her former companion) Ann Dymond of Exeter.
Susannah Appleby has been some time attending upon our esteemed friend Mary Ridgway,
and will, I presume, continue for some time longer.
We are not without hope of seeing dear Samuel Smith and his companion,
on their way from Ireland to London, but if we do not,
and you meet in London at the yearly meeting,
I hope you will unite in remembrance of and prayers for me,
as you are united in the regard, and so far as I am enabled,
in the prayers of thy affectionate friend,

[.signed-section-signature]
Richard Reynolds.

--

The minds of many Friends at this period were deeply concerned for the
maintenance of the standard of truth as always held by the Society;
and the following letter from Lindley Murray to David Sands
evinces in what manner the subject obtained their attention:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
York, 5th mo.
16th, 1801.

[.salutation]
My Dear Friend David Sands--

About the time thou wilt receive this,
I believe thy mind will be much exercised by the prospect of the approaching trial,
to the faithful and upright minds, at the ensuing yearly meeting;
but I hope thou wilt be strengthened to lend thy hand to support the standard of truth,
so that the great cause will receive aid from thy exertions,
and thy own mind be comforted with the retrospect, even after many days.
It is a time when the standard-bearers are called on to display it, in the sight of men;
and I believe this can be done in the meekness of wisdom; and if so done,
will find an advocate and witness in the breasts, even of opposers.
I am comforted to find thou art where I believe it is thy place to be;
and I rejoice in believing that thy firm, but gentle, loving,
and Christian-like spirit and deportment, on this great occasion,
will do much for the cause of truth, and the peace of thy own mind.
The resolute support of our Christian principles,
and the pulling down the strongholds of sin and Satan,
are very consistent with love to the souls of those who are in error,
and with a tender desire and labor to reclaim them.

It will be a comfort to hear of thy welfare,
and of the prosperity of the good cause thou art engaged to promote.
I am sometimes apprehensive that thy feeble frame will suffer
considerably from the vicissitudes of climate,
travelling, etc.; to which I think thou wilt be exposed;
and that the mind will at times partake of this suffering,
and be disposed to attribute to more affecting causes the discouragements
which arise only from nature and the languor of the oppressed body;
but I trust that whatever thou mayest be permitted to undergo,
thou wilt cleave to and feel that support which will carry thee through every difficulty;
and make thee rejoice,
even in the sacrifice of spending and being spent for the
promotion of truth and righteousness in the earth.
If this sense and evidence is with thee, then it is enough:
mountains will be levelled and valleys filled up before thee,
and thou wilt be enabled to go on thy way in faith and peace.
When we reflect how much thou hast known of ill-health, disappointment, and affliction,
and how manifestly the Good Hand has been underneath to support and encourage thee,
we trust that confidence, even strong confidence in His goodness and faithfulness,
will never forsake thee; but the language of thy heart, even in deep probations, will be,
"`Lord, thou hast been with me from my youth;
thou hast redeemed me from the vanities of this world,
and set my affections towards thy blessed kingdom; thou hast sustained me in sore trials,
and when in sadness, hast been about my bed and my path.
Thou hast opened a way where I could see no way,
and hast raised the language of holy confidence and triumph in thy goodness and love.
Such marks of thy fatherly care bind me in submission.
I will not dishonor thee, and wound my own spirit,
by distrusting thy protection and favor.
All the evils of this life are not only transient as the morning dew,
but they are as the drops of the bucket,
in comparison of that joy and crown which thou hast given me to believe will,
through thy unutterable mercy, be my happy reward and portion.`"

It gave us much pleasure to perceive, by the tenor of thy letters,
that thy mind was favored with more comfort and cheerfulness than is often thy portion;
I hope it will continue to be thy lot, if not altogether, yet with few interruptions;
because it is better for the spirit and the body,
and not only invites beholders to enlist under a
Master who so visibly makes his servants happy,
but makes the servant more effectual to labor in promoting piety and virtue amongst men.
The depressed mind goes heavily on its way; and sometimes by the livery of sorrow,
may discourage some from entering or persevering in the service.
You have often to tell others that "`wisdom`'s ways are ways of pleasantness,
and that all her paths are peace;`" and when you are living examples of this happy truth,
you beautify and forcibly illustrate what you say.
There are few persons who have greater cause to rejoice in the Lord,
or to joy in the God of their salvation, than my beloved Friend.
He has been with thee from youth to gray hair;
He has caused thee to labor abundantly in His vineyard;
He has given thee a multitude of seals, attesting thy ministry;
and He has on many occasions supported and protected
thee in the midst of danger and discouragement.
When, therefore, the moments of distress approach,
and cast their sickening gloom around thee,
it will be good to remember the condition and language of the Psalmist of Israel,
who was in similar circumstances, "`Why art thou cast down, oh my soul;
and why art thou disquieted within me.`"
"`I will remember the Lord from beyond Jordan,`" etc.,
where he had received strong tokens of Divine favor,
the recollection of which renewed his confidence and strength.
I hope to have the comfort of hearing from thee soon;
and in that love which changeth not, remain thy affectionate friend,

[.signed-section-signature]
Lindley Murray.

--

The yearly meeting of 1801 was now approaching,
in the proceedings of which David Sands could not but feel deeply interested.

The reader will have observed an allusion to Hannah Barnard.
She came as a minister with proper certificates from America,
and during her travels developed unsoundness in doctrine,
similar to that which had been manifested in Ireland.
Her case obtained the attention of the Morning Meeting in London,
which took proper steps to prevent her further travelling in the ministry;
and she was dealt with for her unscriptural opinions.
She appealed against the disciplinary proceedings
which had become necessary in thus restricting her,
to the yearly meeting in 1801; which, after a weighty and solemn deliberation,
decided against her;
and she was ultimately disowned as a member of our religious
society by the monthly meeting in America to which she belonged.

A few were carried away by the plausibility of her public addresses,
during her stay in England;
but they were in several instances known to be unsatisfactory
to those of other religious denominations,
as well as to Friends.
The Society generally was too well persuaded and convinced of the importance
of faithfully maintaining our testimony to the doctrine of the Godhead of Christ,
and his propitiatory sacrifice;
and of the Divine authority and inspiration of the Scriptures of truth,
to be greatly shaken.

In the latter part of this year,
David Sands appears to have been engaged in the southwestern counties,
and after the yearly meeting of 1802, which he attended, and had some acceptable service,
he visited Essex and Suffolk, and in the 10th mo.
he appears to have been engaged in Sussex and Surrey quarterly meeting;
also in Northamptonshire; after which he spent some time about Bath and Bristol.

The following letter from Deborah Darby is worthy of preservation, though short;
the rather because nothing has yet been published respecting the long
and arduous labors and travels of this dedicated handmaid of the Lord,
whose labors in the gospel were blessed to many,
even to the awakening and convincement of some who in afterlife
proved eminent instruments in the Lord`'s hand,
in proclaiming the everlasting gospel of life and salvation through Jesus Christ,
and that to many and distant nations.
In her travels in America, and subsequently, her friend Rebecca Young,
afterwards wife of William Byrd, was her fellow-laborer:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Godalming, 5th mo.
30th, 1802.

[.salutation]
My Dear Friend and Brother, David Sands--

I am obliged by thy kind attention in writing me.
Thy fellowship is precious to me, and thy sympathy reviving.
I have felt my mind nearly interested in thy exercises,
and sincerely desire thy support and comfort under them;
and trust that He who hath been with thee in six troubles,
will be with thee in the seventh,
and give thee occasion to commemorate His goodness
in the language of "`Return unto thy rest,
oh my soul, for the Lord hath dealt bountifully with thee.`"

I have esteemed it a favor that I have been permitted to attend the late yearly meeting.
It has tended to the revival of my hope that the Lord is
still waiting to be gracious unto a backsliding people,
and is willing to turn our captivity, so that Jacob may rejoice and Israel be glad.
But be that as it may, "`Those who suffer with Christ will also reign with him.`"
When thou writes home, please to convey my dear love to thy relations,
and accept a large share thyself, from thy sincere friend,

[.signed-section-signature]
Deborah Darby.

[.postscript]
====

William and Rebecca Byrd`'s love to their beloved friend David Sands;
they nearly unite in the above affectionate salutation,
and sincerely desire that best support and direction
may continue to attend him in all his steps;
that whenever a retreat is sounded from the present field of arduous labor,
it may be attended with the possession of that peace
which the world can neither give nor take away.

====

--

In the spring of 1803, David Sands was at Worcester, and on the 10th of 4th mo.
he attended two marriages there.
During the rest of that year he appears to have spent much of his time about London,
Bristol, and Bath; at the latter place chiefly on account of his health;
which appears to have been greatly benefited by the Bath waters:
but he was often industriously engaged laboring in
his high vocation as a minister of the Gospel.

In 1804, he appears to have been laboring in some parts of Yorkshire,
and in Cheshire and Staffordshire quarterly meeting, also in Lancashire.
There is amongst his papers the substance of a testimony
which he bore in a public meeting at Macclesfield,
on the 24th of 5th mo., 1804;
and as there is frequent allusion in it to his own
religious experience in the early part of his life,
it is deemed worthy of a place in the Appendix to these Memoirs.
It may be regarded also as affording lively evidence,
not only of the style and character of his ministry,
but also of his soundness and clearness in word and doctrine.
It appears to have been taken down in shorthand by a person not of our Society.

In the spring of 1805,
the time arrived when this devoted servant of the
Lord saw his way clear to leave the shores of England,
where he had been engaged to labor in promoting the
glory of God and the good of souls for so many years,
and to return to his family and friends in America.
It may be seen, by the letters which from time to time he wrote to them,
that he not only often had them in tender and affectionate remembrance, but that,
from the second year of his travels in Europe,
he cherished the expectation of joining them after a moderate lapse of time.
In the lengthened period of service which was allotted him,
great at times must have been his trials both of faith and patience.
In the course of his arduous service, both in his own country and in Europe,
he frequently felt the absolute necessity, in order to ensure true peace of mind,
of obeying the Scripture injunction,
that when "`the Lord was pleased to show him light`" upon his path,
it then became his duty to "`bind the sacrifice as with cords to the horns of the altar,`"
and humbly and reverently follow his Divine Leader in the way of his requirings,
however much in the cross to his natural inclination.

Much sympathy was felt with this dedicated servant
of Christ in the course of these his trials,
by many of his friends, both in England and America,
which was evinced in a variety of ways.
Previous to his embarkation,
he received the following kind and brotherly salutation
from his long-tried friend Richard Reynolds.
Many of his dear friends in England felt deeply interested
for his preservation and welfare.
