== Chapter XV.

[.chapter-synopsis]
* Letter from Richard Reynolds
* Arrival at Home
* Letter from James C.
* David Sands`' Reply
* Visit to Philadelphia and to Canada
* Letter from James Neall
* Letter from John Murray, Junior
* A Remarkable Occurrence
* Conclusion.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Bristol, 4th mo.
8th, 1805.

[.salutation]
My Dear Friend--

I was duly favored with thy kind letter of the 6th of last mo.
Thou wast pleased to express a willingness to hear from me,
but did not tell me where thou wast likely to be,
previously to thy embarkation for America; nor from what port,
although thou expressed a thought of thy getting away, and most likely from Liverpool.
I received information on the 6th instant that thou wast about to sail from thence.
I avail myself of the first opportunity to express my sincere desire for thy preservation;
and hope that thou wilt find thy dear family and friends well and comfortable,
after so long a separation from them;
and that thou wilt be permitted to rest from such exercises as
have been thy portion in the latter part of thy stay in this land.
I rejoice with thee that thy mind is so much relieved,
and thy health better than for some time past.

I am sorry that any part of thy late trials should
have arisen from the person thou mentions.^
footnote:[William Hodgson, in his [.book-title]#Historical Memoirs,#
speaking of the firm testimony which David Sands bore against the errors of the Seceders,
remarks that he "`had been drawn, in the love of Christ, to visit Ireland,
and being led into very plain dealing among them,
in imparting the whole counsel of his Divine Master,
he became a principal mark for their enmity.
Many of them refused to acknowledge his ministry,
by uniting in the usual orderly practice of standing up and taking off the hat,
while he was engaged in meetings for worship,
in the solemn act of addressing the Most High.`"--Page 391.]
If he would have been advised by me, it would not have been so;
and as I could not prevent the publication, I thought it best to be silent;
insomuch that though I had a visit from him the latter end of last summer,
not a word passed between us on the subject of his book.
But I have expressed my entire disapprobation.
I shall be glad to hear from thee, whenever thou hast freedom to write to me,
on either side of the Atlantic;
and wherever thou art thou mayest assure thyself of my true love and regard.
I am become an old man, and feel increasing infirmities, from which,
in the common course of nature, death only can release me; and in that course,
probably will soon release me.
Nor am I without a hope that, through the mercy of God in Christ Jesus,
I also shall then be admitted where the wicked cease from troubling,
and the weary are at rest--everlasting rest--with
those who have been near and dear to us in this world,
and who are already entered thereinto.

Farewell, dear friend: continue to remember me;
and as thou shalt be enabled to approach the throne of Divine mercy with acceptance,
forget not thy affectionate friend.

[.signed-section-signature]
Richard Reynolds.

--

After taking a general and solemn leave of his many tender and affectionate friends,
he embarked at Liverpool, on board the ship "`Washington,`" bound for New York,
where he arrived in safety after a boisterous passage,
and was received with unfeigned love,
and with sincere thankfulness to that kind and overruling
Power who had supported him through many close trials,
and much bodily weakness,
and who had brought him safely back to his connections and friends.
After spending a few days in New York, where part of his family resided,
he reached his beloved wife and children and other friends.
He rested at home for some time; having often the company of many friends,
who participated in his peaceful enjoyment of the reward of faithful
dedication to the service of his Lord and Master Jesus Christ.

The following letter, with David Sands`' reply, though without date or full signature,
is thought worthy of insertion; and may most properly be introduced here:

[.embedded-content-document.letter]
--

[.salutation]
Most Worthy and Honored Friend--

Will you forgive the liberty I have taken in thus addressing you.
Feelings of gratitude and love will not permit me to remain silent.
I bless God, who has in mercy sent you, his faithful servant, amongst us,
to administer to my necessity by pouring out, as it were,
the oil and the wine into my wounded spirit; and to you, my precious friend,
I can acknowledge you have been as it were my guardian angel,
to pluck me as a brand from the burning;
and to plant in my bosom a hope that I may be found among the redeemed.
Your mission is one of love and good works;
to lead the souls of your fellow-men from sin and darkness
unto the bright and shining light of the holy Jesus,
their Saviour and Redeemer.
None feel the weight and benefit of your holy calling more than myself.
I was a poor benighted traveller, wandering in darkness and doubt;
often querying with myself, who is Jesus of Nazareth,
whom they call Saviour and Redeemer?
I have never known him, or seen his works, though it is said he wrought miracles,
raised the dead, and even gave up his life for the redemption of sinners.
I heard and read all this, but still queried,--Is it not a fable?
what have I to do with him?
His blood, if it was shed, is nothing to me.
I was, like Paul, a persecutor.
I cried peace, while peace was a stranger to my heart; I wandered up and down the earth,
in search of rest to my weary soul;
in the bright allurements of folly I believed I should find it; but like a phantom,
when near, it eluded my grasp.
Thus I passed my days in seeking pleasure, my nights in mourning;
and while my Heavenly Father was striving with me,
and knocking gently at the door of my heart;
though I was ready at times to cry out with anguish, I still rejected him, saying,
as it were, "`Go thy way for this time,
at a more convenient season I will send for thee.`"

Thus I mused on my situation,
reasoning with myself after this wise,--"`Is this earth our only abiding place,
or is there another?`"
I had been taught, in early life, to look only to this world for enjoyment,
as anything beyond was only ideal.
Mistaken belief! leading to ruin and disappointment.
I tried to believe there was no accountability;
but the good Spirit was still striving with me,
inviting me to the Fountain of Living Waters.
I turned from the world with disgust,
and endeavored to seek rest for my weary and sin-sick soul.
While wondering which way to turn my steps,
I heard that some people called Quakers had arrived in our village,
and were going to have a meeting in the schoolhouse that evening.
I had heard that yours were a self-denying people; singular in dress and address;
and I determined to go, being more prepared to receive amusement than instruction:
in truth, I tried to be an unbeliever in the things of God, and of His heavenly kingdom.
When I entered the house, I was struck with the awful solemnity that overshadowed you.
It were vain to attempt to describe my feelings, while we sat in this solemn silence.
It seemed as though my poor tempest-tossed spirit would have burst its confines,
and deserted its earthly tenement.
While in this state of conflict, you arose,
and commenced with those ever-memorable words "`Come unto me,
all ye who are weary and heavy laden; take my yoke upon you, for it is easy,
and my burden, for it is light.`"
Oh! that blessed invitation of our dear Redeemer unveiled the darkness, and I could see,
as in a glass, the very depths of my soul, and was ready to cry out, "`Lord,
be merciful to me a sinner.`"
Never shall I forget the sweet words of hope, which flowed from your tongue,
words of eternal life;
your countenance became radiant with the theme of
the goodness and glory of the Almighty God and Father,
who gave His dear Son, that through him we might be saved.
Oh! how soon the glimmering of hope dispelled the darkness of infidelity!
I felt the invitation was to me, and most joyfully accepted it,
for I was indeed weary and heavy laden, and longed for rest.
I returned home, my heart filled with praises to God;
the image of my suffering Saviour was before me,
and I felt I could suffer and die for His precious sake.
Oh! that my brethren, who are blind as I was, could see as I now do;
and oh! that there were more like you, commissioned, as I believe, from on high;
true and faithful servants, to bear the olive branch of peace to the soul,
and give glory to God our Father.
I have no objection to your showing this;
I would that all the world should know "`that whereas I was blind,
now I see;`" and most fervently I pray,
that infidelity may be no longer a foul stain on the earth; but that all should come,
"`taste and see how good the Lord is:`" that though their burdens are grievous to bear,
they may cast them upon Him and find rest.

I hope not to weary your patience with too long a communication.
My feelings on the subject I can liken only to an ice-bound spring,
now penetrated by the warm rays of Gospel love, which has gushed forth,
and will flow forever.
I know your valuable time is much occupied; but could you feel freedom to write,
if only a few lines, it would give me much comfort.
May you go on in the glorious work,
and may the great Lord of the harvest bless and crown your end with peace,
is the fervent prayer of your unworthy friend,

[.signed-section-signature]
James C.

--

[.embedded-content-document.letter]
--

[.letter-heading]
David Sands`' Reply.

[.salutation]
Dear Friend--

Thy letter of the 20th I received, but not until some time after its date:
the contents were truly comforting to me.
To know I have been the poor unworthy instrument made use of,
to bring even one sinful soul to the foot of the Cross,
is an evidence of my being rightly directed.
But, my friend, give to God all the glory; I am as nothing without His aid.
Praise His great and good name; yea, exalt it forever.
Oh, what a grievous sin is infidelity;
the mark of its footsteps may be traced by the desolation
and misery which follow close upon its train.
It brings a blasting mildew over the fair face of nature;
its poisonous influence spreads far and wide, like the deadly Upas: all who venture near,
feel its sickly withering effects.
I grieve to say there is much of it abroad in our land;
and though partly concealed under the cloak of Christianity,
its hideous deformity will sometimes appear;
but there is a healing balm for all who will apply it, and seek it while it may be found.
None ever were refused who (rightly) asked for mercy;
for the great attributes of His Majesty, who is Lord and Ruler over His people,
are justice, love, and mercy.
I rejoice with thee, my brother, who hast found the gracious Saviour: and I trust that,
as thou hast sinned much, thou mayest love the more.

As thou abidest in Him, He will be to thee a strong defence:
as a mighty rock in a weary land, and a refuge from the pitiless storms of life,
wherein thou shalt find safety and rest.
Though the tempest may beat outside thy dwelling, there will be sweet peace within.

Thou hast great cause to bless the goodness of Almighty God,
who has dealt mercifully with thee, in opening thine eyes,
that thou mayest see the dangerous path in which thou was journeying.
He willeth not the death of a sinner, but that all should repent and live.
He is a careful Shepherd, who daily watcheth over His sheep:
and should they wander from his fold, He will gently lead them back again,
chiding them only as a tender mother doth the child of her bosom.
I also have abundant cause to reverence His holy name;
He has been to me strength in weakness, riches in poverty;
and though I feel my frail bark to be weak and shattered,
I trust it will be strengthened to outride every tempest that may be allotted it.
I know where strength is, and hope ever to be favored to wait patiently for it,
and thankfully to prize it above all the joys and sorrows of time.
I could say much more in praise of His goodness, but time will not admit at present.

I recommend thee to the good Shepherd of Israel; and my earnest desire is,
that above all the comforts of this world, thou mayest find in thy own bosom,
as thou journeys on through life,
that sweet peace and consolation which will enable thee to bear up thy head in joy,
above all the storms and billows of this tempestuous and transitory scene.
Therefore, journey on; persevere in the good cause of Christ; be ever on the watch,
lest the enemy of thy soul`'s peace may assail thee.
Pray that the heavenly manna may be daily administered, to nourish and support thee;
and that thou mayest, when thy voyage of life is finished,
be favored to be found among his jewels; worthy of the language, "`Well done,
good and faithful servant,
enter thou into the joy of thy Lord,`" is the fervent breathing of my soul for thee,
my friend.

[.signed-section-signature]
David Sands.

--

After David Sands returned from his long visit to Europe,
he continued to take a lively interest in the welfare of the Society;
visiting occasionally many meetings and Friends in the neighborhood of his residence.
He also paid another visit to Philadelphia,
spending several months in visiting Friends in that city and parts adjacent.

His general health being very delicate,
he was not concerned to pay many very extensive visits,
except one to Canada in the year 1812.

He was led to labor amongst the French, and by the river St. Lawrence,
and had many meetings in Quebec and its neighborhood;
and was favored to return with the consoling persuasion that he had been endeavoring
faithfully to perform what he believed to be his religious duty.
He had often to travel in much bodily weakness, and in the winter season.
His last journey was to New England, where, in many places,
he found comforting evidence of the fruit of his former labors,
when travelling through the wilderness parts of that country before his visit to Europe;
and when he had frequently to labor where no Friends`' meetings had been previously held.
Now he had the satisfaction of finding monthly and quarterly meetings established.
At some of the meetings which he now attended there were sixty
vehicles (of different sorts) for the conveyance of Friends,
in districts where, on a former occasion,
he had been the first Friend known to have travelled in the work of the ministry.
After his return from this journey, he seldom went farther from home than New York,
where he paid his last visit about six months before his decease.
His increasing indisposition of body prevented his going much out, except to meeting;
and to visit some families in his own monthly meeting, which he felt concerned to do.

The following letters evince the sympathy, unity,
and interest in his welfare which continued to be cherished by his friends.
The first is from his old friend and fellow-laborer James Neall;
the second is an instructive communication from John Murray, junior, of New York; which,
though originally a confidential letter, yet now, after the lapse of so many years,
it is apprehended may suitably find a place in these Memoirs,
for the edification and instruction of others.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Brunswick, 6th mo.
6th, 1808.

[.salutation]
Dearly Beloved Friend David Sands--

Having opportunity, I may say thou art often in my remembrance,
and I among thousands should be glad to see thee in our land,
not doubting but that thou wilt be clothed with the
garment of praise for the spirit of heaviness.
I write these few lines to renew mutual love,
and to say I have lived to see the bread that thou cast on the waters,
in the region of the East, returning after many days, to the glory of God;
breathing peace on earth and good will to men;
although some sturdy oaks and tall cedars have failed every way.
Thou mayest remember, dear David,
how we passed along among the people during the inclement season of the year;
over ponds and lakes, hungry and cold;
and sometimes inwardly stripped and baptized for the dead;
all which cannot be fully expressed in this silent
way so plainly as felt experience gives it.

Although there have been great overturnings,
yet the Divine Parent causeth the sun to shine, and the south wind to blow,
as the extended sceptre of his continued mercy;
watering the garden of the soul that loves him,
and even continuing to make himself manifest, at times,
to them who inquire not after him.

May the Lord of the harvest clothe thy tender mind afresh
with a concern again to visit the churches in our land.

I have seen little children turn a snowball,
and it grew bigger so fast by turning that they would call for help.
As of old the fishermen did, when, by their Master`'s orders,
they had cast the net on the right side of the ship; even so,
when the sun warms the snow, and the north wind breathes upon it,
the last turning will collect more weight than several preceding ones.
Thou wilt understand my simple hints.

I conclude with a feeling of more love than can be expressed in this silent way,
and remain thy assured and affectionate friend,

[.signed-section-signature]
James Neall.

[.postscript]
====

I have written to thee one or two letters since thy return from Europe,
but have not had any answer.
I wish to receive a line from thee,
and an intimation of thy mind when thou lookest towards us.

====

--

[.embedded-content-document.letter]
--

[.letter-heading]
From John Murray, Jun., to David Sands.

[.signed-section-context-open]
New York, 7th mo.
21st, 1811.

[.salutation]
My Dear Friend--

Since thou left the city,
I have been very much indisposed with an attack of cholera morbus.
The frequent attacks of disease,
together with the debility which pervades my constitution,
are a continued memento or intimation,
that "`here we have no continuing city;`" hence the necessity of being prepared,
and of seeking an inheritance in that city which hath foundations,
whose maker and builder the Lord alone is.
Under these impressions, we are put in remembrance of duties still unperformed,
and that delays are oftentimes unwise and dangerous.
These reflections having at this time been renewedly brought into view,
revives a conversation we had together, on a subject seriously interesting to myself,
and perhaps in some degree to the Society of which I am a member.
Thy communications were no less calculated, than I presume they were intended,
to stir up the pure mind by way of remembrance,
in order that whatever religious service may be required,
there may not be an unwarrantable reluctance, or consultation with flesh and blood,
but a surrender to those requisitions which, in the unfoldings of Divine wisdom,
may be called for.

I assure thee, my dear friend, I have often recurred to seasons of favor,
when the light of truth-shined upon my understanding with, I apprehend,
indubitable clearness; and as often have I had to regret the want of faith,
and my aversion to become a fool: hence weakness and dimness of sight clothed my mind,
and rendered me less susceptible of those impressions which were
mercifully intended to enlarge the field of religious labor,
and perhaps open the way for moving in a sphere more repugnant to the wisdom
of the creature than any other service in which he had been previously exercised.
Thus, in retracing my steps, and in contemplating the path of duty,
(which I have believed was intended,) I feel at times very much discouraged,
and so much embarrassed with many doubts and difficulties, as to apprehend that,
as the right time appears to have passed by, it requires very clear evidence,
and nothing short of the "`woe,`" ought now to induce
a movement which at any period is awful,
and on all occasions should be accompanied with life and power.

It is improbable that I should have hazarded an exposure
of my sentiments and feelings in this way,
had not thy sympathetic mind led thee to a communication which unfolded sensations
that could not but excite in me some very serious and awakening reflections.
They met with something in my heart which so corroborated former impressions,
that I was ready to conclude thou was favored to judge,
and that not altogether from the seeing of the eye or the hearing of the ear.
Perhaps I have said enough on this subject.
I consider it a very delicate one, and only to be handled by a skilful workman.
I am now willing to leave it,
and in case thou shouldest believe it right to impart farther counsel and advice,
I hope I shall feel grateful for every word which may be dictated
under the influence of that wisdom which is profitable to direct.
I feel desirous that, as thou art advancing in life, and infirmities are increasing,
thou mayest be favored to witness an unshaken evidence that all will be well in the end.
And as a foretaste of the joys to come,
I wish thou may enjoy that calm and tranquillity of mind,
which is very desirable in the decline of life,
even as it relates to our comfort and welfare while in the body.
I am affectionately thy friend,

[.signed-section-signature]
John Murray, Jun.

--

[.centered]
=== A Remarkable Occurrence.

Many interesting incidents might be related of this truly devoted servant of his God,
David Sands; through whom the power and mercy of God to man, through Christ Jesus,
was often made manifest, in causing the lofty head to bow,
and the knee to bend in submission to his holy will.
The following is preserved as a remarkable evidence of it, which none should dare deny:--

In the course of one of his early journeys in the work of the ministry,
he arrived at a town or village where the Society
of Friends or their principles were unknown.
He put up at an Inn where was to be a large ball or assembly that evening.

Being their custom, on such occasions, to invite strangers who might happen to be there,
to join them; and his appearance being new to them, and very singular,
they invited him to attend; perhaps to add to their amusement as a subject of ridicule.
He accepted the invitation, and after they were all assembled,
and their mirth and music commenced, he walked into the midst of them.
His solemn and impressive demeanor struck the company with awe;
the music and dancing ceased, and they all stood in silent amazement, waiting the result;
when he commenced addressing them to the following import:

[quote]
____
My friends, for what purpose is this gay company assembled?
Is it to worship Almighty God; him from whom all your favors and blessings flow; who,
in his love and compassion, gave the dear Son of his bosom as a ransom,
that through him you might have eternal life?
Or have you rather suffered yourselves to be led
captive by the enemy of your soul`'s peace,
who, for a season,
may hold out bright and pleasant allurements to tempt
your unwary feet to stray from the true fold of peace,
revealed in and through Christ Jesus your Saviour and Redeemer;
he who suffered his precious blood to flow to wash away your sins?
Oh! be persuaded by a brother who loves you with
that love which flows from the Fountain of all good,
to turn from these follies and devices of Satan, which will lead you astray.
Oh! be persuaded, I say, to seek the Lord whilst he may be found;
turn to him and he will turn unto you; knock,
before the door of mercy is eternally closed,
and he will receive you and encompass you with unbounded love,
and lead you gently into pleasant places, even into the kingdom of heaven,
where you will rejoice forevermore; singing praises unto the Lamb.
Yea, he will be unto you as a shield and buckler;
and as your strong defence in times of trouble.
Suffer him not to stand knocking at the door of your
hearts until his head shall become wet with the dew,
and his locks with the drops of the night.`'
____

Thus did he continue to address them until the power
of the Most High was so made manifest among them,
that they listened to his communication with deep interest; and,
as some of them afterwards expressed, he appeared as a messenger from heaven,
sent to warn them of their danger.
Many of them were brought to tears whilst he was speaking; and after he concluded,
acknowledged, with gratitude, their sense of his solicitude for their welfare; saying,
"`We have heard this night what we never can forget.`"
After taking a tender leave of them, they separated,
almost forgetful of the cause for which they had assembled.
