== Appendix.

[.chapter-synopsis]
* Address to a young Friend
* On Silent Worship
* Testimony delivered at Macclesfield

The following remarks, from the pen of David Sands,
appear to be the fruits of experience, and are worthy of preservation

[.embedded-content-document.address]
--

[.letter-heading]
To a Young Friend.

I felt easy to communicate some observations that
I think will not be disagreeable to thee,
nor unprofitable for thee to consider of and weigh,
as they may be found useful in thy journey through life.
The subjects are,--Temperance, Prudence, and Fortitude.
I shall begin by a quotation from a great man, who, speaking on these subjects, says,
"`that the richest endowments of the mind are temperance, prudence, and fortitude.
Prudence is a universal virtue, which enters into the composition of all the rest;
and where she is not, fortitude loses its name and nature.`"
Self-denial is the most exalted pleasure;
and the conquest of evil habits is the most glorious triumph.
A wise man stands firm in all extremities;
and bears the lot of his humanity with a divine temper.
Virtue is made for difficulties, and grows stronger and brighter by such trials.
Men will have the same veneration for a person who suffers adversity without dejection,
as for great works demolished; the very ruins whereof are reverenced.
There is an heroic innocence as well as there is an heroic courage.
It is a maxim of prudence to leave things which are not useful before they leave us.
The true way to advance another`'s virtuous example, is to follow it;
and the best way or means to cry down another`'s vice, is to decline it.
The greater the difficulty, the more glory in surmounting it.
Skilful pilots gain their reputation from storms and tempests.
To be valorous is not always to be venturous.
As fortitude suffereth not the mind to be dejected with any evils;
so temperance suffereth it not to be drawn from honesty by any allurements.
A warm heart requires a cool head.
Courage without conduct, is like fancy without judgment; all sail and no ballast.

No man ever was cast down with the injuries of what is called Fortune,
but who had suffered himself before to be deceived by her favors.
Judgment is the throne of prudence; and silence is its sanctuary.
Nothing would fortify us more against any manner of accidents,
than possessing our souls with this maxim, that we can never be hurt but by ourselves:
if our reason be regulated by truth, and our actions according to it,
we are invulnerable.
A virtuous and well-disposed person is like good metal, the more he is fired,
the more he is refined; the more he is opposed by some,
the more he is approved by the good.
Wrong may well try him and touch him, but it cannot imprint upon him any false stamp.
It is a maxim amongst the Spanish, he who loses wealth loses much,
and he who loses a friend more; but he that loses his spirit, loseth all.
The virtue of prosperity is temperance; the virtue of adversity is fortitude; which,
in morals, is the more heroical virtue.
Prosperity is the blessing of the Old Testament; adversity is the blessing of the New;
which, when patiently and submissively endured, carrieth the greater benediction,
and the clearer revelation of God`'s favor.
A virtuous habit of the mind is absolutely necessary to influence the whole life,
and beautify every particular action;
and overbalances all the gilded charms of folly and vice.
The prerogative of good men appears plainly in this,
that men bear more sorrow to the sepulchre of the virtuous,
than to the boasted palace of the wicked.
To conclude, I may boldly venture to say, a man of virtue is an honor to his country,
a glory to humanity, a satisfaction to himself, and a benefactor to the world.
He is rich without oppression or dishonesty, charitable without ostentation,
courteous without deceit, and brave without vice.

--

[.embedded-content-document.address]
--

[.blurb]
=== Address to Religious Inquirers, on the Subject of Silent Worship; or Waiting Upon God.

[.blurb]
=== By David Sands.

Our Lord Jesus Christ hath told us, John 15:5, "`Without me ye can do nothing.`"
We therefore cannot perform divine worship acceptably without his assistance.
This assistance is to be received in spirit; for, saith the Apostle, Eph. 11:18,
"`Through him we (both Jews and Gentiles) have access by one spirit
unto the Father;`" and as our access is through his Spirit,
which is not to be commanded by us at our pleasure, we must necessarily wait for it.
This waiting must be in silence from the expression of words;
and also in stillness of mind from carnal thoughts and wandering imaginations.
For the utterance of words in worship is acting, not waiting;
is discoursing to others about God;
not seeking him in such a manner as that we may haply feel after him and find him;
agreeable to the Apostolic doctrine in Acts 17:27.

We, the people called Quakers, look upon the worship of the Omnipotent God,
the creator and judge of all,
to be the most solemn engagement the mind of man is capable of being concerned in.
And in consideration of his high and inconceivable majesty,
think it our duty to approach him with the greatest awfulness and reverence;
we therefore sit down to wait in silence;
seeking to have our minds introverted and collected from earthly thoughts,
and wandering cogitations, into a single steadfast looking towards him.

And herein we fail not to feel the gracious condescension
of divine love to touch our hearts,
less or more; which humbles our spirit, enlightens us to see our present duty,
and quickens us to perform divine and solemn worship in the presence of God;
either imperceptibly to the outward eye or ear, under a continuation of silence,
or by audibly breaking out into vocal exercise;
as we apprehend it may please the Holy Spirit to lead.
Thus we really witness the verity of that gracious declaration of our Lord,
Matt. 18:20, "`Where two or three are gathered together in my name,
there am I in the midst of them.`"
We also experience, according to the Prophet Isaiah 40:31,
"`They that wait upon the Lord shall renew their strength;`" and Lam. 3:25,
"`The Lord is good unto them that wait for him; to the soul that seeketh him.`"
The Royal Psalmist was no stranger to this silent waiting, for he adverts to it,
Ps. 37:7, "`Rest in the Lord,`" or according to the marginal correction,
"`Be silent to the Lord; and wait patiently for him.`"
He also practised it, Ps. 62:1,
"`Truly my soul waiteth upon (or is silent upon or before) God;`" which,
in the modern phrase,
may be thus rendered truly,--My soul is engaged in silent
attention upon God coherently with the wise man`'s cautions,
Ecc. 5:2, "`Be not rash with thy mouth,
and let not thy heart be hasty to utter any thing before God; for God is in heaven,
and thou on earth; therefore let thy words be few.`"
He well knew, as he expresses it, Prov. 16:1, that,
"`The preparation of the heart in man, and the answer of the tongue, is from the Lord.`"
Silent waiting was in practice amongst the Prophets, and those that attended them;
as appears particularly in the Prophecy of Ezekiel.
We find the spirit of the Prophet engaged in divine visions,
while the elders of Judah sat before him;
as it is described from the 1st verse of the 8th chapter to the 4th of the 11th chap.;
during the time of which visions it cannot be consistently
supposed he was either speaking to them,
or they to him, or to each other.

Permit me now to say, in answer to inquirers, that we, the people called Quakers,
do not wait with expectation of any supereminent influx of the Holy Spirit;
nor profess to be actuated by a very superior degree thereof,
to what we believe others may experience as well as us.
We do not, nor ever did, pretend to appropriate it exclusively in any degree to ourselves.
We have constantly inculcated (1 Cor. 12:7) that "`The manifestation
of the Spirit is given to every man to profit withal;`" and what
chiefly makes difference and contrariety amongst mankind is,
that some believe in it and obey it: others do not, but reject it; first in themselves;
and through the blindness and enmity which inevitably ensues thereupon,
oppose the effects of its appearance in others.
Let even such honestly put the question to themselves,--Is a gloomy
lethargic sleeper the necessary consequence of solemn silence?
Is there no such thing as mental worship, or worship in spirit and in truth,
unless the tongue be audibly employed?
Is it yet to be told (or made known) that the essence of worship is in the soul;
that bodily exercise is nothing, but as it is a consequence of that which is mental?
Of itself it is but form without substance.
It may amuse, but cannot profit; neither can it bring honor to the Holy Spirit,
for he is honored by his own fruits.
The essential honor thereof consisting in its having the preeminence in our hearts,
demonstrated by our obedience.
Was any virtue in the expression of words sufficient
to bring down the Holy Spirit amongst us,
they might be right in pressing them upon us.
But as the heat which may be raised in the mind, merely by external sound,
is not a divine influence, but sparks of man`'s own kindling,
so may we read their termination in the Prophet`'s
expostulation with Israel in ancient times,
(see Isaiah 1:11) which, when applied to the present dispensation,
and seriously and candidly considered,
will leave us conscientiously to follow what we have found right.
As the subject is weighty as well as extensive,
I feel it best to leave it for the present,
and refer the inquirer to the 10th and 11th Propositions
of [.book-title]#R. Barclay`'s Apology# for the People called Quakers.

--

[.centered]
=== The Substance of a Testimony

Delivered by David Sands at a public meeting held
at Macclesfield in Cheshire in the year 1804,
and taken down in shorthand by Thomas Mollineaux.

Note by the Editor.--Although the Society of Friends, as a religious body,
have never sanctioned or encouraged any of their own members in taking down in writing,
during their meetings for Divine worship,
the public testimonies delivered by their Ministers;
believing that the mind of a true worshipper would not feel at liberty to be so occupied;
yet in the various periods of the Society`'s history,
it has at times happened that persons not holding our religious views,
being present on such occasions,
have taken down in shorthand the substance of testimonies or sermons so delivered.
Some of these having been published,
have been regarded as valuable evidence of the soundness
in doctrine of the Ministers of the Society;
and esteemed not only on that account,
but as being of an instructive and edifying tendency.
In this way, we have preserved to us the substance of several testimonies delivered,
both in the early periods of the Society and a few of later date.
Several volumes of them have been printed and reprinted;
and are well worthy of a careful perusal.
But it should ever be borne in mind that there is often much Divine power
and unction accompanies the ministry of the Lord`'s servants and ministers,
which cannot be preserved in writing; and in many cases it has been this,
to which the most beneficial and lasting effects must be ascribed.
There is reason to believe that this often, in an especial manner, was the case,
as regards the ministry of David Sands.
We may easily conceive it to have been so when the following communication was delivered.
It was taken down by a person not of the Society of Friends;^
footnote:[Extract of a letter from Samuel Jesper, a Friend, of Macclesfield,
dated 12th mo.
10th,
1847.--It is an interesting fact that the individual who took down
in shorthand the testimony delivered by David Sands,
at Macclesfield, is still living here, viz., Thomas Mollineaux.
He is the author of an Arithmetic, much used in schools;
also the author of an approved system of Stenography, and some other works.
He is nearly ninety years of age, and has been, until quite lately, very active,
both mentally and bodily.]
and though from the appearance of the manuscript,
it is evident that it does not contain the whole of what was so delivered,
yet it is thought well worthy of preservation,
and may be regarded as a fair specimen of the convincing, persuasive,
energetic character of the ministry of David Sands.

[.embedded-content-document.testimony]
--

[.blurb]
=== Substance of the Testimony.

It pleased the Lord in the early part of my life to afford
me some awakenings or visitations of his love;
and caused them to operate, at least so far as to set me on thoughtful inquiry.
I was like those mentioned by one of the Prophets,
whose faces were turned Zionward--they were asking the way to Zion.
In this passage the way to heaven is alluded to,
as a way that we are to seek and inquire about.

We may remember that the church unto whom the Apostle wrote,
were called "`pilgrims and strangers,`" and they
are often represented in Scripture as "`travellers.`"
The Apostle beseeches them,
as "`strangers and pilgrims,`" to "`abstain from fleshly lusts,
which war against the soul.`"
Now, strangers have great need to be careful; if they are not careful,
without intending anything but good, they might miss the road, and get out of the way.
I say that they must be careful in their inquiries,
in order that they may not miss their way.
Not only to ask one another, but, as far as they may be enabled,
to inquire of such as are able to instruct them.
Strangers are often exposed to false information;
they must therefore direct their inquiries in such a way as that they may not be deceived,
lest they be led astray by such as undertake to be their guides,
that are not themselves perfectly acquainted with the true way.

They may also be led into unprofitable paths, and directed to wrong stages;
and this may lead them into unprofitable company,
whose communications may have so much weight with them,
especially if they take them for friends, as to stop their progress,
and induce them to take up with a false rest; I was going to say,
to stop at a half-way house.
We read of a people that had been in captivity,
and whilst in that state they became mixed;
they lost the pure language of the true Israelite,
and spoke a mixed language that was part Jew and part Ashdod;
they were not wholly either the one or the other,
and when presented in order to be examined before the Judges of Israel,
they could not stand in judgment; they were not approved, but driven away,
as such as would defile the priesthood and the sanctuary.

It appears also that there was something like this in the days of the Apostles;
for we read there were those that had begun well, and had run well for a season;
that they had begun in the Spirit, under the influence of the Spirit,
and had no doubt felt something of its power; but, from some cause or other,
had fallen away.
And we also find that some bad guides had got in amongst them;
that as there were false Prophets amongst the people of Israel,
so were there false teachers, even amongst the primitive Christians.
They were false, because they taught false doctrine,
and undertook to do what they were not qualified for;
and thus imposed on the people whom they undertook to guide;
and instead of leading them in those paths in which the faithful had advanced forward,
they turned them from the guidance of the Holy Spirit, to visible fleshly things;
so that they became so altered in their views as to imagine they
were able to become perfect by carnal notions and bodily exercises.

These things are recalled for our learning;
so that even in this generation we may remember our Lord`'s caution,
"`Take heed how ye hear;`" and not only so,
but what and whom ye hear-whom we receive as our guides.
We read that the time would come when many would cry, "`Lo, here is Christ, or Lo,
there is Christ,`" but, said our Lord Jesus Christ, "`Go ye not after them,
for the kingdom of heaven is within you.`"
As though he had said, "`Do not look abroad,
with an expectation of finding that which ye must find at home.`"
This seems to be implied by our Lord`'s exhortation also,
when he revived that passage in the Prophet Isaiah,
"`All thy children shall be taught of the Lord,
and great shall be the peace of thy children.
In righteousness shall they be established.`"
This is what I believe to be the privilege of the children of God in the present day;
they have a Teacher and an Instructor that will never lead them astray.
This pure guide teacheth them to profit; and leadeth them in the way that they should go.

But now to return to my own experience.
I was deeply engaged with earnest desires that I might come to a state of certainty,
and be settled upon a foundation that would stand sure;
and I found by experience that in this was involved
a work that required a great deal of inward labor,
for, as our Lord said, speaking of the hearers of his word,
he distinguished between the mere negligent hearers and the truly obedient disciple.
The latter he compares to a wise man, who digged deep,
and laid the foundation of his house upon a rock.
My earnest desire was to find this Rock, and to know what it was.
This digging seems to me to be digging through our own works and wills,
and getting deeper than our own thoughts and reasonings; in a word,
it is coming to a state of strippedness--to be of the poor in spirit.
This is the state those are in who have no will of their own,
no righteousness of their own; nor do they wish to have any thoughts of their own,
as it were;
but that all the powers of their minds should be brought
into an entire subjection to the will of God;
and into that course which is consistent with his will concerning them.
They know, as said the Apostle,
they of themselves cannot think a good thought or
do a good action without the Lord`'s help.
This state of inward poverty and strippedness is blessed: being stripped,
they are empty also; and being empty, they become partakers of the promise;
for "`blessed are they that hunger and thirst after righteousness,
for they shall be filled:`" they that hunger and thirst after the true knowledge of God,
and of our Lord Jesus Christ.
The language of their minds seems to be this: "`Oh Lord, give me thyself;
nothing short of thyself can satisfy my soul.
I want to be settled in a land of certainty,
that at all times I may be able to address thee as "`Our
Father which art in Heaven.`'`" These are true seekers,
and the promise is, that they shall find.
They do not ask things of God to consume them on their lusts;
or to make themselves appear respectable, as did the Scribes and Pharisees of old,
"`to be seen of men;`" but they ask those things because they feel the real want of them.

Now God knows thy heart, and he is not guided by words, or the sound of the voice;
but he answers mankind according to the sincerity of their hearts;
for God loves a sincere and upright heart; and the prayers of these he answers,
sooner or later; he fills them with the very things that they need.
I hope, my dear brethren and sisters,
that many of you know what it is to be filled with
things suitable to your respective states.
The Lord fills his own children with good things; he loads them with benefits.
Those that are poor, humble, and that are brought, as it were, out of themselves,
he causes them to say, as did a female on sacred record, "`My soul doth magnify the Lord,
my spirit hath rejoiced in God my Saviour.`"
Oh, ye that are poor, ye need not be uneasy, for he filleth the poor with good things.
But the rich thought they had plenty, and at the same time were really poor, wretched,
and miserable, and blind; and naked.`"
Instead of being rich, they were blind; they did not see their nakedness;
they did not wish to see themselves in the glass; they could not say in sincerity,
"`Lord, search me, try me, know my ways; and if there is iniquity in me, Oh Lord,
do thou take it away.
Let not thine hand spare, nor thine eye pity,
until thou makes me meet for thy holy kingdom.`"
But the rich and self-righteous do not want to see;
they would rather have an outside garment than an inside holiness.
If they can but pass along and be esteemed of men,
they care little about anything further.
Thus they bring blindness upon themselves, and hardness of heart:
for a blind hypocrite is always hard-hearted; and being hard-hearted,
you may observe how they could handle our dear Redeemer--He who went about doing good;
healing the bodily diseases of poor mankind.
And whilst doing those gracious acts, He comforted the widows;
often speaking a word of instruction and comfort for their poor souls.
All that came to Him in faith, He was willing to help: and when of the ten that came,
only one was right-minded, yet He healed them all.
When I touch upon the character of our Redeemer,
all the powers of my soul seem to be immersed in the spirit of my dear Redeemer.
My heart at times has melted when I considered the steps that he took:
weary and fatigued, whilst thus doing good.
The birds of the air had nests, the foxes had holes;
but the Son of Man had not whereon to lay his head.
The unbelieving Jews knew and examined his works;
they were constrained to acknowledge his notable miracles;
that man never spake like this man.
His works, like his garment, could not be picked to pieces.
They sifted the poor parents of the man that was born blind, whether he was their son.
We find they confessed that he was;
but by what means he was restored to sight they said they could not tell.
This shows how the fear of man operates, in those who give way to it.
They said, he is of age, ask him.
Thus they avoided confessing to the power of Christ.
But the poor but grateful man spoke as every true Christian should do:
"`I know that whereas I was blind, now I see;`" as though he had said,
"`I was a poor benighted creature, but Jesus met with me, I have found him;
Jesus of Nazareth I wanted to know him for years past; and whereas once I was blind,
now I see.`"

Well, my dear brethren and sisters, I have come to you in a large measure of gospel love.
Some of you can say we do know, and can certify that Jesus is the Son of God,
because he has given to you of his spirit.
I hope it is under the influence of the Lord`'s good Spirit,
that I feel free to make this remark to call upon you--to inquire of you,
whether you can say as much,--"`This I know, that whereas I was blind, now I see.`"

But I am not merely concerned for the little flock of Christ; I love them,
I own them as brethren;
but I am sometimes concerned for those who are still at a distance;
and I like when I am favored with strength to call upon these,
to consider their own situations.
You may be good neighbors, good fathers and mothers, at the same time you cannot say,
"`This I know, that whereas I was blind, now I see.`"
Even your associates amongst professing Christians
may not be such as will help you to heaven,
but rather lead you from the strait gate.
Remember the foolish virgins in the parable.
The time will come when it will be in vain for you to beg of the wise.
Therefore now put away the evil of thy doings: turn from all thy wickedness:
look to Him who is able to pardon thy sins.

But perhaps the Lord`'s servants have stretched out their hands to gather thee in vain;
"`will ye also be his disciples?`"
It is not the mere talkers about religion; yet we may talk on suitable occasions.
Come taste and see how good the Lord is.
Come hearken, and I will declare what God hath done for my soul.
This love wants all mankind to be happy.
To come to the feast of fat things in the Lord`'s holy mountain.
Lord, visit the nations; not only to convince and convict them,
but let thy power go forth to convert them!
This is the language of a Christian; I learned it from my Master.
I did not spring from a religious family; I was called out alone,
and had none to look to but God.
He set my feet upon a Rock; not a shadow of a great rock in a weary land only,
but a Rock from which I might drink in the wilderness.
This Rock was higher than myself.
He established my goings.
In the sufficiency of faith I have stood: I have not been shaken by the winds;
my foundation has stood firm and sure.

Yet even this reverend trust and confidence was nothing too much, in my early days,
when I had to appear in the character of a preacher.
But under the constraining power of Gospel love, if, through my labors,
I might but witness the drunkard becoming a sober man,
and the rich weaned from putting their confidence in uncertain riches,
my soul would leap for joy sometimes; and it will this night.
I feel as if the Lord was near to comfort; and I hope you will be comforted.
May the Lord`'s comfort make your souls like a watered garden;
that you and I may unite in offering to him thanksgiving and praise;
not merely from our mouths, but with our hearts.
It has been a valley of tears to many of you,
but will he not put your tears in his bottle,
and give you to see an end of all your trials.
Blessed are they that follow Christ.
Come, ye fathers and mothers; come, ye widows and orphan children; come,
ye mourners and heavy-hearted: you have had your seasons of bitterness in this world.
He can clothe you with the garment without spot or wrinkle,
and lead you to where none can steal from you.
"`Come, ye blessed of my Father.`"

I want you to be comforted, dear young people;
such of you as have been in the school of affliction,
and that are yet struggling to overcome.
Be good soldiers; do not be afraid; stand firm;
for the Creator of heaven and earth is your friend, your father, your God, your king,
and he will save you with a present and with an everlasting salvation.
Come boldly; it is for you, ye poor; you who can say, "`I have left all to follow thee.
Thou art my morning song and my evening praise.`"

Now I find freedom to tell you that the "`Spirit and the Bride say, come;
and let him that heareth say, come; and let him that is athirst come; and whosoever will,
let him come, and take of the waters of life freely.`"
Come, ye rich, come, ye poor, that lean upon the staff; come,
these blessings are offered to you; even for them that lie on the dunghill:
I invite you to come.
May you all flock as doves to the windows, this evening.
Come to Christ;
may you go home with your souls satiated with the things of God`'s kingdom.
I had no more view of what I should say when I came here than any one in this company;
it was from a sense of duty.
Five words spoken from the heart and to the heart is, in my view,
better than five thousand from the head only.
I was not brought up to the ministry;
and though what I say may be very broken and incoherent, yet it matters not,
if it may but help you to heaven:

I hope, my friends, there are none here that would choose Barabbas instead of Jesus;
none that would crucify afresh the Lord of glory.
The Jews of old added cruelty to their sin; they did it in a rough manner.

The nominal outside Christian is still a crucifier,
He is slain in the streets of their minds: Sodom, spiritually understood, is within us;
till the heart is changed, it is prone to wickedness and deceit.
There the devil`'s works are carried on.
But, my friends, I feel a hope that there are none here who cherish such a disposition;
but that your desire is to die the death of the righteous.
I do not offer myself as your best teacher and instructor; no,
I wish to direct your minds to the light, and spirit, and grace of God.
This is the true guide of the church.
"`I will not leave you comfortless,`" said our blessed Lord; no,
"`I will send you another Comforter;`" a teacher suited to your states.
He shall guide you into all saving truth; necessary truths; into every duty,
whether heads of families, masters or servants.
This is the true guide.
They who follow him are the sons of God; and he owns them.
"`As many as are led by the Spirit of God, they are the sons of God.`"

What an astonishing thought is this!
What a situation for worms, sinners, to be brought into;
to be covered with the wings of a dove!
He lights upon all believers.
This is the rock laid in Zion; the inward Zion of the heart;
the purified temple of the Spirit of God.
This is the true hope of salvation; Christ in you, by a living faith.
The changed heart becomes the house of God.
Such are prepared, eventually, to join with Moses in singing,
"`Great and marvellous are thy works, Lord God Almighty; just and true are thy ways,
thou King of Saints.`"
Methinks, my friends, the very thought of it cheers me.
Therefore dig through your own wills: throw away everything but one thing; the good part.
Here is the candle (the light of God`'s Spirit) by which you may read the book of conscience;
that by attending thereto, you may have your conversation in heaven;
and the blood of the Lord Jesus Christ will cleanse from all sin.

I was brought up amongst a people who preached that revelation is ceased.
One said, this is the way; another, that is it:
but I wanted to know the true way to heaven; therefore made little ado about a name.
I could read well.
I had read my Bible, but it seemed to be a sealed book.
I was confused, until it pleased God to put the right clue into my hand.
This brought me to see my vileness;
"`into the horrible pit,`" where I beheld clearly my deplorable condition.

His Spirit witnessing with our spirits is the best evidence:
thus I came to see a little clearer.
Ye are washed,`" saith the Apostle.
Thieves, liars, drunkards, unclean persons do not go to heaven as they are;
heaven is too clean a place for them.
There must be a change of mind.
"`Ye are washed, sanctified, justified in the name of the Lord Jesus.`"
These go to the "`fountain for sin and for uncleanness.`"
From a sense of their wants, they ask for it, and they obtain cleansing by it.
These are secret things.
I found that people must have eyes before they can see.
So I set off, left my father`'s house, and became a stranger.
I saw the propriety of attending to the things belonging to my peace.
Now I took joyfully the spoiling of my goods,
and rejoiced that I was worthy to suffer for Christ`'s sake.

Many go truckling and limping, and get on poorly, for want of the obedience of faith.
Things are beautiful in their season, and in their uses.
The Bible is a noble book, and I wish it was more read; but Christ is our Redeemer.
God is over all.

Consider the deplorable end of the wicked; when brought to their senses,
you may find them cursing their vanity.
"`Oh my enemy`"--`"Oh fashion`"--`"Oh the world,
you have brought me down to the grave full of tears.`"
"`I don`'t mind lying, but I fear that Judge whose laws I have transgressed.
I have said,
I have a visit to pay--I do not like to be singular--I
will be better by-and-by.`" But God says,
"`Now is the day of salvation.`"
We must work when the wind blows.
We must mind the breathings of God`'s Spirit upon us.
We must work when God is working in us; for "`where the word of a king is,
there is power.`"

I saw the Scriptures were all beautiful from end to end.
When sitting alone and feeling calm, I could read the Scriptures.
There is a spirit in man, and the inspiration of the Almighty giveth him understanding.
They who mind this, are on their way to Zion.
Christ is the Lord from heaven, a quickening spirit.
There is one body or church, and one spirit,
even as ye are called in the one hope of your calling.
There is but one true foundation, and no other can be laid,
and happy are they that build upon it.

The true temple is not made with human hands;
you carry a house with you that God has built; you will carry your altar,
and you will worship God in spirit and in truth.
Thus you will overcome the world, and be able to say, "`Oh Lord,
I have leaped over the walls of opposition.`"
"`Bless the Lord, Oh my soul, and all that is within me bless his holy name.`"

The Grace of our Lord Jesus Christ be with you all.
Amen.

--

[.the-end]
Finis.
